### ISSUE TITLE
ArgumentError "Cannot set :string fields"

### ISSUE THREAD

**Issue by sunaku** [ffi/ffi#10]
Hello,

I ran into a "Cannot set :string fields" error from `memory_op_put_strptr()` in `ext/ffi_c/AbstractMemory.c:389`.

Is this functionality just not implemented yet (should have raised a NotImplementedError), or is there a reason why users are prohibited from assigning the result of `FFI::MemoryPointer.from_string()` to a `:string` field inside a `FFI::Struct`?

Thanks for your consideration.

**Comment by athlite** [comment]
I guess you can circumvent this by defining a setter.
In the c source file:
```
void person_set_name(Person *p, char name[]) {
  p->name = strdup(name);
}
```
Ruby:
```
class Person < FFI::Struct
  layout :name, :string
end
module Libperson
  extend FFI::Library
  ffi_lib "libperson"
  attach_function :person_set_name, [Person, :string], :void
end
```
```
person = Person.new
Libperson.person_set_name( person, "John" )
puts person[:name]
````

**Comment by nevinera** [comment]
More straightforwardly (and I only use this for writing tests), you can write an `FFI::MemoryPointer` to a `:string` struct entry using something like `x.pointer.put_pointer(x.offset_of(:key), p)`. A setter implementation could look like:

```ruby
def name=(val)
  pos = offset_of(:name)  
  if val.nil?
    self.pointer.put_pointer(pos, FFI::MemoryPointer::NULL)
  elsif val.is_a?(FFI::MemoryPointer)
    self.pointer.put_pointer(pos, val)
  else
    fail("name= requires an FFI::MemoryPointer or nil")
  end

  val
end
```

It's dangerous to do this sort of thing normally (read: in any code that will be used in production), but it can save a *lot* of trouble in the setup and teardown of specs.
