### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by eregon** [ffi/ffi#1019]
@larskanis Hello, do you have plans for a release soon?

There seem to be [quite a lot of changes](https://github.com/ffi/ffi/compare/v1.15.5..master) on master and the last release was a while ago: https://github.com/ffi/ffi/releases/tag/v1.15.5

**Comment by larskanis** [comment]
Thanks for asking! Yes, there are a bunch for changes waiting for a new release.

I'm currently working on Ractor support. It's working quite well already, but I'm unsure how to solve the `typedef` definitions, which are global shared definitions, which are writable at any times. I'll open a PR for it soon. Maybe you can help me?

Beside from Ractor there are some open PRs I'd like to merge before the release.

**Comment by casperisfine** [comment]
I see the Ractor support has been merged.

Any other issue blocking the release we can help you with?

**Comment by ParadoxV5** [comment]
bump. 1.16 is out :tada:
