### ISSUE TITLE
Write RBS files

### ISSUE THREAD

**Issue by ParadoxV5** [ffi/ffi#1039]
Hi folks. I am a user of Ruby FFI.
I am interested in integrating it into my RBS workflow. Introduced with Ruby 3, [ruby/rbs](https://github.com/ruby/rbs/) is a type-checking language for Ruby.

What are your interests in RBS? Ideally, the Gem library would manage, update and ship the RBS of a Gem. I can help out with filling in the RBS documents or, in the meantime, upload a set of stubs to [ruby/gem_rbs_collection](https://github.com/ruby/gem_rbs_collection)

> Note that if you are the maintainer of the gem, you should consider moving RBS files to the gem's code repository and including them in the gem package instead.
> ⸺ [`ruby/gem_rbs_collection`, `docs/CONTRIBUTING.md`, § Become a code owner](https://github.com/ruby/gem_rbs_collection/blob/efc8580c38aa501593a8735ac6476cb42aaf6787/docs/CONTRIBUTING.md#become-a-code-owner)

**Comment by larskanis** [comment]
I think we can integrate the RBS files into the gem package. However I don't have any experience with RBS. I only read about it several times. It would be great if you could create an initial pull request.

**Comment by larskanis** [comment]
RBS API description will be part of ffi-1.17.0, currently available as prerelease ffi-1.17.0.rc2.

**Comment by larskanis** [comment]
Thank you @ParadoxV5 for all your great work regarding RBS!

**Comment by lloeki** [comment]
Thank you @ParadoxV5!

I've been meaning to do just that and upstream these, which we'll now be able to remove:

- https://github.com/DataDog/libddwaf-rb/blob/bf280637edac308a579399dd8e62db63d83a5949/vendor/rbs/ffi/0/ffi.rbs
- https://github.com/DataDog/dd-trace-rb/blob/f7a8fb5d597316c0ba274ee87a28948078f5a969/vendor/rbs/ffi/0/ffi.rbs

(... provided the small bits I've crudely written are implemented but from a cursory look it seems like they are)
