### ISSUE TITLE
1.16.2 RPM packaging on centos:7 fails

### ISSUE THREAD

**Issue by johrstrom** [ffi/ffi#1055]
While packaging this gem for centos/7 distribution I'm running into this error. 

As this is centos/7 - this issue is really more of an FYI than anything else. I'm really just putting it here to let people know in case they run into it.

```
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Compiling /work/el7-x86_64/BUILDROOT/ondemand-3.1.0-1.el7.x86_64/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.0-1/gems/ffi-1.16.2/ext/ffi_c/libffi/generate-darwin-source-and-headers.py ...
  File "/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.0-1/gems/ffi-1.16.2/ext/ffi_c/libffi/generate-darwin-source-and-headers.py", line 220
    f"--host={platform.target}",
                              ^
SyntaxError: invalid syntax
```

I don't really need to compile python in my RPM so as a workaround I'm going to use this spec statement (unconfirmed to work at the time of writing, but I suspect it will). 

```
%undefine __brp_python_bytecompile
```

Again - this is more of a heads up for other folks who run into the same issue. Feel free to close as won't do or similar. 

Thanks!

**Comment by johrstrom** [comment]
Undefining it through `%undefine __brp_python_bytecompile` did not work. 

Disabling it through `%global _python_bytecompile_errors_terminate_build 0` did though!

**Comment by larskanis** [comment]
> Disabling it through %global _python_bytecompile_errors_terminate_build 0 did though!

Is it something we should include in the ffi gem?

**Comment by johrstrom** [comment]
I don't see a `.spec` file in this repository so I don't know.

I'm not sure who's packaging & distributing the `rubygem-ffi` RPM, but they may need to do something if they want to update to 1.16.2 on centos/7 systems (the wiki page shows the maintainers and an email list).

https://packages.fedoraproject.org/pkgs/rubygem-ffi/rubygem-ffi/

Again - centos/7 being old and just about EOL I think doing nothing and just relying on 1.9.10 to be available on that platform is perfectly acceptable too.

**Comment by johrstrom** [comment]
I should clarify that this is really for EL/7 (ore even more specifically RedHat Enterprise Linux) because CentOS/7 has been end of life for some time but RHEL/7 will be EOL next in May of 2024.

I found the spec file here
https://src.fedoraproject.org/rpms/rubygem-ffi/blob/rawhide/f/rubygem-ffi.spec

With this ticket to update to `1.16.2`. 
https://bugzilla.redhat.com/show_bug.cgi?id=2240411

I cannot comment on RHELs ticketing system or else I would.  Hopefully they'll find this issue when they get around to updating that RPM.
