### ISSUE TITLE
1.16.4 is not published on https://rubygems.org/gems/ffi nor is tagged on GitHub repo

### ISSUE THREAD

**Issue by ParadoxV5** [ffi/ffi#1091]
Is it not released yet?
But [@larskanis has bumped VERSION to `1.17.0.rc`](https://github.com/ffi/ffi/commit/a0995bc)…

> Add Windows fat binary gem for Ruby-3.3

My Windows build of Ruby is waiting for the [`mingw-ucrt` variant](https://rubygems.org/gems/ffi/versions/1.16.3-x64-mingw-ucrt) to support Ruby 3.3…

**Comment by larskanis** [comment]
I first thought to release 1.16.4 but there are some additions that are not just bug fixes, so that it will be ffi-1.17.0. For the time being I uploaded ffi-1.17.0.rc1 and .rc2.
