### ISSUE TITLE
ffi-1.17.0 requires rubygems version >= 3.3.22

### ISSUE THREAD

**Issue by vshunkov** [ffi/ffi#1103]
Hello,

We are experiencing an error after resent ffi [changes](https://my.diffend.io/gems/ffi/1.17.0.rc2-x86_64-linux-musl/1.17.0-x86_64-linux-musl), despite we have a version lock in the Gemfile.lock. Could you please give an advice how we can troubleshoot or fix the problem?  

Error:
ffi-1.17.0-x86_64-linux-musl requires rubygems version >= 3.3.22, which is incompatible with the current version, 2.7.6

**Comment by xeron** [comment]
This should be reopen. Debian stable has ruby 3.1.2 and rubygems 3.3.15 and these versions won't change until the next OS release.

**Comment by alucardgt86** [comment]
Amazon Linux 2 also now reports
Notice: /Stage[main]/Jmeter/Exec[ffi]/returns: ERROR:  Could not find a valid gem 'ffi' (= 1.16.3) in any repository
Notice: /Stage[main]/Jmeter/Exec[ffi]/returns: ERROR:  Possible alternatives: ffi
Error: '/usr/bin/gem install ffi -v 1.16.3 -N' returned 2 instead of one of [0]
Error: /Stage[main]/Jmeter/Exec[ffi]/returns: change from 'notrun' to ['0'] failed: '/usr/bin/gem install ffi -v 1.16.3 -N' returned 2 instead of one of [0]
So we need the condition removing on ruby version to be the same as 1.16.3 if thats possible.

**Comment by unRARed** [comment]
Getting this on Heroku as well:

```
-----> Ruby app detected
-----> Installing bundler 2.3.25
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Setting up Test for Ruby/Rails
-----> Using Ruby version: ruby-3.1.2
-----> Installing dependencies using bundler 2.3.25
       Running: BUNDLE_WITHOUT='development' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Fetching gem metadata from https://rubygems.org/........
       ffi-1.17.0-x86_64-linux requires rubygems version >= 3.3.22, which is
       incompatible with the current version, 3.3.7
       Bundler Output: Fetching gem metadata from https://rubygems.org/........
       ffi-1.17.0-x86_64-linux requires rubygems version >= 3.3.22, which is
       incompatible with the current version, 3.3.7

 !
 !     Failed to install gems via Bundler.
 !
```

`gem "ffi", "< 1.17.0"` worked for us as well.

**Comment by mayuresh-srivastava** [comment]
> Getting this on Heroku as well:
> 
> ```
> -----> Ruby app detected
> -----> Installing bundler 2.3.25
> -----> Removing BUNDLED WITH version in the Gemfile.lock
> -----> Setting up Test for Ruby/Rails
> -----> Using Ruby version: ruby-3.1.2
> -----> Installing dependencies using bundler 2.3.25
>        Running: BUNDLE_WITHOUT='development' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
>        Fetching gem metadata from https://rubygems.org/........
>        ffi-1.17.0-x86_64-linux requires rubygems version >= 3.3.22, which is
>        incompatible with the current version, 3.3.7
>        Bundler Output: Fetching gem metadata from https://rubygems.org/........
>        ffi-1.17.0-x86_64-linux requires rubygems version >= 3.3.22, which is
>        incompatible with the current version, 3.3.7
> 
>  !
>  !     Failed to install gems via Bundler.
>  !
> ```
> 
> `gem "ffi", "< 1.17.0"` worked for us, too.



> Getting this on Heroku as well:
> 
> ```
> -----> Ruby app detected
> -----> Installing bundler 2.3.25
> -----> Removing BUNDLED WITH version in the Gemfile.lock
> -----> Setting up Test for Ruby/Rails
> -----> Using Ruby version: ruby-3.1.2
> -----> Installing dependencies using bundler 2.3.25
>        Running: BUNDLE_WITHOUT='development' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
>        Fetching gem metadata from https://rubygems.org/........
>        ffi-1.17.0-x86_64-linux requires rubygems version >= 3.3.22, which is
>        incompatible with the current version, 3.3.7
>        Bundler Output: Fetching gem metadata from https://rubygems.org/........
>        ffi-1.17.0-x86_64-linux requires rubygems version >= 3.3.22, which is
>        incompatible with the current version, 3.3.7
> 
>  !
>  !     Failed to install gems via Bundler.
>  !
> ```
> 
> `gem "ffi", "< 1.17.0"` worked for us, too.

@unRARed How did you downgrade ffi? This gem is something which not mentioned directly in Gemfile and I guess it's gets installed as part of dependency.
