### ISSUE TITLE
Why 3.4-dev disallowed explicitely for part of `1.17.0` releases?

### ISSUE THREAD

**Issue by mensfeld** [ffi/ffi#1109]
Hey,

I noticed that the `ruby_version` limitation on some of the platforms is now locked to `< 3.4-dev`. Why is that?

Is there some strict technical reason to do so? I was not able to find it in the PRs nor issues (sorry if I missed that).

It makes it a bit harder for gem maintainers like myself to prepare for Ruby 3.4.

**Comment by mensfeld** [comment]
Closing. @KJTsanaktsidis answered this in private, explaining that ABI is not stable.

**Comment by ktecho** [comment]
@KJTsanaktsidis Do you plan on release a new version now that Ruby 3.4 has been released? Thanks!
