### ISSUE TITLE
Issue with post-fork callback execution (FFI Callback Dispatcher not restarted)

### ISSUE THREAD

**Issue by mensfeld** [ffi/ffi#1114]
Repro:

Run this docker container to get Kafka: https://github.com/karafka/karafka/blob/master/docker-compose.yml with `docker-compose up`

Save and run the below code. It will  install my [rdkafka](https://rubygems.org/gems/rdkafka) gem and run:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rdkafka'
end

require 'rdkafka'
require 'securerandom'

def create_topic(name = SecureRandom.uuid)
  Rdkafka::Config
    .new('bootstrap.servers': '127.0.0.1:9092')
    .admin
    .create_topic(name, 1, 1)
    .wait

  puts "[#{Process.pid}] Topic #{name} created!"
end

# This will work correctly and will create topic and not hang
create_topic

# Now we will fork ourselves few times
fork do
  # Expectation is for this to also print create but will hang on `#wait`
  # because the callback never kicks in
  create_topic
end

# Lets give it a moment
sleep(5)

# Now this will work
fork do
  # Now if I do the same but force-overwrite the already existing rdkafka
  # callback, all will work
  # Remove it not to get irrelevant warnings
  Rdkafka::Callbacks.send(:remove_const, :BackgroundEventCallbackFunction)
  Rdkafka::Callbacks::BackgroundEventCallbackFunction = FFI::Function.new(
      :void, [:pointer, :pointer, :pointer]
  ) do |client_ptr, event_ptr, opaque_ptr|
    Rdkafka::Callbacks::BackgroundEventCallback.call(client_ptr, event_ptr, opaque_ptr)
  end

  create_topic
end

sleep(5)
```

I was able to establish, that upon fork the `FFI Callback Dispatcher` thread is not started back.

This is how I define the callback function: https://github.com/karafka/rdkafka-ruby/blob/main/lib/rdkafka/callbacks.rb#L153

If that's me doing something wrong I would love to get info how to fix that.

**Comment by KJTsanaktsidis** [comment]
I think we might need something like this? https://github.com/ffi/ffi/commit/62005f00e21c90eaba9657d388261774ce033bf6

If we agree I can polish that up and turn it into a PR next week.

**Comment by mensfeld** [comment]
Yeah, we definitely need this otherwise, it will be dangling not only in rdkafka. Thank you :pray:
