### ISSUE TITLE
Fix mistakes in wiki

### ISSUE THREAD

**Issue by natsu1375** [ffi/ffi#1129]
https://github.com/ffi/ffi/wiki/Examples#warning-dont-use-managedstruct-when-you-want-type-casting

```
  obj_ptr2 = FFI::MemoryPointer.new :pointer
  nfound = MyLibrary.find_first_match("foobar", obj_ptr2)
  obj_ptr2=obj_ptr2.read_pointer() ## MISSING this line
  obj2 = MyLibrary::SomeObject.new(obj_ptr2) # wrap ruby object around C pointer
  puts obj2[:name] # => 'foobar'
```

The returned `obj_ptr2` is of type `struct SomeObject**`, so there's a missing  dereference before it's passed to `MyLibrary::SomeObject.new`

**Comment by larskanis** [comment]
Thanks for the notification and the fix! I updated the section accordingly.
