### ISSUE TITLE
Windows: cannot load such file -- ffi_c (LoadError)

### ISSUE THREAD

**Issue by aslakhellesoy** [ffi/ffi#176]
1.0.10 is broken on Windows MRI (1.9.2 and 1.9.3) as of this commit: 8e86ddbc78b552b11877dca9ee85e99d0fc87ee3

1.0.9 works fine.

**Comment by ManuSakrepatna** [comment]
gem install ffi --pre
This worked for me under windows

**Comment by ismailakinkunmi** [comment]
> gem install ffi --pre

thanks, it work for me
