### ISSUE TITLE
Failed compiling for Ruby2.0.0p0 x64 under windows

### ISSUE THREAD

**Issue by Crossverse** [ffi/ffi#250]
trying: gem install ffi
got:
make[3]: Leaving directory `/c/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.4.0/ext/ffi_c/libffi-x64-mingw32'
make[2]: Leaving directory`/c/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.4.0/ext/ffi_c/libffi-x64-mingw32'
make[1]: Leaving directory `/c/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.4.0/ext/ffi_c/libffi-x64-mingw32'
compiling AbstractMemory.c
compiling ArrayType.c
compiling Buffer.c
compiling Call.c
compiling ClosurePool.c
compiling DataConverter.c
compiling DynamicLibrary.c
compiling ffi.c
compiling Function.c
Function.c: In function 'callback_invoke':
Function.c:463:9: warning: passing argument 2 of 'rb_rescue2' makes integer from pointer without
 a cast [enabled by default]
In file included from c:/Legacy/Ruby200-x64/include/ruby-2.0.0/ruby.h:33:0,
                 from MethodHandle.h:28,
                 from Function.c:21:
c:/Legacy/Ruby200-x64/include/ruby-2.0.0/ruby/ruby.h:1404:7: note: expected 'VALUE' but argument
 is of type 'struct gvl_callback _'
Function.c:463:9: warning: passing argument 4 of 'rb_rescue2' makes integer from pointer without
 a cast [enabled by default]
In file included from c:/Legacy/Ruby200-x64/include/ruby-2.0.0/ruby.h:33:0,
                 from MethodHandle.h:28,
                 from Function.c:21:
c:/Legacy/Ruby200-x64/include/ruby-2.0.0/ruby/ruby.h:1404:7: note: expected 'VALUE' but argument
 is of type 'struct gvl_callback *'
compiling FunctionInfo.c
FunctionInfo.c: In function 'fntype_initialize':
FunctionInfo.c:177:15: error: 'FFI_STDCALL' undeclared (first use in this function)
FunctionInfo.c:177:15: note: each undeclared identifier is reported only once for each function it appears in
make: *_\* [FunctionInfo.o] Error 1

Gem files will remain installed in C:/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.4.0 for inspection.
Results logged to C:/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.4.0/ext/ffi_c/gem_make.out

**Comment by ManuSakrepatna** [comment]
gem install ffi --pre   - worked for me under windows
