### ISSUE TITLE
Internal error in read_array_of_type ?

### ISSUE THREAD

**Issue by hadmut** [ffi/ffi#266]
Hi, 

I'm just trying to use a c library with a function that returns a pointer to a struct. I'm aware that there is such a beast like FFI::Struct, but tried to read data directly from the pointer returned by the function call, like given in the Howto-Examples:

puts ptr.read_array_of_type(FFI::TYPE_UINT8, :get_uint8, 4)

which runs into an error message:

/home/hadmut/.gem/gems/ffi-1.8.1/lib/ffi/pointer.rb:99:in `get_uint8': wrong number of arguments(0 for 1) (ArgumentError)
    from /home/hadmut/.gem/gems/ffi-1.8.1/lib/ffi/pointer.rb:99:in`block in read_array_of_type'
    from /home/hadmut/.gem/gems/ffi-1.8.1/lib/ffi/pointer.rb:98:in `times'
    from /home/hadmut/.gem/gems/ffi-1.8.1/lib/ffi/pointer.rb:98:in`read_array_of_type'
    from test_ffi.rb:35:in `<main>'

looks like some inconsistency in the code...

regards

**Comment by 4ndv** [comment]
This issue is STILL present!
