### ISSUE TITLE
Hook Procedure not working!

### ISSUE THREAD

**Issue by AntonSynytsia** [ffi/ffi#283]
For some reason when I activate the hook procedure, it freezes the application, while it worked fine when I used [win32-api](https://github.com/djberg96/win32-api)!

Here's the code:

``` Ruby
require 'ffi'

module HookProc

  extend FFI::Library
  ffi_lib :user32, :kernel32
  ffi_convention :stdcall

  # Hook reference
  #   http://msdn.microsoft.com/en-us/library/windows/desktop/ms632589(v=vs.85).aspx
  #
  callback :procedure, [ :int, :uint, :long ], :int
  attach_function :callNextHookEx, :CallNextHookEx, [ :pointer, :int, :uint, :long ], :int, :blocking => true
  attach_function :setWindowsHookEx, :SetWindowsHookExA, [ :int, :procedure, :uint, :uint ], :pointer
  attach_function :unhookWindowsHookEx, :UnhookWindowsHookEx, [ :pointer ], :bool
  attach_function :getCurrentThreadId, :GetCurrentThreadId, [], :int

  @hhook = nil
  @tid = getCurrentThreadId

  # KeyboardProc callback function
  #   http://msdn.microsoft.com/en-us/library/windows/desktop/ms644984(v=vs.85).aspx
  #
  KeyboardProc = Proc.new() { |nCode, wParam, lParam|
    puts wParam
    state = lParam >> 30 # 0 - onKeyDown, -1 - onKeyUp, 1 - onKeyExtended
    unhook if wParam == 0x1b and state == 0 # on escape key down

    # Pass the hook information to the next hook procedure.
    #callNextHookEx(nil, nCode, wParam, lParam)
    # May return a non-zero value to prevent the system from passing the message
    # to the target window procedure.
    1
  }

  class << self

    def hook
      return false if @hhook != nil
      @hhook = setWindowsHookEx(2, KeyboardProc, 0, @tid)
      puts 'hook called!'
      true
    end

    def unhook
      return false if @hhook == nil
      unhookWindowsHookEx(@hhook)
      puts 'unhook called!'
      @hhook = nil
      true
    end

    def status
      @hhook != nil
    end

  end # class << self

end # module HookProc
```

When I called HookProc.hook, and pressed the key it set the application to not-responding mode! Is there anything I should optimize for it to work? - cause it worked when I used win32-api (i.e Its callbacks and functions)

**Comment by rawhiteside** [comment]
Is it rude to resurrect an old, closed thread?  I want to install a hook myself, and I'm confused about the status of this.  I tried the above code, and it still doesn't work.  Further, the last comment says the project was abandoned?  It doesn't appear to be dead.  Enlighten me, please!

**Comment by djberg96** [comment]
@rawhiteside The ffi project was briefly offline because Wayne had a meltdown. It was resurrected shortly afterwards and is definitely not dead.

If you have an issue, please post it here or on the ruby-ffi google group.

**Comment by AntonSynytsia** [comment]
Apparently I don't think you can setup a Hook Procedure using Ruby FFI. You can, however, use Win32-API by Daniel Berger. See my comment above, posted on Sept 23, 2013, for an example.

**Comment by djberg96** [comment]
@AntonSynytsia Please post an issue in ruby-ffi or on the ffi github project page. Maybe it could be made to work?

**Comment by AntonSynytsia** [comment]
@djberg96 Its not a problem for me any more. A long time has passed since I migrated all my Windows API dependent code to a Ruby C extension. But since you asked, I will post an issue.

**Comment by AntonSynytsia** [comment]
Submited an issue here: https://github.com/ffi/ffi/issues/457
