### ISSUE TITLE
FFI::Pointer.new(int).address returns incorrect value for unsigned integers with JRuby

### ISSUE THREAD

**Issue by djberg96** [ffi/ffi#313]
It seems that when using JRuby it returns an incorrect value for the address of an unsigned integer:

```
# Should be (1 << FFI::Platform::ADDRESS_SIZE) - 1
FFI::Pointer.new(-1).address # Returns -1 instead of correct value
```

I wasn't sure if this should be reported here or in the JRuby project. If I've made a mistake, I'll report it there instead.

**Comment by graywolf** [comment]
> I'll address this on the jruby side when i get a chance.

Was closed in jruby without any fix, so this should be reopened... I think.

**Comment by tduehr** [comment]
This is a JRuby problem. Fortunately, Java 8 solves this somewhat... https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#toUnsignedLong-int-
