### ISSUE TITLE
Please add more prepend TypeDefs

### ISSUE THREAD

**Issue by windwiny** [ffi/ffi#320]
On win32 platform, system api use a lot of prepend TypeDef, like HANDLE, HWND, DWORD, WPARAM, LPARAM, etc..

In order to more easily and safer convert C/C++ function declare to RUBY FFI module, please add more independent platform prepend TypeDefs.

like add below to lib/ffi/types.rb 

    TypeDefs.merge!({
        :HANDLE => Type::ULONG,
        :HDC => Type::ULONG,
        :HINSTANCE => Type::ULONG,
        :HWND => Type::ULONG,

        :ATOM => Type::USHORT,
        :BOOL => Type::INT,
        :BYTE => Type::UCHAR,
        :DWORD => Type::UINT,

        :LPCSTR => Type::STRING,
        :LPSTR => Type::STRING,
        :LPVOID => Type::POINTER,

        :WPARAM => Type::UINT,
        :LPARAM => Type::UINT,

        # :LPWSTR =>,
        # :LPCWSTR =>,
        # :WINBOOL =>,
        # :WCHAR => Type::STRING,
        # ... more
    }) if RUBY_PLATFORM =~ /win/i || RUBY_PLATFORM =~ /ming/i

Make the parameter type is more like the original definition.
like

      attach_function :CloseHandle, [:ulong], :bool
to

      attach_function :CloseHandle, [:HANDLE], :bool

.

**Comment by tduehr** [comment]
I'll have to remember about that library.
