### ISSUE TITLE
cannot load such file -- ffi_c (LoadError)

### ISSUE THREAD

**Issue by anilreddy** [ffi/ffi#368]
Hi,

Today I have updated ruby version to 2.1.3 in windows OS and try to run a simple watir script & I came across this issue.

``` batchFile
C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': ca
nnot load such file -- ffi_c (LoadError)
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ffi-1.9.3-x86-mingw32/lib/ffi.rb
:14:in `rescue in <top (required)>'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ffi-1.9.3-x86-mingw32/lib/ffi.rb
:3:in `<top (required)>'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/childprocess-0.5.3/lib/childproc
ess/windows.rb:1:in `<top (required)>'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/childprocess-0.5.3/lib/childproc
ess.rb:176:in `<top (required)>'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.43.0/lib/se
lenium/webdriver.rb:1:in `<top (required)>'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.43.0/lib/se
lenium-webdriver.rb:1:in `<top (required)>'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/watir-webdriver-0.6.10/lib/watir
-webdriver.rb:2:in `<top (required)>'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from tests.rb:2:in `<main>'
```

**Comment by niwo** [comment]
Same problem here, also on CentOS7

**Comment by tduehr** [comment]
Please file a separate ticket for the centos7 problem. Please also include how/where you've installed ruby.

**Comment by sharanKumar** [comment]
@tduehr I have this issue still . I tried "gem -rdevkit install ffi --platform=ruby ffi" but it throws error saying -rdevkit is an Invalid option .

I have  "ruby 2.2.1p85 (2015-02-26 revision 49769) [i386-mingw32]" . I am completely new to ruby , Please tell me if i am in the right way .

**Comment by tduehr** [comment]
There's a regex problem currently, it's been fixed in HEAD but didn't make the gem. It's a fairly simple fix. Take a look at https://github.com/ffi/ffi/commit/4168ef3dbd56a7b52978efb2ff7d0dc448f8f8f1

**Comment by brawneyman** [comment]
Thank you, the ^'s fixed my problem!

**Comment by nikhilvs** [comment]
gem install ffi --platform=ruby fixed for me

**Comment by Ajedi32** [comment]
I was able to fix this by uninstalling the ffi gem completely (`gem uninstall ffi`), then reinstalling with `gem install ffi --platform=ruby`, as recommended by others in this thread.

**Comment by daddie888** [comment]
The question is why create such problems..
Using 2.3 and 1.9.3, its problems like this that force me using old versions half of the time.

> Ruby 2.1 introduces ABI breakage which means compiled C extensions with previous
> 1.9.3 or 2.0.0 will not run against Ruby 2.1.

**Comment by kaizamm** [comment]
gem:2.6.11 
ruby:ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
CentOS Linux release 7.2.1511 (Core) 
I still have this problem 
use --platform=ruby didn't slove my problem

**Comment by ManuSakrepatna** [comment]
gem install ffi --pre
This worked for me under windows

**Comment by dorianmariefr** [comment]
Addng `gem "ffi"` to my `Gemfile` fixed it https://stackoverflow.com/q/65000467/12544391

**Comment by padsalatushal** [comment]
> Addng `gem "ffi"` to my `Gemfile` fixed it https://stackoverflow.com/q/65000467/12544391

works for me. thanks .
