### ISSUE TITLE
Could not find ffi-1.9.4 in any of the sources

### ISSUE THREAD

**Issue by ericbrooke** [ffi/ffi#374]
Fetching source index from https://rubygems.org/
Could not find ffi-1.9.4 in any of the sources

Have you updated on ruby gems?

**Comment by danielballan** [comment]
Why was it yanked?

**Comment by danielballan** [comment]
Apparently 1.9.4 is a dependency-of-a-dependency in one of my old packages, so resolving this is now tricky. Did it have to be yanked completely?

**Comment by simi** [comment]
I think (https://github.com/ffi/ffi/issues/371) https://github.com/ffi/ffi/commit/0409fa86a070ecddc078e4de8a3b78b5dfe41053 was the reason.

**Comment by danielballan** [comment]
Thanks.

**Comment by tduehr** [comment]
Yup, that's it. 1.9.4 was up for a very short time, Pretty surprised anyone grabbed it as a dependency.
