### ISSUE TITLE
uintptr_t is wrong size on 64-bit JRuby

### ISSUE THREAD

**Issue by djberg96** [ffi/ffi#396]
I noticed that a 64-bit JRuby is handling :uintptr_t incorrectly. It should give me an 8 byte pointer, but I'm getting a 4 byte pointer instead:

    # 64-bit MRI returns 8, but a 64-bit JRuby returns 4
    FFI::MemoryPointer.new(:uintptr_t).size

My workaround for now is this:

    if RUBY_PLATFORM == 'java' && ENV_JAVA['sun.arch.data.model'] == '64'
      :ulong_long
    else
      :uintptr_t
    end

**Comment by tduehr** [comment]
issue moved to jruby
