### ISSUE TITLE
Methods missing to get/read write/put :size_t, :ssize_t

### ISSUE THREAD

**Issue by Asmod4n** [ffi/ffi#398]
Have a need for read_size_t from a FFI::Pointer, e.g. wrap https://github.com/jedisct1/libsodium/blob/5c3c132e47e119808ef98d45560772c335c640b4/src/libsodium/include/sodium/utils.h#L34 with ffi.
Here is how i currently wrap it https://github.com/Asmod4n/ruby-ffi-libsodium/blob/bd1e581e9ff1840eaa21ccaef76023da825ef6d5/lib/sodium.rb#L64.

**Comment by paddor** [comment]
+1

**Comment by tduehr** [comment]
These will be implemented by generic read/write type methods.

**Comment by tduehr** [comment]
See also #333
