### ISSUE TITLE
Calling a native function through a function pointer

### ISSUE THREAD

**Issue by bfoz** [ffi/ffi#404]
I'm working with an existing library that has methods that return pointers to structures full of pointers to functions. Using the documentation (thanks!) I've figured out how to model the pointers in the structures, but to do anything useful with the structures I need to be able to call the pointed-to-functions. So far, I haven't found the magic incantation in the docs, and my Google-fu is failing me.

I'm getting structs of the form...

```C
typedef struct
{
    int (*func1)(...);
    int (*func2)(...);
    ...
} function_table;

struct my_struct
{
    function_table* vt;
};
```

How do I call `func1`, `func2`, etc?

If calling function pointers isn't already implemented, I'd be willing to take a stab at it if someone would be kind enough to point me in the right direction.

**Comment by tduehr** [comment]
Are you looking to call that yourself or for the C library to call it?

Regardless of the use case there the underlying class for both the callbacks and functions is a pointer class.

Take a look at [Callbacks](https://github.com/ffi/ffi/wiki/Callbacks) and the [struct callback spec](https://github.com/ffi/ffi/blob/master/spec/ffi/struct_callback_spec.rb). All of those should respond to #call.

Here's the relevant spec:
```ruby
    module CallbackMember3
      extend FFI::Library
      ffi_lib TestLibrary::PATH
      class TestStruct < FFI::Struct
        layout \
          :add, callback([ :int, :int ], :int),
          :sub, callback([ :int, :int ], :int)
      end
      attach_function :struct_call_add_cb, [TestStruct, :int, :int], :int
      attach_function :struct_call_sub_cb, [TestStruct, :int, :int], :int
    end

    s = CallbackMember3::TestStruct.new
    add = Proc.new { |a,b| a+b}
    s[:add] = add
    fn = s[:add]
    expect(fn.respond_to?(:call)).to be true
    expect(fn.call(1, 2)).to eq(3)
```

The documentation for most of ffi needs a pretty good review.

**Comment by bfoz** [comment]
I need to call it from my code. The library appears to be using structures full of pointers to approximate virtual functions, but using only C. Calling various factory methods yields said structures, and I need to call the provided "virtual methods" from Ruby.

Using your example, I think I need something like...
```ruby
attach_function :factory_method, [], TestStruct

subclass = CallbackMember3.factory_method()
fn = subclass[:add]
fn.call(3,4)   # => call whatever method the pointer points to
```

**Comment by tduehr** [comment]
That looks about right. There should be no need to park the function in a variable: `subclass[:add].call(3,4)` should work unless you need a null guard of some sort.

**Comment by bfoz** [comment]
That did the trick, thanks.

The only remaining hangup came from using nested structures, which meant that I needed to use #ptr to reference the nested one...

```ruby
class FunctionTable < FFI::Struct
    layout :function1, callback(...) 
end

class MyStruct < FFI::Struct
    layout :vt, FunctionTable.ptr     # <= This is the part that I forgot
end

my_struct = factory_method()
my_struct[:vt][:function1].call(...)     # It works!
```

Thanks for your help.

Is there a good place to add this to the documentation? I might as well make sure that no one else gets hung up on this.

**Comment by tduehr** [comment]
I'd add it to the wiki. Possibly, to the `Struct` module's yardoc.

**Comment by bfoz** [comment]
Done and done.

**Comment by tduehr** [comment]
Thanks!
