### ISSUE TITLE
Windows Ruby 2.1 - FFI can't load DLLs

### ISSUE THREAD

**Issue by stakach** [ffi/ffi#410]
I've been trying to migrate a few clients off Ruby 1.9.3 to Ruby 2.1 on Windows using ruby installer with dev kit installed.

All the gems install and compile however FFI fails with a DLL not found error, however the path returned matches exactly the path of the DLL.

Exact same gems work on Windows Ruby 1.9.3 without change and the gems work on OSX and Linux with Ruby 2.1

**Comment by stakach** [comment]
![image](https://cloud.githubusercontent.com/assets/368013/6329691/ccf2f0f0-bbc6-11e4-88e6-38d4a6782967.png)

**Comment by tduehr** [comment]
for now, since you already have devkit installed, try forcing the platform to ruby `--platform=ruby`

**Comment by tduehr** [comment]
wait... Am I reading that right? Is it trying to load a dll with an absolute path?

If that's the case I'm pretty sure there's a bug that prevents that from working (anything other than auto-searched paths). I'm not sure why it works in 1.9.3 but not 2.1. The library loading logic currently assumes dlopen symantics (in this case RTLD constants) which aren't in any way correct or in use for windows. You can workaround it by directly loading DynamicLibraries and passing in the correct constants.

**Comment by stakach** [comment]
It was auto searched. The code that is trying to load there is:
https://github.com/cotag/ruby-tls/blob/master/lib/ruby-tls/ext.rb#L6

```ruby
require 'ffi'
require 'ffi-compiler/loader'

module RubyTls
    extend FFI::Library
    ffi_lib FFI::Compiler::Loader.find('ruby-tls-ext')

```

**Comment by stakach** [comment]
Or do you mean a path on `PATH` env var?

**Comment by tduehr** [comment]
`FFI::Compiler::Loader.find('ruby-tls-ext')` is returning the absolute path to the DLL. which isn't properly supported right now.

**Comment by stakach** [comment]
Turns out the DLL is consistently corrupt - however only when built using Ruby21...
Building with ruby 1.9 works every time. Different dev kits.

So not actually an FFI issue. The up shot is that absolute paths definitely do work with both ruby 2.1 and 1.9

**Comment by schneems** [comment]
So you can link an absolute path for a dll using ffi? I'm trying something like this:

```ruby
if RUBY_PLATFORM =~ /mswin|mingw/
  libsass_path = "#{gem_root}/ext/libsass/win/bin/libsass.dll"
else
  libsass_path = "#{gem_root}/ext/libsass/lib/libsass.so"
end
ffi_lib libsass_path
```

It kinda looks like it's working on my end but i'm getting a segfault when my tests run.

**Comment by stakach** [comment]
I would probably use something like `if FFI::Platform.windows?` instead of `RUBY_PLATFORM`

Have you attached any functions and calling into the library? As the segfault would probably only occur if you call into the library - if the function definition in Ruby is in anyway malformed or the manipulation of data is not just right then that can cause a segfault.

**Comment by schneems** [comment]
Good idea on the `FFI::Platform.windows?`

It segfaults when I call into the lib. Here's my current windows pet project https://ci.appveyor.com/project/schneems/sassc-ruby/build/17.

It works on mac and linux and i've never done any windows native compat work before. So i'm mostly shooting in the dark.

You can see the current segfault here: https://ci.appveyor.com/project/schneems/sassc-ruby/build/17/job/lsdrbpbpr4s4vf9k#L169

**Comment by stakach** [comment]
It should be exactly the same on windows as mac and linux.
One of the common problems I find is pre-compiled gems on windows - they only work on particular major revisions of ruby and usually only 32bit.

i.e. FFI on windows may only support: 1.9 and 2.1 etc on 32bit (I'm not actually sure)

So my guess would be one of the following:
* FFI or another gem you are relying on has a precompiled native extension (never problems loading DLLs)
* There is actually an error in your code that isn't apparent on other platforms

I once defined a struct incorrectly and it gave me incorrect values on linux and windows, segfault on mac. Took me ages to work out the issue.
