### ISSUE TITLE
#== raises "ArgumentError: Invalid Memory object", is this expected behavior?

### ISSUE THREAD

**Issue by jtzero** [ffi/ffi#411]
Title sums it up, using #== to compare a MemoryPointer to a non-ffi Object raises an error
<pre>irb(main):001:0> require 'ffi'
=> true
irb(main):002:0> m = FFI::MemoryPointer.new(:ulong)
=> #<FFI::MemoryPointer address=0x00000002f17fd0 size=4
irb(main):003:0> m == 1
ArgumentError: Invalid Memory object
        from (irb):3:in `=='
        from (irb):3
        from C:/Ruby200-x64/bin/irb:12:in `<main>'
irb(main):004:0> FFI::VERSION
 => "1.9.6"</pre>
is this expected behavior?

**Comment by tduehr** [comment]
Yes, `==` tries to cast the Fixnum as a Pointer, which is an invalid cast.

If you want to compare the pointer's address with a fixnum you need to use `1 == m.to_i`, if you want to compare with the value at the pointer `1 == m.get_ulong`
