### ISSUE TITLE
1.9.7 java (and windows) missing on rubygems.org

### ISSUE THREAD

**Issue by mprins** [ffi/ffi#416]
I may be premature in reporting this, but since I just ran into this while/after/during releasing a maven plugin that bundles some ruby libs... 
rubygems is missing the java (and windows) versions causing some grief, eg: jruby trying to  `make` native extensions while running the build.

see: https://ci.appveyor.com/project/mprins/sass-maven-plugin/build/191%20(appveyor-integration-tests)/job/l2lcyay12d7xj1r2#L120

see also #378 and #377

**Comment by tduehr** [comment]
1.9.7 contained an error anyway and was yanked. 1.9.8 now also has windows and java builds pushed to rubygems.

**Comment by mprins** [comment]
Thanks!
