### ISSUE TITLE
ffi_lib ignores .bundle libs

### ISSUE THREAD

**Issue by kirel** [ffi/ffi#42]
http://gist.github.com/367604

running

```
$ ruby extconf.rb
$ make
$ ruby issue.rb
```

results in
    /Users/daniel/.rvm/gems/ruby-1.9.1-p378/gems/ffi-0.6.3/lib/ffi/library.rb:61:in `block in ffi_lib': Could not open library 'issue': dlopen(issue, 5): image not found. Could not open library 'libissue.dylib': dlopen(libissue.dylib, 5): image not found (LoadError)
but it should probably just load the`issue.bundle`.
    ffi_lib ["issue.bundle", "issue"]
can be used as a workaround.

Produced on OSX 10.6 Ruby 1.9.1

**Comment by CAMOBAP** [comment]
@ghost I just wondering why not add this logic to `FFI.map_library_name`? Any cons?
