### ISSUE TITLE
Yanked 1.9.7 version causing dependency issues

### ISSUE THREAD

**Issue by cessien** [ffi/ffi#420]
The 1.9.7 version was yanked and its causing an issue for one of the gem packages I'm using. I'm not too sure if rubygems will update on its own or not so I'm creating this issue.

**Comment by miketheman** [comment]
Rubygems will _not_ update on its own if there's a Gemfile.lock that is locked to 1.9.7.
It appears the maintainers have released a 1.9.8 - running a `bundle update ffi` should solve this.

**Comment by miketheman** [comment]
See https://github.com/ffi/ffi/issues/416#issuecomment-81400327 for the maintainer's comment.

**Comment by cessien** [comment]
Perfect. Thanks!
