### ISSUE TITLE
Can not find ffi-1.9.7 in any of the sources

### ISSUE THREAD

**Issue by BrandonMathis** [ffi/ffi#422]
The 1.9.7 version of the ffi gem has been yanked.

Can you please shed some light on why this was done? It is generally considered bad practice to yank published versions of a gem :(

**Comment by tduehr** [comment]
it doesn't compile and neither the fat binary for windows or java versions of the gem were pushed..

**Comment by BrandonMathis** [comment]
Understood.

Some of my co-workers were getting errors trying to pull down that version of the gem. `bundle update ffi` fixed everything just fine.

**Comment by tduehr** [comment]
so they'd run bundle update originally when 1.9.7 had been yanked and 1.9.8 wasn't out yet? sounds like a bug in bundler. Thanks for the info, I'll keep it in mind next time I manage to break the gem.
