### ISSUE TITLE
symbol lookup error: undefined symbol: rb_str_new_static

### ISSUE THREAD

**Issue by waynehoover** [ffi/ffi#423]
I get this error, not when the gem compiles, but when running a sinatra app that requires ffi through another gem.

`ruby1.9.1: symbol lookup error: /home/pi/.gem/ruby/2.2.1/gems/ffi-1.9.8/lib/ffi_c.so: undefined symbol: rb_str_new_static`

Any ideas?

**Comment by tduehr** [comment]
This function is not used in FFI. Can you provide more context and a backtrace? What gem are you using?

**Comment by waynehoover** [comment]
The `typhoeus` gem requires `ethon` which requires `ffi`.

The interesting thing is that it used to be working, until I downgraded `ffi` for another reason. Then I started to get this error. So I ran `gem uninstall ffi` and re-installed `ffi` to the latest version and I still get this error. I'm getting this error on a raspberry pi btw, if that matters.

The above is the only backtrace I have, it compiles fine.

**Comment by tduehr** [comment]
This gem being what it is, platform is very important. Can you provide a stack trace from this error? I've seen these two gems come up with issues before but they've never really been resolved or repeatable.

Also, your prompt indicates ruby version 1.9.1 but the gem installation path 2.2.1.

**Comment by waynehoover** [comment]
I fixed this issue by deleting all my gems, and reinstalling them. Not sure why, but it worked.

**Comment by HaleTom** [comment]
I just had a similar issue, with but with `json`. It seems that the particular gem is irrelevant, but the fix is the same:

`gem uninstall -a <gemname>`
`bundle install`

**Comment by felbape** [comment]
I had to reinstall ffi, same fix
gem uninstall -a  ffi
bundle install
