### ISSUE TITLE
failed to load the ffi-yajl c-extension, falling back to ffi interface ---> ruby 2.2.1

### ISSUE THREAD

**Issue by ddpdevang** [ffi/ffi#426]
c:\Users\Devang\Desktop\RORBoxUsingChef>librarian-chef install
failed to load the ffi-yajl c-extension, falling back to ffi interface
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in require' : cannot load such file -- ffi_c (LoadError) from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54 :inrequire'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.8-x64-mingw32/lib/ff
i.rb:18:in rescue in <top (required)>' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.8-x64-mingw32/lib/ff i.rb:3:in'
from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54
:in require' from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54 :inrequire'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/
ffi.rb:4:in <top (required)>' from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54 :inrequire'
from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54
:in require' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl. rb:31:inrescue in '
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl.
rb:27:in <top (required)>' from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69 :inrequire'
from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69
:in require' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/chef-12.1.1/lib/chef/json_co mpat.rb:20:in'
from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69
:in require' from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69 :inrequire'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-chef-0.0.3/lib/lib
rarian/chef/manifest_reader.rb:27:in compile_manifest' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-chef-0.0.3/lib/lib rarian/chef/manifest_reader.rb:21:inread_manifest'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-chef-0.0.3/lib/lib
rarian/chef/source/local.rb:57:in fetch_manifest_data' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-chef-0.0.3/lib/lib rarian/chef/source/local.rb:49:inmanifest_data'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-chef-0.0.3/lib/lib
rarian/chef/source/local.rb:28:in fetch_version' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/manifest.rb:121:infetch_version!'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/manifest.rb:113:in fetched_version' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/manifest.rb:59:inversion'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/manifest.rb:97:in satisfies?' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/dependency.rb:121:insatisfied_by?'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:103:in block in check_manifest' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:104:ineach'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:104:in find' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:104:incheck_manifest'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:63:in block in recursive_resolve' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:154:inblock (3 levels) in resolving_dependency_ma
p_find_manifests'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:187:in block in scope_checking_manifest' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:223:inscope'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:186:in scope_checking_manifest' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:153:inblock (2 levels) in resolving_dependency_ma
p_find_manifests'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:211:in block in map_find' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:210:ineach'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:210:in map_find' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:152:inblock in resolving_dependency_map_find_mani
fests'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:165:in block (2 levels) in scope_resolving_depende ncy' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:179:inblock in scope_checking_manifests'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:223:in scope' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:178:inscope_checking_manifests'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:164:in block in scope_resolving_dependency' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:223:inscope'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:163:in scope_resolving_dependency' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:151:inresolving_dependency_map_find_manifests'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:62:in recursive_resolve' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:70:inblock in recursive_resolve'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:154:in block (3 levels) in resolving_dependency_ma p_find_manifests' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:187:inblock in scope_checking_manifest'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:223:in scope' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:186:inscope_checking_manifest'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:153:in block (2 levels) in resolving_dependency_ma p_find_manifests' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:211:inblock in map_find'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:210:in each' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:210:inmap_find'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:152:in block in resolving_dependency_map_find_mani fests' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:165:inblock (2 levels) in scope_resolving_depende
ncy'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:179:in block in scope_checking_manifests' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:223:inscope'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:178:in scope_checking_manifests' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:164:inblock in scope_resolving_dependency'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:223:in scope' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:163:inscope_resolving_dependency'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:151:in resolving_dependency_map_find_manifests' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver/implementation.rb:62:inrecursive_resolve'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/resolver/implementation.rb:50:in resolve' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/resolver.rb:23:inresolve'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/action/resolve.rb:26:in run' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/cli.rb:169:inresolve!'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-chef-0.0.3/lib/lib
rarian/chef/cli.rb:41:in install' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command .rb:27:inrun'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocat
ion.rb:126:in invoke_command' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359: indispatch'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb
:440:in start' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/cli.rb:26:inblock (2 levels) in bin!'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/cli.rb:31:in returning_status' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/cli.rb:26:inblock in bin!'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria
n/cli.rb:47:in with_environment' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/libraria n/cli.rb:26:inbin!'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/librarian-chef-0.0.3/bin/lib
rarian-chef:7:in <top (required)>' from C:/Ruby22-x64/bin/librarian-chef:23:inload'
from C:/Ruby22-x64/bin/librarian-chef:23:in `'

c:\Users\Devang\Desktop\RORBoxUsingChef>

**Comment by tduehr** [comment]
There's an error in the regexs that load the library file. see #421 for a workaround until the next release.
