### ISSUE TITLE
[BUG] Segmentation fault >= 1.9.3

### ISSUE THREAD

**Issue by igravious** [ffi/ffi#429]
I'm not going to paste the entire trace. RDF::Raptor 1.2.1 requires FFI >= 1.9.3 but that causes a segmentation fault. Pinning FFI to < 1.9.3 allows RDF::Raptor 1.0.1 to be used.

I'm not sure if the fault is with FFI or RDF::Raptor so I'm posting to both.

**Comment by tduehr** [comment]
Please supply the trace via a gist, and whatever code you can.

**Comment by igravious** [comment]
I posted a link to a gist in my comment in issue 21 of ruby-rdf/rdf-raptor: https://github.com/ruby-rdf/rdf-raptor/issues/21
I'll supply some code shortly.

**Comment by tduehr** [comment]
Error in rdf-raptor
