### ISSUE TITLE
Error compiling ffi in MaxOSX with Ruby 2.2.1

### ISSUE THREAD

**Issue by deivid-rodriguez** [ffi/ffi#430]
Here you can see the [error](https://travis-ci.org/deivid-rodriguez/byebug/jobs/56226843). Apparently the c99 flag is in use but the code is not compliant?

Thanks!!

**Comment by gugl** [comment]
Did someone already find a solution for that?

**Comment by tduehr** [comment]
I have no problems building locally on my mac.

**Comment by deivid-rodriguez** [comment]
I'm not installing _ffi_ in travis anymore, but I can't compile ffi locally using the `std=c99` flag.

**Comment by tduehr** [comment]
c99 is used on solaris 10 where it works fine currently. I'm not sure how or why you'd be using it on OSX.

**Comment by tduehr** [comment]
Bah.. just reread the error log here. I think you're using a substantially different version of xcode than what you compiled ruby with. I need the contents of gem_make.out to confirm.

http://stackoverflow.com/questions/23429145/error-failed-to-build-gem-native-extension-ruby-extconf-rb-mac-osx

**Comment by deivid-rodriguez** [comment]
The problem happens only in travis, I don't have an OSX machine myself. I
just tried to compile the gem using the c99 flag in my linux machine in
case the information that it fails as well could help.

In any case, this is not an issue for me anymore, as I'm not using ffi in
travis.

**Comment by tduehr** [comment]
I've started a run of our test suite:

https://travis-ci.org/ffi/ffi/builds/55107251

**Comment by tduehr** [comment]
It passed on every platform it's expected to pass on. Can you link a travis build that failed? The c99 messages are just warnings so that's not the problem anyway.

**Comment by deivid-rodriguez** [comment]
> It passed on every platform it's expected to pass on. Can you link a travis build that failed? 

I mean I was having the problem on my _own_ travis build that was failing when installing ffi. It's linked to in the first message.

> The c99 messages are just warnings so that's not the problem anyway.

I guess this is because of other flags you have enabled. In my case, that's not true by default.

    gcc --version
    # => gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
    echo "int main(int argc, char *argv[]) { for (int i=0; i < 10; i++); }" > test.c
    gcc test.c -o test
    # => test.c: In function ‘main’:
    # => test.c:1:36: error: ‘for’ loop initial declarations are only allowed in C99 mode
    # => int main(int argc, char *argv[]) { for (int i=0; i < 10; i++); }
    # =>                                                          ^
    # => test.c:1:36: note: use option -std=c99 or -std=gnu99 to compile your code
    gcc test.c -std=c99 -o test
    # => OK

**Comment by tduehr** [comment]
hrm....
```
make: /usr/local/bin/gmkdir: No such file or directory
```

Looks like the environment is missing something. I think you need to add `brew install coreutils` for the osx build there.

**Comment by deivid-rodriguez** [comment]
Aaaahm, nice catch, I totally missed that error. @gugl Does that help you?

@tduehr Thanks for your help!

**Comment by gugl** [comment]
Ah. Thanks for the hint and the fast responses. I'll try that when I come home.

**Comment by gugl** [comment]
working now. thanks. I still have a problem with the dep_selector gem. I'm not sure if it really was a ffi issue in the first place. anyway, ffi is working now. thanks.
