### ISSUE TITLE
can't find ffi_c with ruby 2.2.1 on Windows

### ISSUE THREAD

**Issue by topac** [ffi/ffi#432]
I saw that the folder lib/2.2 is not created (but the lib/2.1 folder is created) so the file 2.2/ffi_c is missing.

Windows server 2008 r2
Ruby 2.2.1p85 (2015-02-26 revision 49769) [i386-mingw32]

```

C:\test\test-db>gem install ffi
Fetching: ffi-1.9.8-x86-mingw32.gem (100%)
Successfully installed ffi-1.9.8-x86-mingw32
Parsing documentation for ffi-1.9.8-x86-mingw32
Installing ri documentation for ffi-1.9.8-x86-mingw32
Done installing documentation for ffi after 1 seconds
1 gem installed

C:\test\test-db>irb
irb(main):001:0> require 'ffi'
LoadError: cannot load such file -- ffi_c
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.9.8-x86-mingw32/lib/ffi.rb:18:in `rescue in <top (required)>'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.9.8-x86-mingw32/lib/ffi.rb:3:in `<top (required)>'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby/bin/irb:11:in `<main>'
```

**Comment by ccoenen** [comment]
Same problem here on Windows 8.1 and ruby 2.2.1p85.

The problem can be mitigated by using the RubyDevKit (available at rubyinstaller.com), uninstalling the prebuilt gem (-x86-mingw32) and then installing ffi like this:

    gem uninstall ffi
    gem install ffi --platform ruby
    # if you use bundler, edit your Gemfile.lock and remove the "mingw32" at the end of the gem, run bundle install afterwards so it pick up the "new" gem.
    # editing your Gemfile.lock by hand is probably not a good idea, but it may work as a short term fix

This will build a version tailored to your ruby.

It is not a long-term solution. The Long-Term solution seems to be releasing a new prebuilt gem with ruby 2.2 support.

**Comment by topac** [comment]
Ok, I think the problem is gone thanks to @abargnesi  with https://github.com/ffi/ffi/commit/4168ef3dbd56a7b52978efb2ff7d0dc448f8f8f1
Waiting for the release

**Comment by mvoto** [comment]
+1

**Comment by agongdai** [comment]
+1

**Comment by dcharan** [comment]
+1
