### ISSUE TITLE
Receive a float64 from a function call

### ISSUE THREAD

**Issue by chinshr** [ffi/ffi#434]
My C call [signature](http://www.speech.cs.cmu.edu/sphinx/doc/doxygen/sphinxbase/logmath_8h.html#6114206ec0321d7015c42fc7b81cb83e) looks like this:

```C
SPHINXBASE_EXPORT float64 	logmath_get_base (logmath_t *lmath)
```

On the FFI side I define as follows:

```ruby
typedef :pointer, :logmath
attach_function :logmath_get_base, [:logmath], FFI::NativeType::FLOAT64
```

Does this look correct?

**Comment by watsonbox** [comment]
In this case I think you can just use double:

https://github.com/cmusphinx/sphinxbase/blob/b0f33487bb3e75b9048f1010684a5c8da2bdf2db/include/sphinxbase/prim_type.h#L124
