### ISSUE TITLE
ERROR: Failed to build gem native extension - during Vagrant plugin installation on Win 7 64

### ISSUE THREAD

**Issue by garoke** [ffi/ffi#446]
Vagrant plugin installations no longer working after update to ffi 1.9.10

Here's the build and error output:
-----
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.10), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.10'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    C:/HashiCorp/Vagrant/embedded/bin/ruby.exe extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for rb_thread_blocking_region()... yes
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... no
creating extconf.h
creating Makefile

make "DESTDIR="
generating ffi_c-i386-mingw32.def
Configuring libffi
make -C "/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32"
make[1]: Entering directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32'
make "AR_FLAGS=" "CC_FOR_BUILD=" "CFLAGS=-Wall -fexceptions" "CXXFLAGS=" "CFLAGS_FOR_BUILD=" "CFLAGS_FOR_TARGET=" "INSTA
LL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=
/usr/bin/install -c" "JC1FLAGS=" "LDFLAGS=-LC:\HashiCorp\Vagrant\embedded\lib" "LIBCFLAGS=" "LIBCFLAGS_FOR_TARGET=" "MAK
E=make" "MAKEINFO=/bin/sh /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/missing --run makeinfo " "PICFLAG="
 "PICFLAG_FOR_TARGET=" "RUNTESTFLAGS=" "SHELL=/bin/sh" "exec_prefix=/usr/local" "infodir=/usr/local/share/info" "libdir=
/usr/local/lib" "mandir=/usr/local/share/man" "prefix=/usr/local" "AR=ar" "AS=as" "CC=gcc" "CXX=g++" "LD=c:/hashicorp/va
grant/embedded/mingw/i686-w64-mingw32/bin/ld.exe" "NM=/usr/mingw/bin/nm" "RANLIB=ranlib" "DESTDIR=" all-recursive
make[2]: Entering directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32'
Making all in include
make[3]: Entering directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32/include'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32/include'
Making all in testsuite
make[3]: Entering directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32/testsuite'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32/testsuite'
Making all in man
make[3]: Entering directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32/man'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32/man'
make[3]: Entering directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32'
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_
c/libffi  -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems
/gems/ffi-1.9.10/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFF
SET_BITS=64  -g  -Wall -fexceptions -c -o src/debug.lo /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/de
bug.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi -I. -I/c/hashico
rp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c
/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFFSET_BITS=64 -g -Wall -fexc
eptions -c /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/debug.c  -DDLL_EXPORT -DPIC -o src/.libs/debug
.o
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_
c/libffi  -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems
/gems/ffi-1.9.10/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFF
SET_BITS=64  -g  -Wall -fexceptions -c -o src/prep_cif.lo /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src
/prep_cif.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi -I. -I/c/hashico
rp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c
/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFFSET_BITS=64 -g -Wall -fexc
eptions -c /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/prep_cif.c  -DDLL_EXPORT -DPIC -o src/.libs/pr
ep_cif.o
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_
c/libffi  -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems
/gems/ffi-1.9.10/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFF
SET_BITS=64  -g  -Wall -fexceptions -c -o src/types.lo /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/ty
pes.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi -I. -I/c/hashico
rp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c
/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFFSET_BITS=64 -g -Wall -fexc
eptions -c /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/types.c  -DDLL_EXPORT -DPIC -o src/.libs/types
.o
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_
c/libffi  -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems
/gems/ffi-1.9.10/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFF
SET_BITS=64  -g  -Wall -fexceptions -c -o src/raw_api.lo /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/
raw_api.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi -I. -I/c/hashico
rp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c
/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFFSET_BITS=64 -g -Wall -fexc
eptions -c /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/raw_api.c  -DDLL_EXPORT -DPIC -o src/.libs/raw
_api.o
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_
c/libffi  -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems
/gems/ffi-1.9.10/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFF
SET_BITS=64  -g  -Wall -fexceptions -c -o src/java_raw_api.lo /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi
/src/java_raw_api.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi -I. -I/c/hashico
rp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c
/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFFSET_BITS=64 -g -Wall -fexc
eptions -c /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/java_raw_api.c  -DDLL_EXPORT -DPIC -o src/.lib
s/java_raw_api.o
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_
c/libffi  -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems
/gems/ffi-1.9.10/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFF
SET_BITS=64  -g  -Wall -fexceptions -c -o src/closures.lo /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src
/closures.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi -I. -I/c/hashico
rp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c
/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFFSET_BITS=64 -g -Wall -fexc
eptions -c /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/closures.c  -DDLL_EXPORT -DPIC -o src/.libs/cl
osures.o
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_
c/libffi  -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems
/gems/ffi-1.9.10/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFF
SET_BITS=64  -g  -Wall -fexceptions -c -o src/x86/ffi.lo /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/
x86/ffi.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi -I. -I/c/hashico
rp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c
/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFFSET_BITS=64 -g -Wall -fexc
eptions -c /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/ffi.c  -DDLL_EXPORT -DPIC -o src/x86/.libs
/ffi.o
/bin/sh ./libtool   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi
 -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/ffi
-1.9.10/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFFSET_BITS=
64  -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/
ffi-1.9.10/ext/ffi_c/libffi/src  -c -o src/x86/win32.lo /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x
86/win32.S
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi -I. -I/c/hashico
rp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c
/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFFSET_BITS=64 -I. -I/c/hashi
corp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/include -Iinclude -I/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi
_c/libffi/src -c /c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/win32.S  -DDLL_EXPORT -DPIC -o src/x
86/.libs/win32.o
/bin/sh ./libtool --tag=CC   --mode=link gcc -g  -Wall -fexceptions -version-info `grep -v '^#' /c/hashicorp/Vagrant/gem
s/gems/ffi-1.9.10/ext/ffi_c/libffi/libtool-version`  -no-undefined -bindir "/usr/local/bin" -LC:\HashiCorp\Vagrant\embed
ded\lib -o libffi.la -rpath /usr/local/lib src/debug.lo src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo
src/closures.lo    src/x86/ffi.lo src/x86/win32.lo
./libtool: line 5988: cd: **C:HashiCorpVagrantembeddedlib**: No such file or directory
libtool: link: cannot determine absolute directory name of `C:HashiCorpVagrantembeddedlib'
make[3]: *** [libffi.la] Error 1
make[3]: Leaving directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32'
make: *** ["/c/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/libffi-i386-mingw32"/.libs/libffi_convenience.a] Error 2

Gem files will remain installed in c:/hashicorp/Vagrant/gems/gems/ffi-1.9.10 for inspection.
Results logged to c:/hashicorp/Vagrant/gems/gems/ffi-1.9.10/ext/ffi_c/gem_make.out
-----

The path error "No such file or directory" looks like backslashes are not being escaped in windows path for part of the build? The path C:\HashiCorp\Vagrant\embedded\lib does exist.

Thanks,
Gary.

**Comment by nsteffan** [comment]
@tduehr it looks like the windows version hasn't been pushed to RubyGems, could you please do that?

**Comment by etehtsea** [comment]
@nsteffan @tduehr same for java version. Thank you.

**Comment by larskanis** [comment]
I pushed the x86, x64 and java versions to rubygems.org. This hopefully fixes your issue.

**Comment by garoke** [comment]
@larskanis Yes thanks - that fixed it. Appreciated.

**Comment by vhosakot** [comment]
I saw the error `Failed to build gem native extension` too on CentOS 7.3 and vagrant 1.8.7.

I resolved it after installing ruby-devel and gcc (`yum -y install ruby-devel gcc`)
