### ISSUE TITLE
how to wrap functions which return FILE* ?

### ISSUE THREAD

**Issue by felipebalbi** [ffi/ffi#453]
I'm considering wrapping librsync with FFI, but rs_file_open, returns a FILE *. I wonder if I should just use a :pointer return type or is there something that would make it usable with Ruby's File class ?

**Comment by larskanis** [comment]
On UNIX systems this can be done like this:
``` ruby
require "ffi"
module Stdio
  extend FFI::Library
  ffi_lib FFI::Platform::LIBC
  attach_function :fopen, [ :string, :string ], :pointer
  attach_function :fileno, [ :pointer ], :int
  attach_function :fclose, [ :pointer ], :int
end

filep = Stdio.fopen("testfile", "w")
fd = Stdio.fileno(filep)
io = IO.for_fd(fd, autoclose: false)
io.puts "hello file by ffi"
io.flush
Stdio.fclose(filep)
```

On Windows you additionally need to wrap and unwrap `fd` by rb_w32_wrap_io_handle() and rb_w32_unwrap_io_handle() like [here in the pg.gem](https://github.com/larskanis/ruby-pg/blob/master/ext/pg_connection.c#L838) .

**Comment by tduehr** [comment]
@larskanis is correct.

I would caution against automatically turning that specific pointer into a Ruby IO object unless you have a specific need for it (like implementing some of rsync's logic in Ruby). While I'm not familiar with the exact use of file pointers in librsync, this is an area that tends to cause problems for many users unless they know they want to specifically access that pointer. If you need to expose the rsync stream as a Ruby object I would wrap it in a subclass of IO for user access.
