### ISSUE TITLE
Problem with ulong_long

### ISSUE THREAD

**Issue by kimtn-bitmark** [ffi/ffi#454]
I have 64-bit unsigned integer as a input param in my C function. I try to define wrap interface as bellow

```
var libencrypt = ffi.Library('./mylib', {
  'myfunction': ['void', ['ulong_long']],
})
```

I got this error when i trying to run test
```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: could not determine a proper "type" from: "ulong_long"
```

does it have mean sense with you?

**Comment by tduehr** [comment]
this is for the Ruby gem FFI. I looks like you're looking for the node.js FFI module.

Anyway, that error likely means the ulong_long type has not been defined.

**Comment by kimtn-bitmark** [comment]
Thanks for your answer @tduehr . I'll post it on node-ffi repo.
