### ISSUE TITLE
Could not find ffi in any of the sources

### ISSUE THREAD

**Issue by micahalcorn** [ffi/ffi#456]
On OS X 10.9.5...

**Gemfile**
```Ruby
source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sass-rails', '5.0.4'
gem 'uglifier', '2.7.2'
gem 'coffee-rails', '4.1.0'
gem 'jquery-rails', '4.0.5'
gem 'turbolinks', '2.5.3'
gem 'jbuilder', '2.3.1'
gem 'sdoc', '0.4.1', group: :doc
gem 'mongoid', '4.0.2'
gem 'mongoid-grid_fs', '2.1.0'
gem 'watir-rails', '1.1.0'

group :development, :test do
  gem 'byebug', '6.0.2'
  gem 'web-console', '2.2.1'
  gem 'spring', '1.3.6'
end
```
**Terminal**
```Bash
$ bundle install
...
Installing ffi 1.9.10 with native extensions
...
Bundle complete! 14 Gemfile dependencies, 68 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ bundle show ffi
/Users/me/.rvm/gems/ruby-2.2.2/gems/ffi-1.9.10
$ rails c
Could not find ffi-1.9.10 in any of the sources
Run `bundle install` to install missing gems
```
I tried placing "gem 'ffi', '1.9.10'" in my Gemfile.

I tried removing my Gemfile.lock and repeating this process.

I tried `bundle exec rails c`.

I tried `gem install ffi --version 1.0.11`, which seems to be the dependency for childprocess-0.5.6.

None of these attempts make any difference. What am I missing?

**Comment by micahalcorn** [comment]
I would still like to know how to resolve this, but I built a new app with all of the same code and it works fine. I will close, but please let me know if you have an idea what might cause this, thanks.

**Comment by calliday** [comment]
I am having this same issue. Any ideas?
