### ISSUE TITLE
ffi_lib :shell32 -> Could not open library 'cygshell32.dll': No such file or directory

### ISSUE THREAD

**Issue by tobiashochguertel** [ffi/ffi#459]
I try to get Puppet running with cygwin.

**System Information:**

```
Windows 10 Pro
64-Bit
```

```
0 hochguertelto@workstation-win:/cygdrive/x
$ uname -a
CYGWIN_NT-10.0 workstation-win 2.2.1(0.289/5/3) 2015-08-20 11:42 x86_64 Cygwin
```

```
0 hochguertelto@workstation-win:/cygdrive/x
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-cygwin]
```

**Error:**

```
1 hochguertelto@workstation-win:/cygdrive/x
$ puppet
no implicit conversion of Symbol into String.
Could not open library 'cygshlwapi.dll': No such file or directory

1 hochguertelto@workstation-win:/cygdrive/x
$ puppet
no implicit conversion of Symbol into String.
Could not open library 'cygshell32.dll': No such file or directory
```

**Workaround:**

I made a change in my installed ffi library to get ffi / puppet to this point with cygwin and gem installed puppet:

[Line:101:File: `ffi-1.9.10/lib/ffi/platform.rb` at FFI project at Github](https://github.com/ffi/ffi/blob/master/lib/ffi/platform.rb#L101)

**Before:**
**File: `ffi-1.9.10/lib/ffi/platform.rb`**
```
    LIBPREFIX = case OS
    when /windows/
      ''
    when /cygwin/
      'cyg'
    else
      'lib'
    end

    LIBSUFFIX = case OS
    when /darwin/
      'dylib'
    when /linux|bsd|solaris/
      'so'
    when /windows|cygwin/
      'dll'
    else
      # Punt and just assume a sane unix (i.e. anything but AIX)
      'so'
    end
```

**After:**
**File: `ffi-1.9.10/lib/ffi/platform.rb`**
```
    LIBPREFIX = case OS
    when /windows/
      ''
    when /cygwin/
      ''
    else
      'lib'
    end

    LIBSUFFIX = case OS
    when /darwin/
      'dylib'
    when /linux|bsd|solaris/
      'so'
    when /windows|cygwin/
      'dll'
    else
      # Punt and just assume a sane unix (i.e. anything but AIX)
      'so'
    end
```

**Comment by tobiashochguertel** [comment]
For an introduction for the behavior without 'cyg' prefix please have a look at my [issue 7](https://github.com/djberg96/win32-security/issues/7#issuecomment-140613912) at win32-security.

**Comment by tduehr** [comment]
I think it may be a better idea for FFI to search for both the prefixed and unprefixed libraries.

**Comment by tobiashochguertel** [comment]
I've got closer and learned that FFI can done this already. I written an new comment to [win32-security/issues/7#issuecomment-140762826](https://github.com/djberg96/win32-security/issues/7#issuecomment-140762826) where I written about the way to load native windows libraries.... after I leared how FFI does this.

> I came up with the idea that FFI is correct and has some more magic to load the correct libary. I came up with the following mailinglist entry [[LuaJIT] ffi.load on Cygwin](http://lua-users.org/lists/lua-l/2012-03/msg00505.html) and found the [FFI Wiki page with Windows-Examples](https://github.com/ffi/ffi/wiki/Windows-Examples) 

> I read the example code and saw that they load the windows library `kernel32` via an String value which is passed to `ffi_lib`-method of `FFI:Library`. I was interrested and tried out these examples. They work, no error messages about missing libraries like `cygkernel32.dll`. I have packged these examples into an github repository [showcase-windows-libaries-with-ffi-cygwin](https://github.com/tobiashochguertel/showcase-windows-libaries-with-ffi-cygwin) .

```
git clone git@github.com:tobiashochguertel/showcase-windows-libaries-with-ffi-cygwin.git
cd showcase-windows-libaries-with-ffi-cygwin
./run.sh
```

*Log:*
```
0 hochguertelto@workstation-win:/cygdrive/x/ffi-tests/showcase-windows-libaries-with-ffi-cygwin
$ ./run.sh
Date: 9/16/2015
Time: 20:22:57
```

**Comment by tduehr** [comment]
Can this be closed then?

**Comment by tobiashochguertel** [comment]
Yes, FFI can handle [loading Native Windows Libraries](https://github.com/ffi/ffi/wiki/Windows-Examples).
