### ISSUE TITLE
Structs - Opaque Data Types

### ISSUE THREAD

**Issue by hwhelchel** [ffi/ffi#462]
Is there a way to represent opaque data types in FFI?

https://en.wikipedia.org/wiki/Opaque_data_type

I'm working on bindings for libgraphqlparser which declares a Struct without any members: https://github.com/graphql/libgraphqlparser/blob/18a9c675c24ea2cf0cb8e524b5ecd5adb25700bb/c/GraphQLAstNode.h#L17

Thanks for your help!

**Comment by tduehr** [comment]
You should be able to just use a pointer.
