### ISSUE TITLE
Jruby always rice warning about gem dependencies

### ISSUE THREAD

**Issue by pironim** [ffi/ffi#463]
This happens only with specific JRuby version.
Here is warning:
$ bundle install
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Using ffi 1.9.10
Using bundler 1.10.6
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

I create repo with code to reproduce this problem https://github.com/pironim/PryAndJrubyIssue

git clone git@github.com:pironim/PryAndJrubyIssue.git
rbenv install jruby-1.7.16.1
cd PryAndJrubyIssue
gem install bundler
bundle install
and again type bundle install

Here is screenshot http://screencloud.net/v/zISi

**Comment by pironim** [comment]
I recheck this issue on other computer opensuse + rvm and it still there.
previous comment was created on ubuntu + rbenv.

**Comment by pironim** [comment]
I can't reproduce it on jruby-1.7.22 . and looks like it's version specific

**Comment by tduehr** [comment]
This repository is for the MRI version of ffi. Please file an issue with JRuby for future issues with that version so we can more easily track problems.

That said, FFI is part of JRuby. There should be no need to install it other than to clear up dependency issues when rubygems or bundler decide to be difficult. It's just an empty gem for jruby.
