### ISSUE TITLE
Can't install FFI

### ISSUE THREAD

**Issue by feskyde** [ffi/ffi#465]
I can't install FFI (a Jekyll dependency) using `gem`:

![](https://github.com/feskyde/feskyde.github.io/raw/master/images/reviews/SolusRC1/5.png)

**Comment by larskanis** [comment]
FFI requires Ruby development files to be installed. The package name is
typically ruby-dev or similar.

**Comment by feskyde** [comment]
I forgot this, surely I'm not on Arch

Thanks! :smile:
