### ISSUE TITLE
Extract platform sensing code into a gem

### ISSUE THREAD

**Issue by paddor** [ffi/ffi#471]
I'm thinking about writing a compatibility layer / drop-in replacement for FFI, so it'll use [Fiddle](http://ruby-doc.org/stdlib-2.2.3/libdoc/fiddle/rdoc/Fiddle.html) under the hood.

Unfortunately, I think there aren't any better ways to, e.g. determine the platform's library suffix and stuff like that, than how it's done in this project.

Could you open up the opportunities for developers like me by extracting that valuable functionality? Namely:

* `ext/ffi_c/Platform.h`
* `ext/ffi_c/Platform.c`
* `ffi/lib/ffi/platform.rb`
* possibly the files in `ffi/lib/ffi/platform/`

IMHO, it'd make a lot of sense to put this code into a gem called something like `ffi-platform`. I think many people could profit from it.

(This gem called ['Platform'](https://rubygems.org/gems/Platform) hasn't been updated for 10 years.)

**Comment by larskanis** [comment]
FFI has a much more comprehensive and extendable type system than Fiddle and it has many features that Fiddle lacks. So Fiddle is kind of "FFI-light" . It will be hard to implement everything on Fiddle that FFI supports.

JRuby implements FFI as a native interface. And it supports [Fiddle on top of FFI](https://github.com/jruby/jruby/blob/master/lib/ruby/stdlib/fiddle/jruby.rb) . So your gem is exactly the other way around.

However I see only limited use of such a FFI-to-Fiddle wrapper, given that it will decrease the speed of calls to C code even more. And I don't think it is valuable to split out platform specific code to another gem, given that it includes both Ruby code _and_ C code.

**Comment by simi** [comment]
@paddor *fun fact: actually it is exactly 10 years (since the last version of Platform was released) today.* :trollface:

**Comment by paddor** [comment]
@larskanis I see. Didn't know that about JRuby. And since this project isn't dead, this issue is invalid anyway.

@simi Huh, unbelievable. :open_mouth:
