### ISSUE TITLE
providing negative integer to :uintX type should raise RangeError

### ISSUE THREAD

**Issue by paddor** [ffi/ffi#473]
FFI nicely raises a RangeError when I provide, e.g. the number 23456765432345654 as a `:uint32` parameter. But it doesn't raise RangeError when providing a negative number.

**Comment by tduehr** [comment]
Supplying a negative number for a uint argument is valid in C and a common method of creating large values to indicate error conditions. `23456765432345654` is a 55 bit number and won't fit in a 32 bit int. The behavior of this in C is the left most 23 bits would be truncated. If anything, this could be considered a bug in the code handling overly large number.

**Comment by paddor** [comment]
In that case, I guess FFI should not step in the way of this C "feature".
