### ISSUE TITLE
New wiki entry for proc address loading

### ISSUE THREAD

**Issue by npomf** [ffi/ffi#486]
This is part of an experimental feature I'm developing for expanding on FFI and using OpenGL.  I have not be able to fully test this on Windows 7+ (and have no means to do so on Mac OS X), but it _appears_ to be playing nicely using Linux.

Once further testing is performed and the feature confirmed to operate as intended, I'll create a new Wiki page unless another contributor wishes to do so.

**Update**:  as best I can tell, it appears to be working, though I will need to perform additional testing to be certain.  The proposal text is being updated with some additional notes.

The proposed page contents are quoted below:

> Some libraries, such as OpenGL, do not provide all of their function pointers within the API itself.  This requires the use of a platform-specific function loader to return the procedure address of a function, by its name.  To do so, we'll first need to override part of `FFI::Library`.
> ## Enable fail-over
> 
> ``` ruby
>     # Override the default behavior to permit proc address loading.
>     def attach_function( name, func, args, returns = nil, options = nil )
>         begin
>             super
>         rescue Exception, FFI::NotFoundError
>             unless procaddr( name, func, args, returns, options )
>                 warn "#{name || func} was not found in [#{ffi_libraries.map {|lib| lib.name }.join(', ')}]"
>             end
>         end
>     end
>     module_function :attach_function
> ```
> 
> In the above code, we capture any exception or instance of `FFI::NotFoundError` and send the same arguments to our `procaddr()` function.
> ## Performing Function Loading
> 
> There are a few caveats here, which will be covered before we get into the code itself.
> ### Caveat 1.:  Function loaders are platform-dependent
> 
> The function used to obtain a procedure address is dependent on the current platform.  The implementation below relies on `@@procfunc`, a class-variable which contains the symbolic name of the loading function.  This will need to be declared before calling `attach_function()`.
> ### Caveat 2.:  You must wrap this function to use it
> 
> As you'll find in the source code provided below, we first need to find the Symbol representing the loader function before we can use it.  Once that's done, we wrap it into an actual `FFI::Function` which allows us to call into the method.
> ### The loading routine
> 
> You may notice that the routine shown below is markedly similar to the original `attach_function()` implementation; this is due to it being necessary to replicate the operations taken to derive the data used by FFI for binding and identifying functions between the various methods of invocation.
> 
> If the attempt to locate `@@procfunc` fails, a LoadError will be raised.
> 
> ``` ruby
>     # Perform proc address loading.
>     def self.procaddr( name, func, args, returns, options = {} )
>         # Here we replicate the operations performed by FFI::Libary; this is necessary for later when we bind the
>         # "real" function as an invoker.
>         sym = returns and func.is_a? String or func.is_a? Symbol
>         cname, arg_types, ret_type, opts = sym ? [ func, args, returns, options ] : [ name.to_s, func, args, returns ]
>         arg_types.map! {|t| find_type( t ) }
>         defaults = {
>             convention: ffi_convention,
>             type_map: @ffi_typedefs,
>             blocking: (@blocking and not @blocking.nil?),
>             enums: @ffi_enums
>         }
>         opts = defaults.merge( opts )
> 
>         # In this section, we'll look up the proc address loading function based upon the name provided by our
>         # current platform and bind it to a FFI::Function instance.
>         if @@procaddr.nil?
>             ffi_libraries.each {|lib|
>                 function_names( @@procfunc, [ FFI::NativeType::POINTER ] ).find {|fname|
>                     @@procaddr = FFI::Function.new(
>                         FFI::NativeType::POINTER,
>                         [ FFI::NativeType::POINTER ],
>                         lib.find_function( fname ),
>                         defaults
>                     )
>                 }
>             }
>             raise LoadError unless @@procaddr
>         end
> 
>         # Using our procaddr function, we invoke it against the name of the desired function and retrieve
>         # the pointer to its address.  This same pointer is then used to bind the Invoker or Function that
>         # will be used to attach it to the Library.
>         function = @@procaddr.call( cname )
>         invoker = if arg_types.length > 0 and arg_types[ -1 ].eql? FFI::NativeType::VARARGS
>             FFI::VariadicInvoker.new( function, arg_types, find_type( ret_type ), opts )
>         else
>             FFI::Function.new( find_type( ret_type ), arg_types, function, opts )
>         end
>         return unless invoker   # abort if not supported
> 
>         # The more familiar part of attach_function continues here, in which we attach the invoker to the
>         # library and then return it.
>         invoker.attach( self, cname.to_s )
>         invoker
>     end
> ```
> 
> Please be aware that the implementation is _permissive_ in loading and will silently abort if the proc address was not resolved.  While this may be useful for libraries where different local version may not be able to load all entry points specified in the FFI wrapper, it might not be desired where full compliance is necessary.
> 
> We capture this in the updated `attach_function()` call, which will print a warning whenever `procaddr()` returns a falsey value.

**Comment by larskanis** [comment]
My answer is probably not the one you asked for, but I would like to suggest the [ruby-opengl-gem](https://github.com/larskanis/opengl) in order to use OpenGL. This does exactly the loading mechanism you built with FFI and provides a lot of properly wrapped functions. With version 0.10.0 (yet unreleased) the loading mechanism is more dynamic, to allow alternative OpenGL implementations like [Osmesa](https://github.com/larskanis/osmesa).

Is there a particular reason you're not using the opengl gem?

**Comment by npomf** [comment]
While not quite what I had intended with the wiki page proposal, I'll answer your question, @larskanis:  the gem did not cover GL 4.x compatibility, which was a requirement.  Rolling my own wrapper on top of the standard opengl libraries also avoided needing to handle C-exts which helps provide usability in JRuby, as well as a dependency on source files.

**Comment by larskanis** [comment]
OK. Did you have a look at the various existing OpenGL implementations? Especially this ffi-based one: https://github.com/davll/ruby-opengl

These two are based on fiddle (a lightweight ffi alternative), but maybe interesting anyway:
https://github.com/vaiorabbit/ruby-opengl
https://github.com/nilium/opengl-core

**Comment by mvz** [comment]
My 2 cents:

If you already know which functions need this dynamic loading, you can create a separate function for this rather than overriding `attach_function`. This will also allow you to not support all variations of `attach_function`'s argument list if they're not necessary.

Once that's done, you can inject the function that finds the dynamic implementation as a parameter, which would clean up the code a lot I think.

Alternatively, you could override `Library#find_function` so the rest of `attach_function` still works.

If this is an open source project, it's probably easier to reason about the actual code than to (eventually) edit the Wiki or discuss an example in a GitHub ticket.
