### ISSUE TITLE
Arrays of bool are the wrong size in a struct

### ISSUE THREAD

**Issue by stugol** [ffi/ffi#487]
The following code creates a structure of 1024 bytes, not 1024 bits as expected:
```
class SIGSET_T < FFI::Struct
	layout 	:bits, [:bool, 1024]			# 1024 signals
end
```
If this is intended behaviour (why!?) then we need a `:bit` type to put there instead.

**Comment by tduehr** [comment]
This is part of the C standard, if you need a bitfield of a given size, that's normally created using an array of an unsigned integer type.

**Comment by stugol** [comment]
I'm sorry? Ruby != C.

I find your attitude unhelpful.
