### ISSUE TITLE
Fail on Windows Ruby 2.3 

### ISSUE THREAD

**Issue by ukoloff** [ffi/ffi#500]
Gem ffi is installed normally but when using it it dies. Eg https://ci.appveyor.com/project/ukoloff/openssl-win-root/build/1.0.18-master/job/436l6jdue50s5h2y

In `gems\ffi-1.9.10-x86-mingw32\lib`  I can see folders 1.8, 1.9, 2.0, 2.1, 2.2 and ffi. No 2.3 folder, may be it's the reason.

**Comment by tduehr** [comment]
Yup, we haven't packaged for 2.3 on windows yet... s/b soon.

**Comment by freaz** [comment]
Is there any ETA when this will be resolved? Thanks

**Comment by P3t3rU5** [comment]
As a temporary workaround:

1. Install the gem.
2. Open command prompt (Win + r) and go to the gem directory 
ruby\gems\2.3.0\gems\ffi-1.9.10-x86-mingw32\ext\ffi_c
3. Add devkit folder to path
4. ruby extconf.rb
5. make (it takes a while)
6, after compilation copy to a new dir ruby\gems\2.3.0\gems\ffi-1.9.10-x86-mingw32\lib\2.3

credits to @SilverPhoenix99

**Comment by micapam** [comment]
In case anyone is confused by step 3 above, 'add devkit folder to path' is not simply adding the ruby dev kit 'bin' folder to the path - you have to run the 'devkitvars.bat' file (supplied with ruby dev kit).

**Comment by larskanis** [comment]
You should be able to install the source ffi gem on Ruby-2.3 like this:
```
gem inst ffi --platform ruby
```
RubyInstaller-2.3 will be supported starting with version 1.9.11 of the binary ffi gem.

**Comment by tduehr** [comment]
This should be fixed in 1.9.14.
