### ISSUE TITLE
Fail to install on Windows 7 Ruby 2.2

### ISSUE THREAD

**Issue by baumannchristian** [ffi/ffi#502]
I´m trying to install ffi on Windows 7, Ruby 2.2.4p230, RubyDevKit mingw64-32-4.7.2 via `gem install ffi`

I get this

`Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
        ERROR: Failed to build gem native extension.

    C:/Ruby/bin/ruby.exe -r ./siteconf20160511-4072-1ct0n0a.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include... no
checking for rb_thread_blocking_region()... no
checking for ruby_native_thread_p()... yes
checking for rb_thread_call_with_gvl()... yes
creating extconf.h
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating ffi_c-i386-mingw32.def
Configuring libffi
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
rm: cannot lstat `conftest.exe': Permission denied
make -C "/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi"
make[1]: Entering directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi'
make "AR_FLAGS=" "CC_FOR_BUILD=" "CFLAGS=" "CXXFLAGS=" "CFLAGS_FOR_BUILD=" "CFLAGS_FOR_TARGET=" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "JC1FLAGS=" "LDFLAGS=" "LIBCFLAGS=" "LIBCFLAGS_FOR_TARGET=" "MAKE=make" "MAKEINFO=/bin/sh /c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi/missing --run makeinfo " "PICFLAG=" "PICFLAG_FOR_TARGET=" "RUNTESTFLAGS=" "SHELL=/bin/sh" "exec_prefix=/usr/local" "infodir=/usr/local/share/info" "libdir=/usr/local/lib" "prefix=/usr/local" "AR=ar" "AS=as" "CC=gcc" "CXX=g++" "LD=c:/rubydevkit/mingw/i686-w64-mingw32/bin/ld.exe" "NM=/usr/mingw/bin/nm" "RANLIB=ranlib" "DESTDIR=" all-recursive
make[2]: Entering directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi'
Making all in include
make[3]: Entering directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi/include'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi/include'
Making all in testsuite
make[3]: Entering directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi/testsuite'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi/testsuite'
Making all in man
make[3]: Entering directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi/man'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi/man'
make[3]: Entering directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi'
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/debug.lo src/debug.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/debug.c  -DDLL_EXPORT -DPIC -o src/.libs/debug.o
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/prep_cif.lo src/prep_cif.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/prep_cif.c  -DDLL_EXPORT -DPIC -o src/.libs/prep_cif.o

/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/types.lo src/types.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/types.c  -DDLL_EXPORT -DPIC -o src/.libs/types.o
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/raw_api.lo src/raw_api.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/raw_api.c  -DDLL_EXPORT -DPIC -o src/.libs/raw_api.o
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/java_raw_api.lo src/java_raw_api.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/java_raw_api.c  -DDLL_EXPORT -DPIC -o src/.libs/java_raw_api.o
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/closures.lo src/closures.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/closures.c  -DDLL_EXPORT -DPIC -o src/.libs/closures.o

/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/x86/ffi.lo src/x86/ffi.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/x86/ffi.c  -DDLL_EXPORT -DPIC -o src/x86/.libs/ffi.o
/bin/sh ./libtool   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -I. -I./include -Iinclude -I./src  -c -o src/x86/win32.lo src/x86
/win32.S
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -I. -I./include -Iinclude -I./src -c src/x86/win32.S  -DDLL_EXPORT -DPIC -o src/x86
/.libs/win32.o
/bin/sh ./libtool --tag=CC   --mode=link gcc -Wall -g -fexceptions  -version-info `grep -v '^#' ./libtool-version` -no-undefined  -o libffi.la -rpath /usr/local
/lib src/debug.lo src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo    src/x86/ffi.lo src/x86/win32.lo
libtool: link: gcc -shared  src/.libs/debug.o src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.
libs/ffi.o src/x86/.libs/win32.o      -o .libs/libffi-5.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libffi.dll.a
libtool: link: ( cd ".libs" && rm -f "libffi.la" && cp -p "../libffi.la" "libffi.la" )
/bin/sh ./libtool --tag=CC   --mode=link gcc -Wall -g -fexceptions    -o libffi_convenience.la  src/debug.lo src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo    src/x86/ffi.lo src/x86/win32.lo
libtool: link: ar cru .libs/libffi_convenience.a src/.libs/debug.o src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi.o src/x86/.libs/win32.o
libtool: link: ranlib .libs/libffi_convenience.a
libtool: link: ( cd ".libs" && rm -f "libffi_convenience.la" && cp -p "../libffi_convenience.la" "libffi_convenience.la" )
make[3]: Leaving directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi'
make[2]: Leaving directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi'
make[1]: Leaving directory `/c/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11/ext/ffi_c/libffi'
compiling AbstractMemory.c
AbstractMemory.c:271:1: warning: 'memory_put_bool' defined but not used [-Wunused-function]
AbstractMemory.c:271:1: warning: 'memory_write_bool' defined but not used [-Wunused-function]
AbstractMemory.c:271:1: warning: 'memory_get_bool' defined but not used [-Wunused-function]
AbstractMemory.c:271:1: warning: 'memory_read_bool' defined but not used [-Wunused-function]
AbstractMemory.c:271:1: warning: 'memory_write_array_of_bool' defined but not used [-Wunused-function]
AbstractMemory.c:271:1: warning: 'memory_read_array_of_bool' defined but not used [-Wunused-function]
AbstractMemory.c:387:1: warning: 'memory_read_array_of_string' defined but not used [-Wunused-function]
compiling ArrayType.c
compiling Buffer.c
compiling Call.c
compiling ClosurePool.c
In file included from c:/Ruby/include/ruby-2.2.0/ruby/win32.h:38:0,
                 from c:/Ruby/include/ruby-2.2.0/ruby/defines.h:163,
                 from c:/Ruby/include/ruby-2.2.0/ruby/ruby.h:29,
                 from c:/Ruby/include/ruby-2.2.0/ruby.h:33,
                 from ClosurePool.c:35:
c:\rubydevkit\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
compiling DataConverter.c
compiling DynamicLibrary.c
In file included from c:/Ruby/include/ruby-2.2.0/ruby/win32.h:38:0,
                 from c:/Ruby/include/ruby-2.2.0/ruby/defines.h:163,
                 from c:/Ruby/include/ruby-2.2.0/ruby/ruby.h:29,
                 from c:/Ruby/include/ruby-2.2.0/ruby.h:33,
                 from DynamicLibrary.c:30:
c:\rubydevkit\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
compiling ffi.c
compiling Function.c
Function.c: In function 'async_cb_event':
Function.c:556:9: warning: implicit declaration of function 'rb_thread_select' [-Wimplicit-function-declaration]
Function.c: At top level:
Function.c:610:1: warning: 'async_cb_wait' defined but not used [-Wunused-function]
Function.c:635:1: warning: 'async_cb_stop' defined but not used [-Wunused-function]
compiling FunctionInfo.c
compiling LastError.c
compiling MappedType.c
MappedType.c: In function 'mapped_initialize':
MappedType.c:63:11: warning: unused variable 't' [-Wunused-variable]
compiling MemoryPointer.c
MemoryPointer.c:133:1: warning: 'memptr_mark' defined but not used [-Wunused-function]
compiling MethodHandle.c
compiling Platform.c
compiling Pointer.c
compiling Struct.c
compiling StructByReference.c
compiling StructByValue.c
compiling StructLayout.c
StructLayout.c: In function 'struct_field_initialize':
StructLayout.c:80:9: warning: variable 'nargs' set but not used [-Wunused-but-set-variable]
compiling Thread.c
In file included from c:/Ruby/include/ruby-2.2.0/ruby/win32.h:38:0,
                 from c:/Ruby/include/ruby-2.2.0/ruby/defines.h:163,
                 from c:/Ruby/include/ruby-2.2.0/ruby/ruby.h:29,
                 from c:/Ruby/include/ruby-2.2.0/ruby.h:33,
                 from Thread.h:25,
                 from Thread.c:32:
c:\rubydevkit\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
Thread.c: In function 'wait_for_thread':
Thread.c:220:5: warning: implicit declaration of function 'rb_thread_select' [-Wimplicit-function-declaration]
Thread.c:215:13: warning: unused variable 'res' [-Wunused-variable]
Thread.c: In function 'rbffi_thread_blocking_region':
Thread.c:246:11: warning: unused variable 'res' [-Wunused-variable]
Thread.c:245:11: warning: unused variable 'state' [-Wunused-variable]
compiling Type.c
compiling Types.c
compiling Variadic.c
linking shared-object ffi_c.so
Function.o: In function `async_cb_event':
C:\Ruby\lib\ruby\gems\2.2.0\gems\ffi-1.0.11\ext\ffi_c/Function.c:556: undefined reference to `rb_thread_select' Thread.o: In function `wait_for_thread':
C:\Ruby\lib\ruby\gems\2.2.0\gems\ffi-1.0.11\ext\ffi_c/Thread.c:220: undefined reference to `rb_thread_select' collect2.exe: error: ld returned 1 exit status
make: *** [ffi_c.so] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby/lib/ruby/gems/2.2.0/gems/ffi-1.0.11 for inspection.
Results logged to C:/Ruby/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/ffi-1.0.11/gem_make.out`

I´ve re-installed ruby + DevKit, and also deactivated my virus scanner, as proposed in other issues with similar/same error messages.

Thx for help,
Christian

**Comment by larskanis** [comment]
ffi-1.0.11 is 4 years older than the ruby version you're using. Please upgrade the ffi gem to a more resent version! This should fix your issue.

**Comment by tduehr** [comment]
FFI 1.0.11 was released shortly after the initial release of ruby 1.9.3. It would have been written for ruby 1.8.6 which is no longer supported. Please upgrade your FFI gem to current release.
