### ISSUE TITLE
cucumber - ffi-c Load error

### ISSUE THREAD

**Issue by paulyom** [ffi/ffi#503]
HI, I'm having difficulties running cucumber, The following is the output when trying to launch scripts.
I have ruby 2.3 installed. I have installed DevKit-mingw64 and am working on a win8.1 machine.
I have spent a bit of time with this now but am getting nowhere with it. I have also ran gem install ffi --platform=ruby

C:\Users\************>cucumber

Windows
cannot load such file -- ffi_c (LoadError)
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `rescue in <top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:3:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess/windows.rb:1:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess.rb:176:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver.rb:20:in `<top (require
d)>'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium-webdriver.rb:20:in `<top (require
d)>'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver.rb:1:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
C:/Users/paul.omahony/features/step_definitions/Aztec_Steps.rb:2:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/rb_support/rb_language.rb:96:in `load'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_f
ile'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/runtime/support_code.rb:142:in `load_file'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/runtime/support_code.rb:84:in `block in load
_files!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/runtime/support_code.rb:83:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/runtime.rb:254:in `load_step_definitions'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/runtime.rb:62:in `run!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/cli/main.rb:32:in `execute!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/bin/cucumber:8:in `<top (required)>'
C:/Ruby23-x64/bin/cucumber:22:in `load'
C:/Ruby23-x64/bin/cucumber:22:in `<main>'

**Comment by larskanis** [comment]
The current ffi binary Windows gem doesn't support RubyInstaller 2.3. You need to uninstall this version first:

@tduer could you please release a new version of ffi? Git master fixes this issue.

**Comment by paulyom** [comment]
HI Lars, Thanks for replying, After uninstalling and running cmd you posted, this was the out put

C:\Users\paul.omahony>gem install  ffi --platform ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20160517-83068-3e6kgy.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... no
creating extconf.h
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/ffi-1.9.10/mkmf.log

current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c
make "DESTDIR=" clean

current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c
make "DESTDIR="

make failed, uncaught signal 11

Gem files will remain installed in C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.10 for inspection.
Results logged to C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/ffi-1.9.10/gem_make.out

**Comment by P3t3rU5** [comment]
refer to issue #500

**Comment by larskanis** [comment]
Signal 11 is a segfault. This is probably not related to ffi, but seems to be related to your devkit installation. Maybe it's the some virus scanner that breaks the build.

Can you install other gems like `gem inst atomic` or `gem inst json` ?

I just verified, that `gem inst ffi --platform ruby` works on RubyInstaller-2.3 as ever.

**Comment by tduehr** [comment]
This should be fixed with 1.9.13

**Comment by larskanis** [comment]
@tduehr It should be fixed with 1.9.13, but unfortunately isn't. The gem doesn't contain binaries for RubyInstaller-2.3.

How did you build it? It should built out of the box per `rake gem:windows`. Or did you set a `RUBY_CC_VERSION` other than [this](https://github.com/ffi/ffi/blob/master/Rakefile#L178) ?

I still offer my help to maintain this project.

**Comment by tduehr** [comment]
This should be fixed in 1.9.14. I had an outdated version of `rake-compiler-dock` somehow.
