### ISSUE TITLE
Failed to build gem native extension in 1.9.12

### ISSUE THREAD

**Issue by bsautel** [ffi/ffi#511]
Hello.

I am using ffi in a Java build via the [gradle compass](https://github.com/robfletcher/gradle-compass) plugin.

The build suddently broke yesterday and I found out that is is due to the fact the ffi gem cannot be installed.

The latest successful build used the `ffi-1.9.10-java` version. It is now using the `1.9.12` version.

I get this error message:
```
ERROR:  Error installing /jenkins/.gradle/caches/modules-2/files-2.1/rubygems/ffi/1.9.12/11f071647b365cb1ac17275a9eb39b4e4a2a42d9/ffi-1.9.12.gem:
ERROR: Failed to build gem native extension.

java -jar /jenkins/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.15/4d9cb332bad3633c9c23a720542f456dc0c58a81/jruby-complete-1.7.15.jar extconf.rb
    LoadError: no such file to load -- /jenkins/jobs/Build
require at org/jruby/RubyKernel.java:1065
require at /jenkins/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.15/4d9cb332bad3633c9c23a720542f456dc0c58a81/jruby-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
```

This message `no such file to load -- /jenkins/jobs/Build` might explain the cause of the issue. My build directory contains a blank character. It is `/jenkins/jobs/Build website/[...]` and not just `/jenkins/jobs/Build`.

Would there be any change since 1.9.10 that could explain a behavior change with blank characters in paths?

Thanks.

**Comment by abiacco** [comment]
1.9.10 is the latest java version listed on rubygems.
I haven't used any version after that since i get the following error in my jruby runtime:

`Ignoring ffi-1.9.13 because its extensions are not built.  Try: gem pristine ffi --version 1.9.13`

Don't know if they plan on releasing a java version for the new stuff.

**Comment by bsautel** [comment]
Is JRuby supposed to use only `-java` versions? It does not seem to be the case.

**Comment by abiacco** [comment]
I'm new to ffi, so can't say for sure. Just sharing my experience.

**Comment by larskanis** [comment]
I pushed the `-java` gem.

Yes, JRuby is supposed to use only `-java` versions. The `-java` version is a stub only, because the ffi API is builtin into JRuby.

**Comment by bsautel** [comment]
Thanks @larskanis , it is now working again.

But it sounds like in my case JRuby was not using a `-java` version. Don't know why.
