### ISSUE TITLE
Change ruby ENV["TZ"] with ffi

### ISSUE THREAD

**Issue by ashmaroli** [ffi/ffi#529]
Hello,
My current understanding is that Windows does not understand timezones in Olson format and if used to configure `ENV["TZ"]` within ruby, it always ends up defaulting to UTC-Zero.
Is there a way to use `ffi` to have this implemented for Ruby users on Windows? Say, someone tries to set `TZ = 'America/New_York`. This implementation would then automatically look up `tzinfo/data` and convert to `UTC+05:00` (POSIX format) which Windows seems to understand. 

Thanks

**Comment by tduehr** [comment]
I would not want to monkey around with the ENV global at all. I would expect anyone directly setting environment variables in Ruby to know how it should be set and how to handle the values coming from it when read.

If you'd like to provide a wrapper to set the `TZ` environment variable properly for the current platform, a class method within your gem allows you to correctly format the value user's input for the running platform.
