### ISSUE TITLE
Does AutoPointer work (by default) in Jruby?

### ISSUE THREAD

**Issue by abrandoned** [ffi/ffi#536]
Since JRuby disables ObjectSpace by default, does AutoPointer work under JRuby? (without enabling ObjectSpace)

It looks like AutoPointer is dependent on ObjectSpace, but didn't know if `define_finalizer` would manifest different behavior from needing to use `each_object` in ObjectSpace

https://github.com/ffi/ffi/blob/master/lib/ffi/autopointer.rb#L96

@headius

**Comment by Adithya-copart** [comment]
@abrandoned Sorry for bumping this old issue but to answer the question, I think it works without ObjectSpace enabled.

I came across https://github.com/ffi/ffi/issues/536 while filing https://github.com/ffi/ffi/issues/741 as Github marked them to be similar. I was curious and tried the following.

```
$ irb -r ffi --noprompt
require 'java'

java_import 'java.lang.System'


ptr = FFI::MemoryPointer.new(10).tap {|p| p.write_string 'test'}.read_pointer
ap = FFI::AutoPointer.new(ptr, proc {ptr.method(:free)})
ObjectSpace.define_finalizer(ap, proc { p 'Finalizer is called!!!' })
ap = nil

System.gc()

ObjectSpace.each_object {}
Traceback (most recent call last):
        7: from /Users/adpentela/.rvm/rubies/jruby-9.2.7.0/bin/irb:13:in `<main>'
        6: from org/jruby/RubyKernel.java:1193:in `catch'
        5: from org/jruby/RubyKernel.java:1193:in `catch'
        4: from org/jruby/RubyKernel.java:1425:in `loop'
        3: from org/jruby/RubyKernel.java:1061:in `eval'
        2: from (irb):25:in `evaluate'
        1: from org/jruby/RubyObjectSpace.java:174:in `each_object'
RuntimeError (ObjectSpace is disabled; each_object will only work with Class, pass -X+O to enable)

```

**Comment by headius** [comment]
Most of ObjectSpace works without the flag. The only things we disable are `ObjectSpace.each_object` when passing anything other than `Class` or `Module`, and all uses of `ObjectSpace._id2ref` since that is an internal function from CRuby that should not be used.

`AutoPointer` should work just fine, but please report an issue if it does not!

**Comment by larskanis** [comment]
Thank you @headius for clarification!
