### ISSUE TITLE
v1.9.14 fails to correctly lay out structs in select cases, uses wrong padding

### ISSUE THREAD

**Issue by npomf** [ffi/ffi#541]
# Issue

When using the `FFI::Struct` class under select conditions, the byte-padding of various members within a struct will *not* match the underlying implementation, which calls into question whether the FFI is correctly matching the system's default behaviors when no additional directives are given.

## Environment details

* Ruby used is: `ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]`
* FFI Gem version:  `ffi (1.9.14 x64-mingw32)`
* OS:  Windows 7 Professional 64-bit
* CPU:  Intel i5-4690

## Code which produces the problem

This uses the same representation as the *vulkan.h* header and uses a mixin which allows initialization of structs from hashes of member -> value pairs.  It has been tested thoroughly and shows no issues with other structs.  Likewise. the `.pointer()` method is a shortcut added to allow the array, `@queues`, to be converted into a pointer, as is the usability of members as virtual reader methods to provide cleaner code.

```ruby
# create swapchain info
scci = VkSwapchainCreateInfoKHR.new(
    sType: :VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR,
    surface: @surface,
    minImageCount: caps.minImageCount,
    imageFormat: format,
    imageColorSpace: colorspace,
    imageExtent: caps.currentExtent,
    imageArrayLayers: 1, # monoscopic
    imageUsage: Vulkan::VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT,
    imageSharingMode: (@queues.length.eql? 1) ? :VK_SHARING_MODE_EXCLUSIVE : :VK_SHARING_MODE_CONCURRENT,
    queueFamilyIndexCount: @queues.length,
    pQueueFamilyIndices: @queues.pointer( :uint ),
    preTransform: caps.currentTransform,
    compositeAlpha: :VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR,
    presentMode: mode,
    clipped: VK_TRUE,
    oldSwapchain: from || VK_NULL_HANDLE
)
```

**The structs in question**

The [VkSwapchainCreateInfoKHR](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/vulkan/vulkan.h#L3313), created above:

```ruby
class Vulkan::VkSwapchainCreateInfoKHR < FFI::Struct
    layout sType:                       :VkStructureType,
           pNext:                       :pointer,
           flags:                       :VkSwapchainCreateFlagsKHR,
           surface:                     :pointer,
           minImageCount:               :uint32_t,
           imageFormat:                 :VkFormat,
           imageColorSpace:             :VkColorSpaceKHR,
           imageExtent:                 Vulkan::VkExtent2D.ptr,
           imageArrayLayers:            :uint32_t,
           imageUsage:                  :VkImageUsageFlags,
           imageSharingMode:            :VkSharingMode,
           queueFamilyIndexCount:       :uint32_t,
           pQueueFamilyIndices:         :pointer,
           preTransform:                :VkSurfaceTransformFlagBitsKHR,
           compositeAlpha:              :VkCompositeAlphaFlagBitsKHR,
           presentMode:                 :VkPresentModeKHR,
           clipped:                     :VkBool32,
           oldSwapchain:                :pointer
end
```

The [VkExtent2D](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/vulkan/vulkan.h#L1781), which is the first site of the errors captured:

```ruby
class Vulkan::VkExtent2D < FFI::Struct
    layout width:   :uint32_t,
           height:  :uint32_t
end
```

**Output**

System output shows seemingly correct sizes and alignments, but offsets do not match what vulkan anticipates.  See the section below regarding the *validation layer* and its introspection of the data.

```
DIAGNOSTIC: Vulkan::VkExtent2D is 8 bytes, aligned to 4
DIAGNOSTIC: Vulkan::VkSwapchainCreateInfoKHR is 104 bytes, aligned to 8
DIAGNOSTIC: offsets:
 - sType @ 0 => VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR
 - pNext @ 8 => #<FFI::Pointer address=0x00000000000000>
 - flags @ 16 => 0
 - surface @ 24 => #<FFI::Pointer address=0x00000000000001>
 - minImageCount @ 32 => 2
 - imageFormat @ 36 => VK_FORMAT_B8G8R8A8_UNORM
 - imageColorSpace @ 40 => VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
 - imageExtent @ 48 => #<Vulkan::VkExtent2D:0x00000002ba0570>
 - imageArrayLayers @ 56 => 1
 - imageUsage @ 60 => 16
 - imageSharingMode @ 64 => VK_SHARING_MODE_EXCLUSIVE
 - queueFamilyIndexCount @ 68 => 1
 - pQueueFamilyIndices @ 72 => #<FFI::Pointer address=0x00000002d661c0>
 - preTransform @ 80 => VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR
 - compositeAlpha @ 84 => VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR
 - presentMode @ 88 => VK_PRESENT_MODE_MAILBOX_KHR
 - clipped @ 92 => 1
 - oldSwapchain @ 96 => #<FFI::Pointer address=0x00000000000000>
```

**Validation Layer**

The validation layer captures the issue below:

```
Swapchain(ERROR): object: 0x44a3550 type: 3 location: 1288 msgCode: 8: vkCreateSwapchainKHR() called with pCreateInfo->i
mageExtent = (0,1280), which is not equal to the currentExtent = (1280,800) returned by vkGetPhysicalDeviceSurfaceCapabi
litiesKHR().
Swapchain(ERROR): object: 0x44a3550 type: 3 location: 1471 msgCode: 17: vkCreateSwapchainKHR() called with a non-support
ed pCreateInfo->imageSharingMode (i.e. Unhandled VkSharingMode).
RuntimeError: Failed to create swapchain: VK_ERROR_VALIDATION_FAILED_EXT
```

In particular, it shows that the `pCreateInfo->imageExtent` value is incorrectly offset by *-4 bytes* when read back by Vulkan.

Effectively `pCreateInfo->imageExtent` *should* be at offset-44, **not** offset-48.  This is demonstrated in the correct code.

## Corrected code

This model of the struct is hand-packed to match the anticipated offsets of the `VkSwapchainCreateInfoKHR` struct; no changes were made to the struct class layout.  Specifically, it *completely bypasses* using the erroneous `FFI::Struct` class's handling of the structure's underlying layout and padding and alignment:

```ruby
# hand-pack it.
scci = FFI::MemoryPointer.from_string([
    Vulkan::VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR,    # sType
    0,                                                      # pNext
    0,                                                      # flags
    @surface.to_i,                                          # surface
    caps.minImageCount,                                     # minImageCount
    Vulkan.const_get( format ),                             # imageFormat
    Vulkan.const_get( colorspace ),                         # imageColorSpace
    1280, 800,                                              # imageExtent
    1,                                                      # imageArrayLayers
    Vulkan::VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT,            # imageUsage
    Vulkan::VK_SHARING_MODE_EXCLUSIVE,                      # imageSharingMode
    @queues.length,                                         # queueFamilyIndexCount
    @queues.pointer( :uint ).to_i,                          # pQueueFamilyIndices
    Vulkan.const_get( caps.currentTransform ),              # preTransform
    Vulkan::VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR,              # compositeAlpha
    Vulkan.const_get( mode ),                               # presentMode
    VK_TRUE,                                                # clipped
    VK_NULL_HANDLE                                          # oldSwapchain
].pack('QJQJLLLLLLLLQJLLLLJ'))
```

**Output**

Please note that in this case, the pointer is **105 bytes** long due to the additional null byte appended by FFI.  Otherwise, the contents exactly match what Vulkan anticipates and the initialization test completes successfully.

```
Loaded Vulkan in 0.380022 seconds
Creating environment ...
 => #<Vulkan::Environment:0x000000004692b8>
Setting up window ...
DIAGNOSTIC: FFI::MemoryPointer is 105 bytes
 => #<Vulkan::Window:0x00000002b8fc48>
Press ENTER to complete test
```

**Comment by larskanis** [comment]
The struct layout isn't defined correctly, isn't it?
```diff
           imageFormat:                 :VkFormat,
           imageColorSpace:             :VkColorSpaceKHR,
-           imageExtent:                 Vulkan::VkExtent2D.ptr,
+           imageExtent:                 Vulkan::VkExtent2D,
           imageArrayLayers:            :uint32_t,
           imageUsage:                  :VkImageUsageFlags,
```

Both a pointer and two unit32 have a size of 8 bytes, but the pointer has an alignment of 8 whereas two uint32 have 4 byte alignment. So I guess that's the root cause.

**Comment by npomf** [comment]
I referred to this: https://github.com/ffi/ffi/wiki/Structs#nested-pointers

Based on the very limited information and example code, it led me to believe that using `.ptr()` for a struct was the correct behavior.  Is this not the case?

**Comment by larskanis** [comment]
```.ptr()``` can be used for a pointer to a struct, but in this case it's an embedded struct.

**Comment by npomf** [comment]
This is not made clear anywhere in the documentation as something being possible.

Once I have tested the fix and found it to work, I'll close this issue and look into updating the wiki with more clear examples and usages.

**Comment by larskanis** [comment]
That would be great!

**Comment by npomf** [comment]
Yup, that was it.  This issue is now closed.

I'll update the wiki soon.

**Comment by larskanis** [comment]
@npomf thanks for your contributions in the wiki!
