### ISSUE TITLE
time_t and suseconds_t types are wrong for freebsd

### ISSUE THREAD

**Issue by dcws** [ffi/ffi#544]
There is a longstanding bug with the ethons library such that select() intermittently returns 22 on select on FreeBSD, I have just tracked this down to the type definition in ffi being incorrect for (at least) time_t and suseconds_t  in ffi you have them as ints.. However a printf of sizeof(...) on FreeBSD 11-amd64 indicates they are 8 bytes long (and therefore int64).. I updated the specification to long in the files and was just able to solve the errno22 issue.

I am not sure at what point FreeBSD cut over to 64 bits for those structures (it was a LONG time ago though), how you would version differences in ABI formats within a platform, what is the correct value (long vs int64), what the difference is for the 2 time_t and suseconds_t types, or what other values there are incorrect; but I hope this could be quickly updated.

**Comment by t-zuehlsdorff** [comment]
Just to prevent confusion:
I just committed a patch to the FreeBSD ports-tree which will change the types until the bug is fixed in an release. :)

**Comment by dcws** [comment]
This was fixed in 
https://github.com/ffi/ffi/pull/627  thank you!
