### ISSUE TITLE
Windows: 'Could not open libary', file exists

### ISSUE THREAD

**Issue by sapphyrus** [ffi/ffi#549]
When I try to load [rbnacl](https://github.com/cryptosphere/rbnacl) I get this error:

![image](https://cloud.githubusercontent.com/assets/22681389/21785284/3c1d4bc8-d6bf-11e6-8760-ed23b8da732d.png)

As you can see from the screenshot the file does exist.

My script:
`::RBNACL_LIBSODIUM_GEM_LIB_PATH = 'C:\sapphyrusxyz\Server\libsodium\Win32\Release\v140\dynamic\libsodium.dll'`
`require 'rbnacl'
`

**Comment by sapphyrus** [comment]
System info:
![image](https://cloud.githubusercontent.com/assets/22681389/21810912/ee447310-d74d-11e6-8940-39898af40076.png)

**Comment by larskanis** [comment]
This error is typical, if the dll has further dependencies. Check the libsodium.dll with the Microsoft depends-tool. The dependent dlls can be loaded by chdir into their path while loading or by adding this path to the PATH environment variable.

**Comment by larskanis** [comment]
Have you been able to solve this issue? How did you solve it?

**Comment by sapphyrus** [comment]
Yeah, I did what you suggested and it turned out I was missing the Visual C++ Redistributable (was a fresh server). Installing [this](https://www.microsoft.com/en-us/download/details.aspx?id=48145) fixed my issue.
