### ISSUE TITLE
Windows binary gem for Ruby 2.4

### ISSUE THREAD

**Issue by nurse** [ffi/ffi#550]
gems of v1.9.14 doesn't include binary library:
```
% curl -s https://rubygems.org/downloads/ffi-1.9.14-x64-mingw32.gem|tar xO data.tar.gz|tar t|grep 'so$'
lib/2.0/ffi_c.so
lib/2.1/ffi_c.so
lib/2.2/ffi_c.so
lib/2.3/ffi_c.so
```

Could you release the new version which includes lib/2.4/ffi_c.so?

Or if you give me the privilege of GitHub ffi/ffi and [RubyGems ffi.gem](https://rubygems.org/gems/ffi), I'll do that.

**Comment by cosmo0920** [comment]
#556 can solve this issue?

**Comment by nurse** [comment]
https://github.com/ffi/ffi/pull/551 and v1.9.17 already fixes the issue

**Comment by cosmo0920** [comment]
I see.
ffi gem uses default value of `RUBY_CC_VERSION` for now.
Is it intended?

https://github.com/ffi/ffi/blob/master/Rakefile#L178

rake-compiler-dock had removed Ruby 1.8.7 and 1.9.3 from `RUBY_CC_VERSION`.
https://github.com/rake-compiler/rake-compiler-dock/blob/master/Dockerfile#L126

**Comment by nurse** [comment]
Hmm it should be updated, but v1.9.17 already have the 2.4 binary...
Anyway I close this because there's some other tickets.

```
% curl -s https://rubygems.org/downloads/ffi-1.9.17-x64-mingw32.gem|tar xO data.tar.gz|tar t|grep 'so$'
lib/2.0/ffi_c.so
lib/2.1/ffi_c.so
lib/2.2/ffi_c.so
lib/2.3/ffi_c.so
lib/2.4/ffi_c.so
```
