### ISSUE TITLE
Failed to build gem native extension

### ISSUE THREAD

**Issue by pathawks** [ffi/ffi#552]
I am a user of a gem that requires **ffi**

On a fresh Ubuntu install, I `apt install ruby` and then `gem install ffi`. I get the following error message:

```text
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.14/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20170113-5782-1eagrbg.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1
```

This can be fixed by installing `ruby-dev`, but now I am confused.

On the wiki, **ffi** brags that a user doesn't [need to install the development versions of libraries](https://github.com/ffi/ffi/wiki/Why-use-FFI#an-ffi-extension-doesnt-need-compilation), but clearly that is not the case.

This has been [quite a source of frustration for users](https://github.com/jekyll/jekyll/search?q=native+extension&type=Issues), and I'm curious if there is anything that can be done to make things easier or at least fail more gracefully.

**Comment by tduehr** [comment]
Users don't need to install the development versions of libraries other than Ruby. The dev version of Ruby would be required to build any C based gem that isn't installed via apt (or yum).

**Comment by ervinb** [comment]
I had this issue on a Fedora 25 installation, and solved it with:

```bash
$ sudo yum install libffi-devel redhat-rpm-config
```

The `ruby-devel` and `development-tools` packages were already installed.

**Comment by lpan** [comment]
@ervinb I solved it with `sudo dnf install redhat-rpm-config`. I wonder how is it related to this gem :stuck_out_tongue:

**Comment by hakobc** [comment]
$ sudo yum install libffi-devel redhat-rpm-config 
worked for me as well.

**Comment by lxhunter** [comment]
On ubuntu: ```apt-get install libffi-dev```

**Comment by bmann** [comment]
On Chromebook, using Chromebrew `crew install libffi`
