### ISSUE TITLE
fatal error: 'string' file not found

### ISSUE THREAD

**Issue by chadlwm** [ffi/ffi#559]
I try to translate c++ header file to ruby.

the c++ header just as below:

```c++
#include <string>
#include "st_common.h"
```

then I got a error:

```
./st_license.h:4:10: fatal error: 'string' file not found
```

the ffi generate file as below

```ruby
require "ffi_gen"

FFIGen.generate(
  module_name: "SDK::License",
  ffi_lib:     "libst_license.so.2",
  headers:     ["st_license.h"],
  cflags:      `llvm-config --cflags`.split(" "),
  prefixes:    [ 'ST_'],
  output:      "ffi.rb"
)
```

version info as below:

- ruby : `ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]`
- ffi: `1.9.17`
- ffi-gen: `1.2.0`

Anyone run into this issue, and how to resolve it?

thanks

**Comment by tduehr** [comment]
That looks like a problem with your ffi_gen code or config. Please file an issue with them: https://github.com/neelance/ffi_gen

**Comment by chadlwm** [comment]
thanks for your suggestion.
