### ISSUE TITLE
ffi 1.9.18 is not released fat gem for Windows

### ISSUE THREAD

**Issue by cosmo0920** [ffi/ffi#564]
In 1.9.18, ffi is not released fat gem for Windows.
I could install ffi gem with Devkit and Ruby 2.3.1, but Windows users usually do not create development environment in their machines.

**Comment by xavivars** [comment]
Same thing happened to me. I had to 'lock' my Gemfile to 1.9.17 to be able to get a working version.

**Comment by larskanis** [comment]
I just pushed the mingw versions of the gem. Please close the issue, if it works for you!

**Comment by cosmo0920** [comment]
Thanks, it works!

```log
<snip>
GEM
  remote: https://rubygems.org/
  specs:
    cool.io (1.4.6-x64-mingw32)
    docile (1.1.5)
    ffi (1.9.18-x64-mingw32)
    ffi-win32-extensions (1.0.3)
      ffi
<snip>
```
