### ISSUE TITLE
Using FFI or Fiddle on an Embedded Ruby

### ISSUE THREAD

**Issue by BackOrder** [ffi/ffi#569]
I would like to be able to pass Ruby varargs as an argument to a C function created with `rb_define_method`. The typical prototype for a C function with **argc = -1** is `VALUE func(int argc, VALUE *argv, VALUE obj)`.

The following is a code sample that would be representative of the situation but yet would work with a standard Ruby. **VALUE \*** is the challenging part — it works as an array but not as a splat.

```ruby
require("fiddle")
require("fiddle/import")

module EmbeddedRuby
   extend Fiddle::Importer
   dlload("msvcrt-ruby220.dll")

   typealias "VALUE", "unsigned long"

   extern "VALUE rb_ary_cat(VALUE, const VALUE *, long)"
end

a = [ "a", "b", "c" ]
b = ["d", "e", "f"]

puts a.dup.push(b).inspect
puts a.dup.push(*b).inspect

puts Fiddle::Pointer.new(
         EmbeddedRuby.rb_ary_cat(
            Fiddle::Pointer.new(a.__id__ << 1),
            Fiddle::Pointer.new(b.__id__ << 1).ref,
            b.size)).to_value.inspect
```

The Ruby script outputs the following on Ruby 2.2.6:

```
["a", "b", "c", ["d", "e", "f"]]
["a", "b", "c", "d", "e", "f"]
["a", "b", "c", ["d", "e", "f"], false, false]
```

The expected results would be `["a", "b", "c", "d", "e", "f"]`. Anyone knows how to do this with either Fiddle or FFI (or both)?

**Comment by BackOrder** [comment]
Anyone? @tduehr ? :)

**Comment by tduehr** [comment]
Why would you want to call the C version of a Ruby function through FFI in Ruby?!?

This may give you some help: https://zegoggl.es/2009/05/ruby-ffi-recipes.html

You're also defining the function as taking an array of Ruby objects in your impl. You have to find a way to get it to set up to use varargs.

**Comment by BackOrder** [comment]
> Why would you want to call the C version of a Ruby function through FFI in Ruby?!?

Embedded Ruby. [Shoes](https://github.com/Shoes3/shoes3)

All Ruby classes and methods for GUI elements are defined in C (`rb_define_class`, `rb_define_method`, etc). This approach lacks of flexibility and makes it hard to provide a proper DSL to Shoes users. I would instead like to create classes in Ruby and link methods to corresponding legacy C functions.

Hooking existing GUI elements through FFI/Fiddle is working (libshoes.dll, libshoes.so) but full replacement is not successful. Ruby FFI/Fiddle doesn't like C calling convention for Ruby methods. Rewriting Shoes to use Ruby convention (`VALUE self, VALUE args`) would require considerable time. Splat operator is also a challenge.

**Comment by tduehr** [comment]
By convention, `rb_` functions are exposed in Ruby somewhere. Unless you need to do something extremely specific and esoteric, stick to the stuff exposed in Ruby. Those C functions are exposed in Ruby as `Class.new` and `Object@define_method`, respectively.

If you want to be able to call them as C functions from Ruby, you'll have to figure out what magic the runtime does and what is added to `VALUE` so it knows multiple arguments are being passed rather than a single array argument.

**Comment by BackOrder** [comment]
> By convention, rb_ functions are exposed in Ruby somewhere. Unless you need to do something extremely specific and esoteric, stick to the stuff exposed in Ruby. Those C functions are exposed in Ruby as Class.new and Object@define_method, respectively.

I would like to remove those `rb_` functions in favour of writing code in Ruby. It means by the time the embedded Ruby is running, a given class and its methods will not be defined but C code for low level things are available.

> If you want to be able to call them as C functions from Ruby, you'll have to figure out what magic the runtime does and what is added to VALUE so it knows multiple arguments are being passed rather than a single array argument.

The code in my original post is does exactly that. It exposes the fact that splat operator is a special case in Ruby. If you would change `b.zise` for `1` (one object as an argument: an array), you would obtain `["a", "b", "c", ["d", "e", "f"]]` — which is the expected behaviour for a single object as argument.

Essentially, calling C functions has worked so far but the splat operator is ruining the party.

**Comment by tduehr** [comment]
Your code is passing an instance of Array and saying it's passing three arguments. That's where the other two entries are coming from: the space after the array that happens to be `Qnil`. You have to flatten it to a C array of `VALUE` pointers or get to the underlying `VALUE *` in the Array object.

That can be done in both FFI and Fiddler just as you'd do for any other Array going into a C function.

**Comment by BackOrder** [comment]
> Your code is passing an instance of Array and saying it's passing three arguments. That's where the other two entries are coming from: the space after the array that happens to be Qnil. 

Indeed. It would work for a splat array but not for an array. There seems to be no way to define a splat array at C level. Yacc parses the splat array (`NODE_SPLAT`) and tells the compiler to set an internal flag (`VM_CALL_ARGS_SPLAT` in [compiler.c](https://github.com/ruby/ruby/blob/7519688ed86cb8b423fd24d4e27964056e78bc9b/compile.c#L3879)).

> get to the underlying VALUE * in the Array object.

Isn't it what I am doing at the moment using **ref**? `Fiddle::Pointer.new(b.__id__ << 1).ref`

> You have to flatten it to a C array of VALUE pointers or [...]. That can be done in both FFI and Fiddler just as you'd do for any other Array going into a C function.

This is an idea! How would you do it? I have attempted in both Fiddle and FFI (based on [Ruby FFI Recipes](https://zegoggl.es/2009/05/ruby-ffi-recipes.html) you provided) without success. The receiving C function (`rb_ary_cat` in this case) is not liking it and causes a segfault.

**Comment by tduehr** [comment]
No, your `VALUE *` going into the call is to the Ruby Array object `b`. This is a single argument, you just happen to be getting `Qfalse` object behind that call. Essentially, the call would look something like this if written in Ruby:

~~~ruby
a.dup.push(*[b, false, false])
~~~

You need to create a `VALUE **` containing references to the Ruby objects in `b`.

~~~
argv = FFI::MemoryPointer.new(:pointer, b.length)
b.each_with_index do |p, i|
  argv[i].put_pointer(0,  MORE_MAGIC(p))
end
~~~

The only problem is that `MORE_MAGIC` is quite a bit of magic. You'd have to find a way to get at the underlying  `VALUE*` of each Ruby object in `b`.

That is going to be implementation, possibly platform, dependent. For MRI, you might be getting that with `Fiddle::Pointer.new(b.__id__ << 1)`.

Looking at the use case again, I'm not sure why you think defining methods in C makes it hard to create a DSL for them. As I said before, they're all accessible from Ruby already. The usage of `rb_define_class` and `rb_define_method` in C is to tell the VM where to glue those C functions into  Ruby to make them available in the runtime. Messing with Ruby implementation internals is not within scope of a library like FFI or Fiddle. A proper bridge between the runtime and implementation language has to be created. This likely requires a few hooks into the implementation handling of certain objects.

An example there is JRuby. There is a wonderful bridge between Java and Ruby implemented for JRuby. It's good enough that porting Java code to Ruby is little more than some syntax tweaks. Even then, messing with just the edges of runtime internals is iffy and results can be rather unpredictable.

Can you provide a specific example of where creating a DSL is giving you problems?

**Comment by BackOrder** [comment]
After pondering for a while on your feedback, it seems to me the solution would be to provide a Ruby interface in C. It is some work but Ruby has a little too much magic to allow what I am looking for.  Thanks for your time!
