### ISSUE TITLE
Newbie confusion - FFI::Struct example containing string pointer missing in Wiki

### ISSUE THREAD

**Issue by casper** [ffi/ffi#571]
I couldn't find any example in the Wiki on how to construct an `FFI::Struct` that contains a string (`char *`) pointer. Can anyone help?

Here's what I got:
```
class SS << FFI::Struct
  layout :s1, :string
end

s = SS.new
s[:s1] = "hello"  # <- Gives error: `[]=': Cannot set :string fields (ArgumentError)
```

There are a lot of example on character buffers, but none on string pointers in structs as input. Is this even possible to do? How do I attach a string to the structure?

**Comment by casper** [comment]
Never mind. If anyone else stumbles upon this mystery. The solution is:

```
  layout :s1, :pointer
  ...
  s[:s1] = FFI::MemoryPointer.from_string("hello")
```

**Comment by larskanis** [comment]
@casper Keep in mind, that you need to store the `FFI::MemoryPointer` somewhere outside of the struct, in order to protect it from the garbage collector. Storing the pointer in a struct is not sufficient to keep the string in memory!
