### ISSUE TITLE
FFI crashing when run as a daemon

### ISSUE THREAD

**Issue by rbclark** [ffi/ffi#579]
Hello,

I am currently involved in a project which is using FFI as a bridge between ruby and go code. We have been having a problem where processes that use the Daemons gem do not work properly. A simple example is below

```
# daemons.rb
require 'daemons'
require 'ffi'


class MyDaemon
  extend FFI::Library
  # Initialize the app while we're not a daemon
  ffi_lib File.expand_path("helloworld.so", File.dirname(__FILE__))
  attach_function :hello_world, [ :string ], :string

  file_path = File.expand_path("nope.txt", File.dirname(__FILE__))

  # Become a daemon
  Daemons.daemonize

  # The server loop
  loop do
    File.open(file_path, 'w') { |f| f.write(hello_world("this is a test")) }
  end
end
```

```
// hello_world.go
package main

import (
  "C"
)

func main() {}

//export hello_world
func hello_world(input *C.char) *C.char{
  return input
}
```

We have compiled the go code with the command `go build -a -buildmode=c-shared -o helloworld.so helloworld.go` and then run `ruby daemons.rb`

What we have found is that when we remove the call to the hello_world go function inside of the loop the process prints successfully to a file over and over, however as soon as we add the call to the hello_world go function then the process no longer prints to the file. Calling the function outside of the daemonized loop also works fine. Also the process seems to completely crash and exit whenever the go code is called.

Do you have any hints on how we could go about getting this issue fixed or working around the issue?

Thank you.

**Comment by jbjbhatcher** [comment]
Hey, not sure if you're still working with this, but can you show your log output?

Should be able to by running your daemon like:

```
Daemons.run('my_daemon.rb', log_output: true, backtrace: true)
```

**Comment by jbjbhatcher** [comment]
I did this & it worked for me:

1. renamed hello_world.go to helloworld.go
2. Created a my_daemon control class, so I could debug the process
3. Removed the Daemons.daemonize line

```
# daemons.rb
require 'daemons'
require 'ffi'

class MyDaemon
    extend FFI::Library
    # Initialize the app while we're not a daemon
    ffi_lib File.expand_path("helloworld.so", File.dirname(__FILE__))
        # expand path takes the given file & converts it to an absolute pathname
    attach_function :hello_world, [ :string ], :string

    file_path = File.expand_path("nope.txt", File.dirname(__FILE__))

    # The server loop
    loop do
      File.open(file_path, 'w') { |f| f.write(hello_world("this is a test")) }
    end
end
```

```
# my_daemon_control.rb
require 'daemons'

Daemons.run('my_daemon.rb', log_output: true, backtrace: true)
```

Then, to start the daemon
```
ruby my_daemon_control.rb start
```

When you want it to stop,
```
ruby my_daemon_control.rb stop
```

**Comment by jbjbhatcher** [comment]
I think we can close this now ... @rbclark

**Comment by rbclark** [comment]
I appreciate the follow-up. I am unfortunately no longer working on the same project as when I reported this issue so I unfortunately can't test the solution. I appreciate the follow up though and I'll go ahead and close this issue.
