### ISSUE TITLE
[error] - ffi requires Ruby version < 2.5, >= 2.0. The current ruby version is 2.5.0.

### ISSUE THREAD

**Issue by Sibiraj-S** [ffi/ffi#597]
ERROR:  Error installing ffi:
        The last version of ffi (= 1.9.18) to support your Ruby & RubyGems was 1.9.18. Try installing it with `gem install ffi -v 1.9.18`
        ffi requires Ruby version < 2.5, >= 2.0. The current ruby version is 2.5.0.

**Comment by formanojhr** [comment]
How did this get resolved? Running into the same issue. ```
fluent-plugin-vmware-log-intelligence % sudo /opt/td-agent/usr/sbin/td-agent-gem -v
2.6.7
rmanoj@rmanoj-a01 fluent-plugin-vmware-log-intelligence % sudo /opt/td-agent/usr/sbin/td-agent-gem install llhttp-ffi
ERROR:  Error installing llhttp-ffi:
	llhttp-ffi requires Ruby version >= 2.5.0.
```
