### ISSUE TITLE
FFI not work in ruby 2.5.0

### ISSUE THREAD

**Issue by SHyZe** [ffi/ffi#602]
It would be necessary to renew developer because there is of the incompetence in putting has in the daytime with ruby

**Comment by Announcement** [comment]
yup; r.i.p. sass because of this.

**Comment by larskanis** [comment]
Which OS? Any error messages?

**Comment by richpeck** [comment]
Windows
![untitled](https://user-images.githubusercontent.com/1104431/35702927-5ec90af4-0792-11e8-8979-52cade19bf5e.png)

**Comment by JoshCheek** [comment]
Hitting this, as well.
![capture](https://user-images.githubusercontent.com/77495/35842274-afaeb18a-0ac6-11e8-821c-b6cae633fb2d.PNG)

**Comment by JoshCheek** [comment]
Oh. Please note that I'm on Ruby 2.5.0p0 (2017-12-15 revision 61468) [x64-mingw32], installed with Ruby Installer.

**Comment by garrit-schroeder** [comment]
https://rubygems.org/gems/ffi/versions/1.9.18-x64-mingw32
Ruby Gems Version is limited to < 2.5 on windows.

**Comment by headius** [comment]
Huh, I wonder why this restriction was put in place. In any case it is patched on master and I'll get a new release pushed out.

The win32 build will take a bit longer since I'm just now setting up C++ on my Windows VM.

**Comment by garrit-schroeder** [comment]
Thanks for the quick support.
Unfortunately, installing the new version results in an error:

C:\Users\USER\IdeaProjects\quark>gem install ffi
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing ffi:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.19/ext/ffi_c
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20180206-11824-egniw0.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.19/ext/ffi_c
make "DESTDIR=" clean

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.19/ext/ffi_c
make "DESTDIR="
generating ffi_c-x64-mingw32.def
Running autoreconf for libffi
/bin/sh: Zeile 2: cd: /c/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.19/ext/ffi_c/libffi: No such file or directory
make: *** [libffi.mk:7: "/c/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.19/ext/ffi_c/libffi-x64-mingw32"/.libs/libffi_convenience.a] Fehler 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.19 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/ffi-1.9.19/gem_make.out

**Comment by larskanis** [comment]
@headius The ruby version restriction comes from rake-compiler and is set depending on the binaries included into the ffi-x64-mingw32.gem . Windows gems can be built per `rake gem:windows` on Linux.

As a proposal: I could publish a new ffi release every year, when a new ruby, RubyInstaller and rake-compiler-dock release comes out. I already have push privilege to rubygems, but not to github - and I don't want to push something, that is not visible in git. This way we could avoid this gap between the ruby and the binary ffi release every year.

**Comment by headius** [comment]
@larskanis Yup I just realized the docker stuff was in there. After some false starts, I've got that running now. I'd be happy to add you as a pusher for the FFI gem.

1.9.21 has already been pushed for "ruby" and "java" platforms. Windows coming shortly.

**Comment by headius** [comment]
@garrit-schroeder Yeah, I forgot to pull libffi before building. 1.9.21 should build ok for you.

**Comment by headius** [comment]
@larskanis Grr...I seem to run into no end of problems with this. Can you try to get the Windows gems built? I'll add you as a pusher. Same username?

**Comment by headius** [comment]
See rake-compiler/rake-compiler-dock#18 and rake-compiler/rake-compiler-dock#19 for the issues I ran into.

**Comment by headius** [comment]
@larskanis You appear to have push rights already. I'm stuck trying to build the Windows gems and have to give a conf presentation in a little while. Hopefully you or @tduehr can get them to build.

I'll check back later this afternoon (CET) and see if I should keep trying :-)

**Comment by larskanis** [comment]
Thanks @headius ! I'll fix the issues and push the gem, when I'm back at home in the evening.

**Comment by garrit-schroeder** [comment]
Windows gem version ..21 works for me.
Thanks a lot

Am 06.02.2018 14:55 schrieb "Lars Kanis" <notifications@github.com>:

**Comment by larskanis** [comment]
Had to [fix ruby](https://github.com/ruby/ruby/pull/1811), then [rake-compiler-dock](https://github.com/rake-compiler/rake-compiler-dock/commit/a311e4256239861a5d35062cf17b4dd110562e75) and make a new release there, but after all `rake gem:windows` worked as expected. Insofar ffi-1.9.21 binary gems are pushed now with support for ruby-2.5.

**Comment by RKushnir** [comment]
Hi. I'm having the same problem on a mac:
```
> gem install ffi -v '1.9.21'
Building native extensions. This could take a while...
ERROR:  Error installing ffi:
  ERROR: Failed to build gem native extension.

    current directory: /Users/iloveffi/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
/Users/iloveffi/.rbenv/versions/2.5.0/bin/ruby -r ./siteconf20180213-10005-1cjdk9d.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

current directory: /Users/iloveffi/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR=" clean

current directory: /Users/iloveffi/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR="
Running autoreconf for libffi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
make: *** ["/Users/iloveffi/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c/libffi-x86_64-darwin17"/.libs/libffi_convenience.a] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/iloveffi/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ffi-1.9.21 for inspection.
Results logged to /Users/iloveffi/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/ffi-1.9.21/gem_make.out
```

**Comment by RKushnir** [comment]
I managed to resolve it with `brew install automake`. All fine now.

**Comment by ianbytchek** [comment]
Learned it the hard way on macOS. If you happen to have multiple versions of Xcode installed, make sure it uses no spaces in path and Xcode is correctly selected to use for command line developer tools `sudo xcode-select --switch path/to/Xcode.app`. Can we have a check for that?
