### ISSUE TITLE
ffi (1.9.21) instalation fails in linux 

### ISSUE THREAD

**Issue by manikandankumaraswamy** [ffi/ffi#611]
Hi Team,

 When I run bundle install I am getting following  error due to that our execution is completely blocked . Please take a look and provide me a solution ASAP. Your support will be greatly appreciated.

    current directory: /usr/local/lib/ruby/gems/2.1.0/gems/ffi-1.9.21/ext/ffi_c
/usr/local/bin/ruby -r ./siteconf20171117-20625-1gne56g.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... yes
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.1.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.1.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR="
Running autoreconf for libffi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:3: error: Autoconf version 2.68 or higher is required
configure.ac:3: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
make: *** ["/usr/local/lib/ruby/gems/2.1.0/gems/ffi-1.9.21/ext/ffi_c/libffi-x86_64-linux"/.libs/libffi_convenience.a] Error 63

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.1.0/gems/ffi-1.9.21 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/ffi-1.9.21/gem_make.out

An error occurred while installing ffi (1.9.21), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.21'` succeeds before bundling.

linux version:  2.6.32-573.el6.x86_64 #1 SMP Wed Jul 1 18:23:37 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by paulomcnally** [comment]
# Something similar happened to me in MacOS

```
gem install ffi -v '1.9.21'   
Building native extensions. This could take a while...





ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /Users/moisolutions/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
/Users/moisolutions/.rbenv/versions/2.5.0/bin/ruby -r ./siteconf20180209-4731-1hpi9pb.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

current directory: /Users/moisolutions/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR=" clean

current directory: /Users/moisolutions/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR="
Running autoreconf for libffi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
make: *** ["/Users/moisolutions/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c/libffi-x86_64-darwin17"/.libs/libffi_convenience.a] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/moisolutions/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ffi-1.9.21 for inspection.
Results logged to /Users/moisolutions/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/ffi-1.9.21/gem_make.out

```

**Comment by paulomcnally** [comment]
Solved on MacOS

`$ brew install automake autoconf libtool`
`$ gem install ffi -v '1.9.21'`

For Ubuntu try:

https://github.com/ffi/ffi/issues/608#issuecomment-363698071

**Comment by ddongule** [comment]
Thank you @paulomcnally you saved my life !!!!!! and my friend's !!!!!!!!!!!

**Comment by ntloi95** [comment]
It's only SOLVED on MAC, how about on Linux?

**Comment by marckohlbrugge** [comment]
> Solved on MacOS
> 
> `$ brew install automake autoconf libtool`
> `$ gem install ffi -v '1.9.21'`
> 
> For Ubuntu try:
> 
> [#608 (comment)](https://github.com/ffi/ffi/issues/608#issuecomment-363698071)

For me `sudo xcodebuild -license accept` was enough

**Comment by Victorcorcos** [comment]
@paulomcnally 

```rb
gem install ffi -v '1.9.21'
```

Gives me this result

```rb
$ gem install ffi -v '1.9.21'
Building native extensions. This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /Users/macbookair/.rvm/gems/ruby-2.5.5/gems/ffi-1.9.21/ext/ffi_c
/Users/macbookair/.rvm/rubies/ruby-2.5.5/bin/ruby -I /Users/macbookair/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0 -r ./siteconf20200914-14372-udumti.rb extconf.rb
checking for ffi_call() in -lffi... yes
checking for ffi_prep_closure()... yes
checking for ffi_raw_call()... yes
checking for ffi_prep_raw_closure()... yes
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... yes
creating extconf.h
creating Makefile

current directory: /Users/macbookair/.rvm/gems/ruby-2.5.5/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR=" clean

current directory: /Users/macbookair/.rvm/gems/ruby-2.5.5/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR="
compiling AbstractMemory.c
compiling ArrayType.c
compiling Buffer.c
compiling Call.c
Call.c:355:5: error: implicit declaration of function 'rb_thread_call_without_gvl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    rbffi_thread_blocking_region(call_blocking_function, data, (void *) -1, NULL);
    ^
./Thread.h:78:39: note: expanded from macro 'rbffi_thread_blocking_region'
# define rbffi_thread_blocking_region rb_thread_call_without_gvl
                                      ^
1 error generated.
make: *** [Call.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/macbookair/.rvm/gems/ruby-2.5.5/gems/ffi-1.9.21 for inspection.
Results logged to /Users/macbookair/.rvm/gems/ruby-2.5.5/extensions/x86_64-darwin-18/2.5.0/ffi-1.9.21/gem_make.out
```

And that is making me very sad 😢 

On my specific case, I need this gem to proper setup the environment to work with `flutter` on MacOS

ℹ️  I am using MacOS Catalina 10.15.6

**Comment by farhan-chughtai** [comment]
You can fix this by adding the flag
gem install ffi -v '1.9.21' -- --with-cflags="-Wno-error=implicit-function-declaration"

**Comment by fffx** [comment]
For bundle 
```
bundle config build.ffi --with-cflags="-Wno-error=implicit-function-declaration"
```

**Comment by orubin** [comment]
> For bundle
> 
> ```
> bundle config build.ffi --with-cflags="-Wno-error=implicit-function-declaration"
> ```

Saved my life. 10x @fffx

**Comment by xlylei** [comment]
> For bundle
> 
> ```
> bundle config build.ffi --with-cflags="-Wno-error=implicit-function-declaration"
> ```

this work for me

**Comment by FDU2023JK4** [comment]
> 

saved my life

**Comment by krisleech** [comment]
For ffi 1.16.3 adding the cflags gives me " make: *** [Makefile:248: MemoryPointer.o] Error 4" instead.
