### ISSUE TITLE
Request to merge PR/540

### ISSUE THREAD

**Issue by nhosoi** [ffi/ffi#614]
Hello,

When selinux deny_execmem is set to 1 [1], our product crashes in rubygem-ffi.
We found the PR/540 [2] solves the problem.  Could it be possible to merge the PR?
Thanks.

[1] setsebool -P deny_execmem 1
[2] https://github.com/ffi/ffi/pull/540  "Do closures via libffi"

**Comment by headius** [comment]
I have merged it for the next release.

**Comment by nhosoi** [comment]
@headius 
> I have merged it for the next release.

Great news!  Thanks a lot.
