### ISSUE TITLE
Please help, I'm getting this error while trying to install ffi gem 

### ISSUE THREAD

**Issue by kaesy** [ffi/ffi#620]
`Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing D:\rubygems\ffi-1.9.23.gem:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.23/ext/ffi_c
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20180307-12816-euridb.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby24-x64/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:1095:in `block in have_header'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:1094:in `have_header'
        from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ffi-1.9.23/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.23 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ffi-1.9.23/gem_make.out`

**Comment by larskanis** [comment]
As proposed in the error message, you should have a look into `C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ffi-1.9.23/mkmf.log` to in order get a more detailed error message.

I can only guess, that the compiler toolchain isn't installed. Did you run `ridk install 3`?
