### ISSUE TITLE
Doesn't install

### ISSUE THREAD

**Issue by ypadlyak** [ffi/ffi#628]
$ gem install ffi -v '1.9.18'  
Fetching: ffi-1.9.18.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
        ERROR: Failed to build gem native extension.

    current directory: /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/ffi-1.9.18/ext/ffi_c
/home/ubuntu/.rvm/rubies/ruby-2.4.0/bin/ruby -r ./siteconf20180429-6005-rd7vz6.rb extconf.rb
checking for ffi_call() in -lffi... yes
checking for ffi_prep_closure()... yes
checking for ffi_raw_call()... yes
checking for ffi_prep_raw_closure()... yes
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... yes
creating extconf.h
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ubuntu/.rvm/gems/ruby-2.4.0/extensions/x86_64-linux/2.4.0/ffi-1.9.18/mkmf.log

current directory: /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/ffi-1.9.18/ext/ffi_c
make "DESTDIR=" clean

current directory: /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/ffi-1.9.18/ext/ffi_c
make "DESTDIR="
compiling AbstractMemory.c
compiling ArrayType.c
compiling Buffer.c
compiling Call.c
In file included from Call.h:36:0,
                 from Function.h:48,
                 from Call.c:57:
Call.c: In function ‘rbffi_do_blocking_call’:
Thread.h:78:39: warning: implicit declaration of function ‘rb_thread_call_without_gvl’ [-Wimplicit-function-declaration]
 # define rbffi_thread_blocking_region rb_thread_call_without_gvl
                                       ^
Call.c:355:5: note: in expansion of macro ‘rbffi_thread_blocking_region’
     rbffi_thread_blocking_region(call_blocking_function, data, (void *) -1, NULL);
     ^
compiling ClosurePool.c
compiling DataConverter.c
compiling DynamicLibrary.c
compiling Function.c
Function.c: In function ‘async_cb_event’:
Function.c:563:9: warning: implicit declaration of function ‘rb_thread_call_without_gvl’ [-Wimplicit-function-declaration]
         rb_thread_call_without_gvl(async_cb_wait, &w, async_cb_stop, &w);
         ^
compiling FunctionInfo.c
compiling LastError.c
compiling LongDouble.c
compiling MappedType.c
compiling MemoryPointer.c
compiling MethodHandle.c
compiling Platform.c
compiling Pointer.c
compiling Struct.c
compiling StructByReference.c
compiling StructByValue.c
compiling StructLayout.c
compiling Thread.c
compiling Type.c
compiling Types.c
compiling Variadic.c
compiling ffi.c
linking shared-object ffi_c.so

current directory: /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/ffi-1.9.18/ext/ffi_c
make "DESTDIR=" install
/usr/bin/install -m 0755 ffi_c.so ./.gem.20180429-6005-6vwtxa
Script is run as ubuntu. Please run as root
Makefile:187: recipe for target 'install-so' failed
make: *** [install-so] Error 1

make install failed, exit code 2

Gem files will remain installed in /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/ffi-1.9.18 for inspection.
Results logged to /home/ubuntu/.rvm/gems/ruby-2.4.0/extensions/x86_64-linux/2.4.0/ffi-1.9.18/gem_make.out

$ cat /home/ubuntu/***/shared/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/ffi-1.9.23/gem_make.out  
current directory: /home/ubuntu/***/shared/bundle/ruby/2.4.0/gems/ffi-1.9.23/ext/ffi_c
/home/ubuntu/.rvm/rubies/ruby-2.4.0/bin/ruby -r ./siteconf20180429-5266-x2ynfo.rb extconf.rb 
checking for ffi_call() in -lffi... yes
checking for ffi_closure_alloc()... yes
checking for ffi_raw_call()... yes
checking for ffi_prep_raw_closure()... yes
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... yes
creating extconf.h
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ubuntu/tickets/shared/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/ffi-1.9.23/mkmf.log

current directory: /home/ubuntu/***/shared/bundle/ruby/2.4.0/gems/ffi-1.9.23/ext/ffi_c
make "DESTDIR=" clean

current directory: /home/ubuntu/***/shared/bundle/ruby/2.4.0/gems/ffi-1.9.23/ext/ffi_c
make "DESTDIR="
compiling AbstractMemory.c
compiling ArrayType.c
compiling Buffer.c
compiling Call.c
In file included from Call.h:36:0,
                 from Function.h:48,
                 from Call.c:57:
Call.c: In function ‘rbffi_do_blocking_call’:
Thread.h:78:39: warning: implicit declaration of function ‘rb_thread_call_without_gvl’ [-Wimplicit-function-declaration]
 # define rbffi_thread_blocking_region rb_thread_call_without_gvl
                                       ^
Call.c:334:5: note: in expansion of macro ‘rbffi_thread_blocking_region’
     rbffi_thread_blocking_region(call_blocking_function, data, (void *) -1, NULL);
     ^
compiling Closure.c
compiling DataConverter.c
compiling DynamicLibrary.c
compiling Function.c
Function.c: In function ‘async_cb_event’:
Function.c:569:9: warning: implicit declaration of function ‘rb_thread_call_without_gvl’ [-Wimplicit-function-declaration]
         rb_thread_call_without_gvl(async_cb_wait, &w, async_cb_stop, &w);
         ^
compiling FunctionInfo.c
compiling LastError.c
compiling LongDouble.c
compiling MappedType.c
compiling MemoryPointer.c
compiling MethodHandle.c
compiling Platform.c
compiling Pointer.c
compiling Struct.c
compiling StructByReference.c
compiling StructByValue.c
compiling StructLayout.c
compiling Thread.c
compiling Type.c
compiling Types.c
compiling Variadic.c
compiling ffi.c
linking shared-object ffi_c.so

current directory: /home/ubuntu/***/shared/bundle/ruby/2.4.0/gems/ffi-1.9.23/ext/ffi_c
make "DESTDIR=" install
/usr/bin/install -m 0755 ffi_c.so ./.gem.20180429-5266-bkj7ii
Script is run as ubuntu. Please run as root
Makefile:187: recipe for target 'install-so' failed
make: *** [install-so] Error 1

make install failed, exit code 2

**Comment by larskanis** [comment]
```
/usr/bin/install -m 0755 ffi_c.so ./.gem.20180429-6005-6vwtxa
Script is run as ubuntu. Please run as root
```
There seems to be a special script in `/usr/bin/install`, that is not common and that needs to be called as root user. This is beyond the scope of Ruby-FFI, so I'm closing this.
