### ISSUE TITLE
Proc callback is being garbage collected

### ISSUE THREAD

**Issue by iesiyok** [ffi/ffi#629]
Hello,

I have been trying to send a nested struct to a C library which does some operations and returns the same struct to Ruby side as pointer. Say these are my struct in the Ruby side.

```
class G1_str < FFI::Struct
  layout :x,      :pointer,
             :prec, :pointer
end
class G2_str < FFI::Struct
  layout :x,      :pointer,
              :y,      :pointer,
             :prec, :pointer
end

class Group_str < FFI::Struct
  layout   :bytes_g1,     G1_str,
           :bytes_a1,     G1_st,
           :bytes_g2,     G2_str,
           :bytes_b2,      G2_str,
           :bytes_g,  :pointer,
           :bytes_o,  :pointer
end
```
And I create :x, :y or :prec as memory pointers as in the generic function below:

```
def to_memory_pointer(bytes, size)
 	g_s = FFI::MemoryPointer.new :pointer, size
 	ary = bytes.inject([]) do |a, str|
               fp = FFI::MemoryPointer.new :char, 256
               fp.put_string(0, str )
                a << fp
         end
    g_s.write_array_of_pointer(ary)
    return g_s
 end
```

Say I have those C functions which are one is just a callback and the other is nothing but a copy of one object to another.
```
typedef void completion_function(Group_str*& gpk);
int struct_copy(Group_str*& g1, Group_str_struct*& g2_ptr, completion_function *);
```
And the functions attached in Ruby as following:
```
callback :completion_function, [ :pointer ], :void
attach_function :struct_copy, [:pointer, :pointer, :completion_function ], :int
```

```
Callback = Proc.new do |ptr|
    obj = Group_str.new(ptr.read_pointer) 
    g1 = G1_struct.new(obj[:bytes_g1].to_ptr)
    j_g1  = bytes_to_g1(g1, 8, 256*24+1)#a method just creates json objects from result
   puts j_g1
  end
```
But since the ptr is garbage collected, it gives me result such as the following:

[", "o", "\x83", "\x97", "\xAB", "\xBF", "\xD3", "\xE7", "\xFB", "\x0F\x01\x93\xD2\xF8\a", "#\x01\x93\xD2\xF8\a",  "\xD7\x01\x93\xD2\xF8\a", "\xEB\x01\x93\xD2\xF8\a", "\xFF\x01\x93\xD2\xF8\a", "\x13\x02\x93\xD2\xF8\a", "'\x02\x93\xD2\xF8\a.....................................]

So the question is how can I avoid the garbage collector sweep my FFI::MemoryPointers? I don't have to use callbacks, I have just tried since it was mentioned that it can't be garbage collected if I use with Proc.new. 
By the way, if i try with disabling GC.disable in Ruby, it works perfectly fine, but it is not safe.

**Comment by larskanis** [comment]
Using a FFI::MemoryPointer or Proc object as a pointer parameter is not sufficient to protect it from being garbage collected. When you assign a pointer to a struct or as a function param, you have to *additionally* store the ruby object somewhere, where it isn't GC'ed. This is typically an instance variable, but could also be a constant or global variable, if only one such object is needed.

I wrote libusb for ruby. It has several such examples. Maybe this can be helpful: https://github.com/larskanis/libusb/blob/master/lib/libusb/transfer.rb#L189

**Comment by iesiyok** [comment]
Thank you very much for your quick answer,

I tried using AutoPointer now at least it is not GC'ed, then I put it in a class variable (@@ptr) but it still is GC'ed. However I believe this is now out of FFI's context.
