### ISSUE TITLE
Error installing  ffi -v 1.9.22

### ISSUE THREAD

**Issue by esaravanakumar89** [ffi/ffi#630]
This is the error  am getting while am trying to install ffi. 

current directory: /usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c
/usr/local/bin/ruby -r ./siteconf20180525-2757-15oex6y.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... no
checking for rb_thread_call_without_gvl()... no
creating extconf.h
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c

xt/ffi_c/libffi/src -Wall -fexceptions -c /usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c/libffi/src/closures.c  -fPIC -DPIC -o src/.libs/closures.o
/usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c/libffi/src/closures.c:498:14: error: previous declaration of â€˜vo* dlmalloc(size_t)â€™ with â€˜C++â€™ linkage
 static void *dlmalloc(size_t);
              ^
In file included from /usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c/libffi/src/closures.c:523:0:
/usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c/libffi/src/dlmalloc.c:691:22: error: conflicts with new declaration with â€˜Câ€™ linkage
 void* dlmalloc(size_t);
                      ^
/usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c/libffi/src/closures.c:499:13: error: previous declaration of â€˜vo dlfree(void*)â€™ with â€˜C++â€™ linkage
 static void dlfree(void*);
             ^
In file included from /usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c/libffi/src/closures.c:523:0:
/usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c/libffi/src/dlmalloc.c:700:19: error: conflicts with new declaration with â€˜Câ€™ linkage
 void  dlfree(void*);
                   ^
/usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c/libffi/src/closures.c:500:14: error: previous declaration of â€˜vo* dlcalloc(size_t, size_t)â€™ with â€˜C++â€™ linkage
 static void *dlcalloc(size_t, size_t) MAYBE_UNUSED;
              ^
In file included from /usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c/libffi/src/closures.c:523:0:
/usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.22/ext/ffi_c/libffi/src/dlmalloc.c:707:30: error: conflicts with new declaration with â€˜Câ€™ linkage
 void* dlcalloc(size_t, size_t);

**Comment by larskanis** [comment]
`checking for rb_thread_call_with_gvl()... no` means that there is some compiler or linker issue or ruby version mismatch, that is beyond the scope of FFI.
