### ISSUE TITLE
My process is dying with an Abort when I upgraded to 1.9.22 from 1.9.21.

### ISSUE THREAD

**Issue by ssether-usinternet** [ffi/ffi#634]
My ffi library upgaded to 1.9.22 (1.9.23 is the same story), and I now get an ABORT when the parent process closes itself instead of a normal exit with 0 return status.  This is happening when my Ruby process forks, and the parent process dies.  The child process is fine, but the parent, or parent(s) process is dying with an ABORT.  Returning to 1.9.21 resolves the problem.

This strace might provide more insight as to what's going on at a low level.  Ruby debug output didn't really provide anything useful.

clone(child_stack=0x7f302e234ff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f302e2359d0, tls=0x7f302e235700, child_tidptr=0x7f302e2359d0) = 16546
futex(0x1ff2f64, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1ff2f60, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x1ff2f30, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1ff2f98, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1ff2f9c, FUTEX_WAIT_PRIVATE, 1, NULL) = -1 EAGAIN (Resource temporarily unavailable)
write(6, "!", 1)                        = 1
futex(0x1ff2f30, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1ff2f60, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1ff2f64, FUTEX_WAIT_PRIVATE, 3, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1ff2f30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x53bdc54, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x53bdc50, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x1ff3694, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x1ff3708, FUTEX_WAKE_PRIVATE, 1) = 0
rt_sigaction(SIGINT, {SIG_IGN, [], SA_RESTORER, 0x7f303dd8d7e0}, {0x7f303e10b470, [], SA_RESTORER|SA_SIGINFO, 0x7f303dd8d7e0}, 8) = 0
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f303dd8d7e0}, {SIG_IGN, [], SA_RESTORER, 0x7f303dd8d7e0}, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
tgkill(16361, 16361, SIGABRT)           = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=16361, si_uid=0} ---
+++ killed by SIGABRT +++
Aborted

When I ran the same code on My Ubuntu box, it works fine and exits cleanly.  strace is a little different as follows:

futex(0x9f1f64, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x9f1f60, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x9f1f30, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0x9f1f98, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0x9f1f9c, FUTEX_WAIT_PRIVATE, 1, NULL) = -1 EAGAIN (Resource temporarily unavailable)
write(6, "!", 1)                        = 1
futex(0x9f1f30, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0x9f1f60, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0x9f1f64, FUTEX_WAIT_PRIVATE, 3, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x9f1f30, FUTEX_WAKE_PRIVATE, 1)  = 0
futex(0x54f14b4, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x54f14b0, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x54f1528, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x9f1f64, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x9f1f60, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x9f1f30, FUTEX_WAKE_PRIVATE, 1)  = 1
rt_sigaction(SIGINT, {SIG_IGN, [], SA_RESTORER, 0x7f109c1074b0}, {0x7f109c62b7b0, [], SA_RESTORER|SA_SIGINFO, 0x7f109c1074b0}, 8) = 0
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f109c1074b0}, {SIG_IGN, [], SA_RESTORER, 0x7f109c1074b0}, 8) = 0
close(4)                                = 0
close(6)                                = 0
munmap(0x7f1094677000, 1052672)         = 0
munmap(0x7f1094376000, 3149824)         = 0
exit_group(0)                           = ?
+++ exited with 0 +++

I'm not terribly familiar with ffi, or process management in general in Ruby since I'm coming at this is all handled by a higher level of abstraction in a framework we're using.  The short answer is this happens when my long-lived process daemonzes itself on startup.  I'm uncertain how exactly ffi fits into this, but it's required by my framework (adhearsion).

The Daemonizer code that forks can be found here:

https://github.com/adhearsion/adhearsion/blob/release/2.6.1/lib/adhearsion/foundation/custom_daemonizer.rb

This is happening on Centos 6.9

 Kernel: 2.6.32-696.23.1.el6.x86_64 #1 SMP Tue Mar 13 22:44:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Processor info from /proc is: 
model name	: Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz

**Comment by lamont-granquist** [comment]
probably dup of #621

**Comment by larskanis** [comment]
Is it solved with ffi-1.9.25?
