### ISSUE TITLE
Parsing string buffer using FFI

### ISSUE THREAD

**Issue by HoneyryderChuck** [ffi/ffi#641]
I'm using ffi to access the picohttpparser library, and I'm [falling in this error described here](https://github.com/h2o/picohttpparser/issues/43). Could someone please help me out?

Apologies if this is not the proper place for asking questions, but the google group seems dead.

**Comment by larskanis** [comment]
Answered [here](https://github.com/h2o/picohttpparser/issues/43#issuecomment-464339451)

**Comment by HoneyryderChuck** [comment]
Thx @larskanis
