### ISSUE TITLE
Compatibility with c++ smart pointers

### ISSUE THREAD

**Issue by iesiyok** [ffi/ffi#648]
I am wondering if it is possible to return a smart pointer from a C++ library to Ruby through FFI.
I know it works if I send its raw pointer, but that is not what I need, the library is a bit complex.

Thanks for your helps in advance,

**Comment by iesiyok** [comment]
Looks like it's working with unique pointers, I couldn't manage to make it run with shared pointers though. Still the unique pointer is helpful.

**Comment by larskanis** [comment]
FFI doesn't support C++ and we don't plan to add it anytime soon. C++ specifics needs to be wrapped behind a plain C interface. Alternatively ruby extensions can be used to bind to C++ APIs.
