### ISSUE TITLE
cannot load such file -- ffi_c (LoadError)

### ISSUE THREAD

**Issue by DJGamerLuna** [ffi/ffi#654]
C:\sphinx\ktane_voice>ruby charlie.rb
Traceback (most recent call last):
        8: from charlie.rb:2:in `<main>'
        7: from charlie.rb:2:in `require'
        6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
        5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `<top (required)>'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `require'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:3:in `<top (required)>'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `rescue in <top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `require': cannot load such file -- ffi_c (LoadError)

**Comment by maurosbu** [comment]
I have the same issue in CentOS 7.

LoadError: libffi.so.5: cannot open shared object file: No such file or directory - /path/to/app/shared/bundle/ruby/2.5.0/gems/ffi-1.9.25/lib/ffi_c.so

In CentOS 7 there is a /usr/lib64/libffi.so.6.  
/usr/lib64/libffi.so.5 doesn't exist.

**Comment by larskanis** [comment]
You need to update to a more recent ffi gem version.

**Comment by EvanCarroll** [comment]
#368

**Comment by dorianmariefr** [comment]
Addng `gem "ffi"` to my `Gemfile` fixed it https://stackoverflow.com/q/65000467/12544391
