### ISSUE TITLE
C++ function throwing exception terminates Ruby application

### ISSUE THREAD

**Issue by zippanto** [ffi/ffi#659]
I'm using FFI to load a closed source library and it's working fine. However I noticed that if I cause the C++ library to throw an exception, it completely terminates my Ruby application. Please see below for the output:

terminate called after throwing an instance of 'CamRetCode'
Aborted

CamRetCode is the exception type. I tried catching an exception in Ruby with the Exception type, but it's not catching anything the Ruby application just terminates.

Any advice or suggestions on how to catch the exception or make it not terminate the whole application?

**Comment by larskanis** [comment]
FFI doesn't support C++. That also means that it doesn't support C++ exceptions. You need to catch the exception in C++ before it reaches FFI.

**Comment by zippanto** [comment]
@larskanis Thanks. Because it's a closed library that isn't really an option. Would there be any other way? I could maybe wrap the library into another C++ library that handles the exceptions.. but that sounds so ugly.

**Comment by larskanis** [comment]
>  I could maybe wrap the library into another C++ library that handles the exceptions.. but that sounds so ugly.

That's the way to go. You have to wrap the C++ interface by a C interface. But note that exceptions are just one particular C++ language feature you have to wrap. There are polymorphic functions, virtual methods, inheritance and much more features, which are beyond C and are not handled by ffi. They all have to be mapped to a simple C API.

Another option is to write a ruby extension. Although the ruby extension API is a C API, it can be used in a C++ context.
