### ISSUE TITLE
face problem installing cosmos

### ISSUE THREAD

**Issue by refaat100** [ffi/ffi#679]
Hello ,
i'm trying to use cosmos for my phd degree but i face a problem with installation

at the step of          
  gem install cosmos --no-rdoc --no-ri

i have this error

&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
test@ubuntu:~$   gem install cosmos --no-rdoc --no-ri

Building native extensions.  This could take a while...
ERROR:  Error installing cosmos:
ERROR: Failed to build gem native extension.

    current directory: /home/test/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/qtbindings-4.8.6.5
/home/test/.rbenv/versions/2.4.2/bin/ruby -r ./siteconf20190215-2711-ymdcem.rb extconf.rb

current directory: /home/test/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/qtbindings-4.8.6.5
make "DESTDIR=" clean
mkdir ext/build
mkdir bin/2.4
mkdir bin/plugins
mkdir bin/plugins/accessible
mkdir bin/plugins/bearer
mkdir bin/plugins/codecs
mkdir bin/plugins/designer
mkdir bin/plugins/graphicssystems
mkdir bin/plugins/iconengines
mkdir bin/plugins/imageformats
mkdir bin/plugins/phonon_backend
mkdir bin/plugins/qmltooling
mkdir bin/plugins/sqldrivers
mkdir lib/2.4
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

**Comment by larskanis** [comment]
This is an issue about qtbindings. You should post it on their issue tracker. Sorry!
