### ISSUE TITLE
Uninitialized constant FFI::ConstGenerator

### ISSUE THREAD

**Issue by CodingAnarchy** [ffi/ffi#690]
`FFI::ConstGenerator` was not loading into the namespace with a `require 'ffi'`.  I had to do an explicit `require 'ffi/tools/const_generator'`.  This wasn't in the documentation anywhere, and it took me a while to even consider requiring the file from the structure in the gem itself to get around my issue, after failing to see anything else online.

My code is here: 
https://github.com/CodingAnarchy/activity_generator/blob/master/lib/linux_c_lib.rb

**Comment by larskanis** [comment]
Thanks for highlighting this!

I made some fixes and additions to the documentation of ffi-1.11.0. In addition I updated the corresponding wiki page: https://github.com/ffi/ffi/wiki/Automatic-Struct-Layout
