### ISSUE TITLE
How does one override library loading path?

### ISSUE THREAD

**Issue by igor-makarov** [ffi/ffi#714]
I have read the wiki on library loading.  

My question is, if one were to develop an FFI-based ruby gem, how would one expose to end users the ability to select a different library version to be loaded?

For example, [Typhoeus](https://github.com/typhoeus/typhoeus) uses `libcurl` and loads it from the system. How would one change this [load instruction](https://github.com/typhoeus/ethon/blob/de60a72552a1ae392705617a45477d93f0f51293/lib/ethon/curls/settings.rb#L7) to allow the end user to use non-system `libcurl`?

Thanks for your time.

**Comment by larskanis** [comment]
Sorry for the late response. You can either set the environment variable `LD_LIBRARY_PATH` to an alternative library directory or use absolute paths like [here in libusb](https://github.com/larskanis/libusb/blob/master/lib/libusb/call.rb#L26-L31).

**Comment by igor-makarov** [comment]
Thanks for responding! 💪🏻
