### ISSUE TITLE
gem install ffi -v '1.9.14' fails to compile

### ISSUE THREAD

**Issue by assafv** [ffi/ffi#716]
I`m using cygwin, not sure why this gem not compiling.

taken from /.gem/ruby/2.6.0/extensions/x86_64-cygwin/2.6.0/ffi-1.9.14/gem_make.out

/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: /home/assaf/.gem/ruby/2.6.0/gems/ffi-1.9.14/ext/ffi_c/libffi/src/prep_cif.c:174:(.text+0x2b6): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ffi_prep_closure_loc'
collect2: error: ld returned 1 exit status
make: *** [Makefile:263: ffi_c.so] Error 1

**Comment by larskanis** [comment]
ffi-1.9.14 is rather old. Could you please try a newer version?
