### ISSUE TITLE
Could not open library 'sodium': The specified module could not be found.

### ISSUE THREAD

**Issue by justinjameslee** [ffi/ffi#723]
`(LoadError)Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.11.1-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'sodium': The specified module could not be found.
.
Could not open library 'sodium.dll': The specified module could not be found.`

Hello, I'm unsure what to do to solve this issue and help would be greatly appreciated. 

Thank you!

**Comment by larskanis** [comment]
Did you try ```
ridk exec pacman -S mingw-w64-x86_64-libsodium
```
to install the required library?

In any way this is certainly an issue of the sodium gem, so you should check the issues there.

**Comment by justinjameslee** [comment]
I just tried it now, i got a bunch of errors.
```
warning: Public keyring not found; have you run 'pacman-key --init'?
error: mingw32: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" is unknown
error: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" could not be looked up remotely
error: mingw64: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" is unknown
error: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" could not be looked up remotely
error: msys: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" is unknown
error: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" could not be looked up remotely
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
```

**Comment by larskanis** [comment]
@justinjameslee I guess you're using rubyinstaller-devkit-2.5.x ? The bundled MSYS2 isn't properly initialized. Did you run `ridk install` as offered on the last installer page? That should do the trick.
