### ISSUE TITLE
-- Control frame information ---- error

### ISSUE THREAD

**Issue by ajays1991** [ffi/ffi#725]
Ruby version : 2.5.3 docker alpine
Rails: 6

I get the following backtrace

`You may have encountered a bug in the Ruby interpreter or extension libraries.
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html
2019-11-01 06:53:56,972 INFO exited: rails (terminated by SIGABRT (core dumped); not expected)
2019-11-01 06:53:57,975 INFO spawned: 'rails' with pid 22
2019-11-01 06:53:58,976 INFO success: rails entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Puma starting in single mode...
* Version 3.12.1 (ruby 2.5.5-p157), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: production
/usr/local/bundle/gems/ffi-1.11.1/lib/ffi/library.rb:112: [BUG] Illegal instruction at 0x00007f832577ffb5
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-musl]
-- Control frame information -----------------------------------------------
c:0065 p:---- s:0337 e:000336 CFUNC :open
c:0064 p:0022 s:0331 e:000330 BLOCK /usr/local/bundle/gems/ffi-1.11.1/lib/ffi/library.rb:112 [FINISH]
c:0063 p:---- s:0322 e:000321 CFUNC :each
c:0062 p:0112 s:0318 e:000317 BLOCK /usr/local/bundle/gems/ffi-1.11.1/lib/ffi/library.rb:109 [FINISH]
c:0061 p:---- s:0311 e:000310 CFUNC :map
c:0060 p:0069 s:0307 e:000306 METHOD /usr/local/bundle/gems/ffi-1.11.1/lib/ffi/library.rb:99
c:0059 p:0078 s:0300 e:000299 CLASS /usr/local/bundle/gems/sassc-2.2.1/lib/sassc/native.rb:11
c:0058 p:0007 s:0296 e:000295 CLASS /usr/local/bundle/gems/sassc-2.2.1/lib/sassc/native.rb:6
c:0057 p:0014 s:0293 e:000292 TOP /usr/local/bundle/gems/sassc-2.2.1/lib/sassc/native.rb:5 [FINISH]
c:0056 p:---- s:0290 e:000289 CFUNC :require_relative
c:0055 p:0021 s:0285 e:000284 TOP /usr/local/bundle/gems/sassc-2.2.1/lib/sassc.rb:31 [FINISH]
c:0054 p:---- s:0282 e:000281 CFUNC :require
c:0053 p:0013 s:0277 e:000276 TOP /usr/local/bundle/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5 [FINISH]
c:0052 p:---- s:0274 e:000273 CFUNC :require_relative
c:0051 p:0006 s:0269 e:000268 TOP /usr/local/bundle/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3 [FINISH]
c:0050 p:---- s:0266 e:000265 CFUNC :require
c:0049 p:0013 s:0261 e:000260 TOP /usr/local/bundle/gems/bootstrap-4.3.1/lib/bootstrap/engine.rb:4 [FINISH]
c:0048 p:---- s:0258 e:000257 CFUNC :require
c:0047 p:0006 s:0253 e:000252 METHOD /usr/local/bundle/gems/bootstrap-4.3.1/lib/bootstrap.rb:61
c:0046 p:0010 s:0249 e:000248 METHOD /usr/local/bundle/gems/bootstrap-4.3.1/lib/bootstrap.rb:11
c:0045 p:0032 s:0245 e:000244 TOP /usr/local/bundle/gems/bootstrap-4.3.1/lib/bootstrap.rb:75 [FINISH]
c:0044 p:---- s:0242 e:000241 CFUNC :require
c:0043 p:0033 s:0237 e:000236 BLOCK /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:81 [FINISH]
c:0042 p:---- s:0232 e:000231 CFUNC :each
c:0041 p:0050 s:0228 e:000227 BLOCK /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:76 [FINISH]
c:0040 p:---- s:0221 e:000220 CFUNC :each
c:0039 p:0030 s:0217 e:000216 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:65
c:0038 p:0015 s:0212 e:000211 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler.rb:114
c:0037 p:0099 s:0207 e:000206 TOP /app/config/application.rb:15 [FINISH]
c:0036 p:---- s:0204 e:000203 CFUNC :require_relative
c:0035 p:0006 s:0199 e:000198 TOP /app/config/environment.rb:2 [FINISH]
c:0034 p:---- s:0196 e:000195 CFUNC :require_relative
c:0033 p:0007 s:0191 e:000190 BLOCK config.ru:3 [FINISH]
c:0032 p:---- s:0188 e:000187 CFUNC :instance_eval
c:0031 p:0034 s:0184 e:000183 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:55 [FINISH]
c:0030 p:---- s:0178 e:000177 CFUNC :new
c:0029 p:0013 s:0174 e:000173 EVAL [FINISH]
c:0028 p:---- s:0171 e:000170 CFUNC :eval
c:0027 p:0030 s:0163 e:000162 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49
c:0026 p:0090 s:0157 e:000156 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:40
c:0025 p:0053 s:0148 e:000147 METHOD /usr/local/bundle/gems/puma-3.12.1/lib/puma/configuration.rb:320
c:0024 p:0017 s:0141 e:000140 METHOD /usr/local/bundle/gems/puma-3.12.1/lib/puma/configuration.rb:245
c:0023 p:0033 s:0134 e:000133 METHOD /usr/local/bundle/gems/puma-3.12.1/lib/puma/runner.rb:147
c:0022 p:0159 s:0129 e:000128 METHOD /usr/local/bundle/gems/puma-3.12.1/lib/puma/single.rb:98
c:0021 p:0119 s:0122 e:000121 METHOD /usr/local/bundle/gems/puma-3.12.1/lib/puma/launcher.rb:186
c:0020 p:0006 s:0115 e:000114 METHOD /usr/local/bundle/gems/puma-3.12.1/lib/puma/cli.rb:80
c:0019 p:0033 s:0111 e:000110 TOP /usr/local/bundle/gems/puma-3.12.1/bin/puma:10 [FINISH]
c:0018 p:---- s:0107 e:000106 CFUNC :load
c:0017 p:0109 s:0102 e:000101 TOP /usr/local/bundle/bin/puma:23 [FINISH]
c:0016 p:---- s:0097 e:000096 CFUNC :load
c:0015 p:0128 s:0092 e:000091 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74
c:0014 p:0075 s:0083 e:000082 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28
c:0013 p:0026 s:0078 e:000077 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:465
c:0012 p:0064 s:0073 e:000072 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27
c:0011 p:0047 s:0065 e:000064 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126
c:0010 p:0261 s:0058 e:000057 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387
c:0009 p:0010 s:0045 e:000044 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27
c:0008 p:0064 s:0040 e:000039 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466
c:0007 p:0010 s:0033 e:000032 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18
c:0006 p:0079 s:0027 e:000026 BLOCK /usr/local/bundle/gems/bundler-2.0.2/exe/bundle:30
c:0005 p:0002 s:0021 e:000020 METHOD /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124
c:0004 p:0046 s:0016 E:000ac0 TOP /usr/local/bundle/gems/bundler-2.0.2/exe/bundle:22 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC :load
c:0002 p:0109 s:0008 E:0006f0 EVAL /usr/local/bundle/bin/bundle:23 [FINISH]
c:0001 p:0000 s:0003 E:000360 (none) [FINISH]
-- Ruby level backtrace information ----------------------------------------
/usr/local/bundle/bin/bundle:23:in `<main>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/bundle/bin/puma:23:in `<top (required)>'
/usr/local/bundle/bin/puma:23:in `load'
/usr/local/bundle/gems/puma-3.12.1/bin/puma:10:in `<top (required)>'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/cli.rb:80:in `run'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/launcher.rb:186:in `run'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/single.rb:98:in `run'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/runner.rb:147:in `load_and_bind'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/configuration.rb:245:in `app'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/configuration.rb:320:in `load_rackup'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
config.ru:0:in `<main>'
config.ru:0:in `new'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'`

**Comment by larskanis** [comment]
There's a loading issue with `libsass.so` or some of it's dependencies. Please check the issues on https://github.com/sass/sassc-ruby - it's very sure not ffi's fault.

**Comment by dzivalli** [comment]
@ajays1991 got the same, did you find a workaround?

**Comment by ajays1991** [comment]
I found out that this issue was coming from sassc 2.2.0  library which is dependency of bootstrap gem in ruby. sassc gem is hitiing some bug in ruby. As @larskanis mentioned its not ffi fault. That issue with ruby is still open, so i managed to add bootstrap manually without any gem and worked for me.

**Comment by jywarren** [comment]
Similar to https://github.com/ffi/ffi/issues/739, fwiw, and also like this error: https://github.com/sass/sassc-ruby/issues/146#issuecomment-527103083
