### ISSUE TITLE
mailing list

### ISSUE THREAD

**Issue by bsammon** [ffi/ffi#731]
Is there still a mailing list?
I tried going to the google group linked in the Wiki and google says it doesn't exist, or it's private.
I'd like to update the wiki if it's no longer accurate or lacking details.

**Comment by larskanis** [comment]
The google group at http://groups.google.com/group/ruby-ffi should still be alive. Everyone can join the group and can post messages then. Messages of new members are moderated. I'm just a simple member there and can not approve messages nor change any settings. However @headius and @enebo are managers - just in case there is something wrong with the list.

**Comment by bsammon** [comment]
So, when I follow that link, it looks very much like the group doesn't exist.  (You can reproduce this, right?  It may be necessary to log out of google/delete all your cookies)
This raises a few questions:
1) Do you really want this group to be private?  Its really unusual for an open-source project to have a private mailing list.  (Unless it's a planning-committee list for a large project like linux-kernel/apache/MRI)
2) If it's going to be private, shouldn't the wiki mention that?  It's rather confusing to newcomers the    way it is.
3) {Can I| Would you like me to} update the wiki myself?

**Comment by headius** [comment]
Sorry about that, I created the group and did not notice it wasn't public.

I've modified the settings so it's visible for everyone now.

@larskanis I can add you as an admin for the group, if you like. Let me know your Google account.

**Comment by larskanis** [comment]
@headius This is larskanis@gmail.com

**Comment by headius** [comment]
@larskanis I have added you as an Owner.
