### ISSUE TITLE
Disallow re-layout of existing Struct

### ISSUE THREAD

**Issue by headius** [ffi/ffi#734]
I ran into this while attempting to align all Ruby code in JRuby and the FFI gem.

Currently, it is possible to define a struct and change its layout repeatedly:

```ruby
class PairLayout < FFI::Struct
  layout :a, :int, :b, :long_long
end
class PairLayout < FFI::Struct
  layout :a, :int, 0, :b, :long_long, 4 # allowed
end
```

However, this seems like not only an odd feature, but a bad/dangerous one. When the layout has been used for any existing objects, changing it will produce very difficult-to-diagnose bugs (at least) or potentially memory violations if the layout is re-retrieved from the class and used for previous pointers.

At some point, it appears this was disallowed but the error was [commented out](bd5cf88787d4cd53b17a77cec66ae20824c2ef1e) for some reason: https://github.com/ffi/ffi/blob/master/lib/ffi/struct.rb#L207

This behavior caused a failure on JRuby running struct_spec.rb, because two specs there open the same `PairLayout` struct and call layout each time. JRuby's implementation of FFI expects that after the first struct has been allocated the layout will not be changed again, and caches it to avoid repeatedly looking up the instance variable. This caching resulted in the first spec's layout being used for the second, causing it to fail.

I believe we should reinstate the error. I cannot think of any good reasons why you would want to re-layout a struct after you have already started creating instances of it, and many good reasons why doing so would be a bad idea.

For now, I have removed the caching in JRuby, but I'd like to revert that (and the C FFI could potentially start caching the layout then as well): https://github.com/jruby/jruby/pull/5948/commits/21a8a8cc9d36b1d15e82cbec1015a50aea7d9137

**Comment by headius** [comment]
At the very least, I believe we should consider the behavior "undefined" and modify the specs to not re-layout the same struct class. I would prefer to have a hard error, since there's really no good reason to modify a struct's layout after it is already in flight.

**Comment by larskanis** [comment]
I fully agree. The `raise` is just disable because the tests depend heavily on it. I'll enable the `raise` and fix the tests today.

**Comment by larskanis** [comment]
OK, I pushed the changes here: https://github.com/ffi/ffi/pull/735/files?w=1

**Comment by larskanis** [comment]
Given that we had a lot of such redefinitions in our tests and the benchmarks, I'm somewhat hesitated to release #735 as ffi-1.12.0. But on the other hand it isn't really worth a ffi-2.0.0 release. Maybe we should only warn about a struct layout redefinition?

**Comment by headius** [comment]
I would be fine with a deprecation warning indicating that this is unspecified behavior that will be prohibited in the future. Thanks for the quick response! I will import the updated tests.

**Comment by eregon** [comment]
The change looks good to me. If it's only FFI tests/benchs then I think it's fine to go hard error. It would be good to maybe check a couple key gems using FFI to make sure they don't rely on that behavior.

**Comment by larskanis** [comment]
@eregon I just checked the [reverse dependencies of ffi](https://rubygems.org/gems/ffi/reverse_dependencies) and it shows 816 gems. That's why I want to change it to a warning.
