### ISSUE TITLE
How to get C library's stack trace?

### ISSUE THREAD

**Issue by p-mongo** [ffi/ffi#737]
I am experiencing an intermittent segfault in a C library called via ffi.  A sample failure looks like this: https://gist.github.com/p-mongo/fb510f1585a078c1f25f28087dc568a1

The only stack trace appears to be as follows:

<pre>

-- Control frame information -----------------------------------------------
c:0075 p:---- s:0400 e:000399 CFUNC  :mongocrypt_ctx_datakey_init
c:0074 p:0020 s:0395 e:000394 BLOCK  /home/w/apps/ruby-driver/lib/mongo/crypt/binding.rb:230
c:0073 p:0008 s:0392 e:000391 METHOD /home/w/apps/ruby-driver/lib/mongo/crypt/binding.rb:507
c:0072 p:0007 s:0385 e:000384 METHOD /home/w/apps/ruby-driver/lib/mongo/crypt/binding.rb:228
c:0071 p:0032 s:0380 e:000379 METHOD /home/w/apps/ruby-driver/lib/mongo/crypt/data_key_context.rb:40 [FINISH]
c:0070 p:---- s:0375 e:000374 CFUNC  :new
c:0069 p:0015 s:0370 e:000369 METHOD /home/w/apps/ruby-driver/lib/mongo/client_encryption.rb:46
c:0068 p:0028 s:0364 e:000363 BLOCK  /home/w/apps/ruby-driver/spec/integration/explicit_encryption_spec.rb:25 [FINISH]
c:0067 p:---- s:0357 e:000356 CFUNC :instance_exec
</pre>

As far as I can tell the C library in question has symbols in it: https://gist.github.com/p-mongo/7224c6e8368f53e29f2df969e2864c0a

How do I get those symbols in the segfault report please?

**Comment by larskanis** [comment]
Run you ruby process with valgrind. It usually prints the most valuable information to diagnose C segfaults.

**Comment by p-mongo** [comment]
Thanks for the pointer, can you recommend a resource to read about how valgrind works with ruby? When I run `valgrind rspec ...` I never get the segfault and it seems that maybe some of the arguments don't make it to my spec run.

With that said, I believe the question is still valid: based on valgrind stating that it runs code in a virtual machine, our CI runs for example wouldn't use it by default on all configurations, but I would still like to get full stack traces when C libraries called by ffi segfault.

**Comment by larskanis** [comment]
You can also use `gdb --args rspec ...` and print the backtrace. It doesn't use binary code transformation like valigrind. But be careful to actually start the ruby executable with valgrind / gdb! Either kind of `valgrind ruby -S rspec` or `valgrind --trace-children=yes rspec` .

> I would still like to get full stack traces when C libraries called by ffi segfault.

I always get a C level stack trace on Ubuntu with ruby installed per rvm. Possibly rbenv uses some other install options, so that they aren't printed.

**Comment by p-mongo** [comment]
I've done some tests in https://github.com/p-mongo/tests/tree/master/ruby-ext-stack-trace, and for example https://github.com/p-mongo/tests/blob/master/ruby-ext-stack-trace/output-ffi-2.7.log has this section:

<pre>
-- C level backtrace information -------------------------------------------
/home/me/.rbenv/versions/2.7.0/lib/libruby.so.2.7(rb_vm_bugreport+0x555) [0x7f10d7994135] vm_dump.c:755
[0x7f10d77d33c7]
/home/me/.rbenv/versions/2.7.0/lib/libruby.so.2.7(sigsegv+0x4b) [0x7f10d78ffc6b] signal.c:946
/lib/x86_64-linux-gnu/libpthread.so.0(__restore_rt+0x0) [0x7f10d74c1730]
/lib/x86_64-linux-gnu/libc.so.6(0x7f10d713a124) [0x7f10d713a124]
shlib/lib.so(foo+0x23) [0x7f10d3ac8138] lib.c:6
shlib/lib.so(foo) (null):0
/usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f10d3aa98ee]
/usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f10d3aa92bf]
</pre>

... which is the information I was looking for.

This output appears to be conditioned on `HAVE_BACKTRACE` being defined when building Ruby, which I'm assuming somehow is missing in our CI builds that produced the output in the original issue description.

In any event my issue appears to not have anything to do with FFI. Thanks again for the help.
