### ISSUE TITLE
SegFault when a AutoPointer is manually released

### ISSUE THREAD

**Issue by Adithya-copart** [ffi/ffi#741]
Encountered a  Segmentation Fault when a AutoPointer object was manually free'd using the FFI function used in the release strategy during initialize.

The function `rd_kafka_destroy` is used while [initializing](https://github.com/appsignal/rdkafka-ruby/blob/d0d71f669daadbfeec056085b8abe065478be784/lib/rdkafka/config.rb#L215-L218) a `AutoPointer`. Calling this method manually on this object results in a SegFault as seen [here](https://travis-ci.org/appsignal/rdkafka-ruby/jobs/642460992?utm_medium=notification&utm_source=github_status) after the object is GC'd and the finalizer is called.

Also, encountered a Segmentation fault when I tried to reproduce this by calling free on the pointer in Ruby. This happened in JRuby as well.

```
$ irb -r ffi --noprompt
ptr1 = FFI::MemoryPointer.new(10).tap {|p| p.write_string 'test'}
#<FFI::MemoryPointer address=0x00007fd7d795f010 size=10>

ap1 = FFI::AutoPointer.new(ptr1.read_pointer, proc {ptr1.method(:free)})
#<FFI::AutoPointer address=0x0000000074736574>

ptr1.free
#<FFI::MemoryPointer address=0x00007fd7d795f010 size=10>

ap1.free
nil

ap1.read_pointer
(irb):5: [BUG] Segmentation fault at 0x0000000074736574
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
```

**Comment by larskanis** [comment]
This is expected behavior. A read-after-free either delivers garbage or segfaults. We don't have a safety check for this use case so far, but it's neither expected nor intended to protect for any segfaults that could happen.
