### ISSUE TITLE
ffi 1.12.2 did not push its -java variant

### ISSUE THREAD

**Issue by kares** [ffi/ffi#743]
could you someone please make sure a build using JRuby is also pushed?
https://github.com/ffi/ffi/commit/ad524cb016fc788861d76e43a5067b8d441a76bc // cc @larskanis 

otherwise this is (potentially) breaking JRuby `bundle` install with the ffi as a dependency.

**Comment by dfighter1985** [comment]
Could this be the same reason why I am getting this?

> 14:14:05  [INFO] Building native extensions.  This could take a while...
> 14:14:06  [WARNING] ERROR:  Error installing /home/jenkins/.m2/repository/rubygems/ffi/1.12.2/ffi-1.12.2.gem:
> 14:14:06  [INFO] 8 gems installed
> 14:14:06  [WARNING]     ERROR: Failed to build gem native extension.
> 14:14:06  [WARNING] 
> 14:14:06  [WARNING]     current directory: /home/jenkins/workspace/ce_5.5_OSZK_branches_sworvd2-kds/dspace/modules/xmlui-mirage2/target/rubygems/gems/ffi-1.12.2/ext/ffi_c
> 14:14:06  [WARNING] /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp :/home/jenkins/workspace/ce_5.5_OSZK_branches_sworvd2-kds/dspace/modules/xmlui-mirage2/target/test-classes:/home/jenkins/workspace/ce_5.5_OSZK_branches_sworvd2-kds/dspace/modules/xmlui-mirage2/target/classes org.jruby.Main -r ./siteconf20200203-365-no79qr.rb extconf.rb
> 14:14:06  [WARNING] Error: Could not find or load main class org.jruby.Main
> 14:14:06  [WARNING] 
> 14:14:06  [WARNING] extconf failed, exit code 1

**Comment by larskanis** [comment]
Sorry, I forgot!
