### ISSUE TITLE
unknown type name ‘caddr_t’

### ISSUE THREAD

**Issue by cbay** [ffi/ffi#744]
On my system (Debian 8):

```
~/.gem/ruby/2.6.0/gems/ffi-1.12.2/ext/ffi_c$ gcc -I. -I/usr/alwaysdata/ruby/2.6.2/include/ruby-2.6.0/x86_64-linux -I/usr/alwaysdata/ruby/2.6.2/include/ruby-2.6.0/ruby/backward -I/usr/alwaysdata/ruby/2.6.2/include/ruby-2.6.0 -I.  -DRUBY_EXTCONF_H=\"extconf.h\" -D_FORTIFY_SOURCE=2   -fPIC -std=c99   -o ClosurePool.o -c ClosurePool.c
ClosurePool.c: In function ‘rbffi_Closure_Alloc’:
ClosurePool.c:145:5: error: unknown type name ‘caddr_t’
     caddr_t code = NULL;
     ^
```

Apparently, [caddr_t](https://stackoverflow.com/questions/6381526/what-is-the-significance-of-caddr-t-and-when-is-it-used) shouldn't be used, and I don't see it defined anywhere, except for WIN32, in that same file:

```
#ifdef _WIN32
  typedef char* caddr_t;
#endif
```

Where is it supposed to be defined for non-WIN32 systems? One could think of `sys/types.h`, but it's not supposed to be, at least [according to the man page](http://man7.org/linux/man-pages/man0/sys_types.h.0p.html).

Note that compiling without `-std=c99` works fine, supposedly because it automatically defines `caddr_t` in C89. But I didn't ask for C99, except that my Ruby interpreter was compiled with it, and I suppose ffi got it from here.

**Comment by larskanis** [comment]
Thanks for pointing this out!
