### ISSUE TITLE
Fail to find Xcode

### ISSUE THREAD

**Issue by Ethenyl** [ffi/ffi#748]
## Issue

I'm currently using the version `1.9.0` of **CocoaPods** (an iOS/macOS dependency manager) and lately a dependency to `ffi` has been added.

Unfortunately, whenever I'm trying to install the latest version of **CP**, I'm faced with the issue that it can't find the **Xcode** installation.

Judging from the log, it seems that the right path is found using `xcode-select` BUT I'm currently using multiple versions of **Xcode**, so the path of my currently selected version of **Xcode** contains spaces.

A quick fix would be to wrap the path toward the **Xcode** binary with double quotes.

## Information

Detected version: 1.12.2
OS: MacOS 10.15.4
Ruby: 2.7.0

## Logs

```
3-nvp9ns.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_call_without_gvl()... yes
checking for ruby_native_thread_p()... yes
checking for ruby_thread_has_gvl_p()... yes
creating extconf.h
creating Makefile

current directory: /Users/XXX/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/ext/ffi_c
make "DESTDIR=" clean

current directory: /Users/XXX/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/ext/ffi_c
make "DESTDIR="
Configuring libffi
clang: error: unsupported option '-print-multi-os-directory'
clang: error: no input files
cd "/Users/XXX/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19" && /Applications/Xcode 11.3.1.app/Contents/Developer/usr/bin/make
/bin/sh: /Applications/Xcode: No such file or directory
make: *** ["/Users/XXX/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19"/.libs/libffi_convenience.a] Error 127

make failed, exit code 2
```

**Comment by larskanis** [comment]
The path `/Applications/Xcode 11.3.1.app` includes a space character. This is not compatible to many build scripts. Did you set this path intentionally? Can you change it?

**Comment by Ethenyl** [comment]
Hi @larskanis,

Thanks a lot for your swift answer.

That's exactly the issue here, the thing is, I'm working on multiple projects, some are "legacy" (which run with old version of Xcode) projects and some are using the latest version.

By default, any developer willing to start using Xcode will use the App Store to download it, which enforces a single version on your Mac, aptly named `Xcode.app`.

But for my specific need, I'm installing multiple versions named after the actual version, like `Xcode 11.3.1`.

I do understand that it breaks your build script but it's the first time I'm faced with an issue with it (and I've been using gems for a long time, CocoaPods is quite old and very popular among Apple developers).

So I'm wondering if it's something that can be "fixed" in `ffi` ? If you think it's not up to `ffi` to handle the fix, I'll change the way I'm using my Xcode installations, but I'm not the only one use this workflow so it might arise again.

**Comment by larskanis** [comment]
Another alternative is to install ffi.gem with libffi as a system library. You need to install libffi with your package manager first. It will be preferred over bundled libffi. See also here: https://github.com/ffi/ffi#requirements

Not sure I'll spend time on this - Nokogiri similar doesn't install in a path with spaces: https://github.com/sparklemotion/nokogiri/issues/1891 But sure patches are welcome!

**Comment by Ethenyl** [comment]
Good point, I've resorted to rename my latest Xcode instance as `Xcode.app`, I'll keep older version with their respective names.

This will allow my machine to match the CI and some of my co-workers that aren't working on the same legacy projects as me.

Thanks a lot for taking some of your time to answer ;-)
