### ISSUE TITLE
Failure to build on macOS when path to Xcode contains a space

### ISSUE THREAD

**Issue by amorde** [ffi/ffi#750]
`make` exists within Xcode's bundle, and users can rename their `Xcode.app` to anything they want. I often have multiple versions of Xcode on my machine, and will rename them to something like `Xcode 11.2` to specify which version it is.

This causes the gem to fail to build with the following error:

```
cd "/Users/eamorde/.rvm/gems/ruby-2.6.1/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19" && /Applications/Xcode 11.2.app/Contents/Developer/usr/bin/make
/bin/sh: /Applications/Xcode: No such file or directory
```

Looks like the place this is failing is here:

https://github.com/ffi/ffi/blob/143c72f020f2c59b4ea7869818d753769ed78d42/ext/ffi_c/libffi.darwin.mk#L42

**Comment by amorde** [comment]
This line would likely have a similar issue:

https://github.com/ffi/ffi/blob/143c72f020f2c59b4ea7869818d753769ed78d42/ext/ffi_c/libffi.darwin.mk#L61

**Comment by larskanis** [comment]
Dupe of #748

**Comment by amorde** [comment]
Ah okay - I'll close since the discussion on that issue makes it sound like something that can't be resolved
