### ISSUE TITLE
Should we move the CI to GitHub Actions?

### ISSUE THREAD

**Issue by eregon** [ffi/ffi#760]
TravisCI seems really slow, it often takes >10min to even start the first jobs on PRs (e.g. https://github.com/ffi/ffi/pull/759).

Thoughts?

**Comment by eregon** [comment]
Seems it's partially due to multiple outages on TravisCI today:
![Screenshot from 2020-03-28 00-32-01](https://user-images.githubusercontent.com/168854/77808447-a1784400-708b-11ea-9753-c22175daafb4.png)
https://www.traviscistatus.com/

**Comment by eregon** [comment]
TravisCI doesn't even have the latest Ruby versions, one more reason to migrate:
https://travis-ci.org/github/ffi/ffi/builds/668043308

**Comment by eregon** [comment]
I got started on this and 2.3-2.7 + ruby-head + truffleruby-head pass on Linux and macOS:
https://github.com/eregon/ffi/runs/543197119?check_suite_focus=true

**Comment by eregon** [comment]
I've got Windows working too in GitHub Actions: https://github.com/eregon/ffi/runs/543263163?check_suite_focus=true
I'll make a PR.

**Comment by eregon** [comment]
GitHub Actions from https://github.com/ffi/ffi/pull/762 seems to work well, e.g., https://github.com/ffi/ffi/actions/runs/66243725

I'll make a PR to propose to remove redundant jobs in TravisCI & AppVeyor.

@larskanis Do we want to test with both CC=gcc and C=clang on Linux/macOS like TravisCI did?
I think testing with the default compiler for each platform already covers the most common & important cases.
Also I guess CC=gcc on macOS has no effect.
And I think on no major Linux distribution clang is the default compiler.

**Comment by larskanis** [comment]
> I think testing with the default compiler for each platform already covers the most common & important cases.

I have the same opinion.

**Comment by larskanis** [comment]
@eregon Thanks for doing this! Github Actions seem to work pretty well.

However Travis-CI (and Appveyor) did a good job for a decade by now. So I wouldn't [delete the jobs](https://github.com/ffi/ffi/pull/764) immediately. We can do this when Github Actions worked well with FFI for a while or when we're tired to update Travis.
