### ISSUE TITLE
Fail install in macOs sierra 10.12.6 When install [compass], please help...

### ISSUE THREAD

**Issue by whoooami** [ffi/ffi#767]
gem install compass is failing for me:

`

> NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
> Gem::Specification#rubyforge_project= called from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/specifications/nokogiri-1.5.6.gemspec:22.
> NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
> Gem::Specification#rubyforge_project= called from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/specifications/nokogiri-1.5.6.gemspec:22.
> ERROR:  Error installing compass:
>         ERROR: Failed to build gem native extension.
> 
>     current directory: /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/ext/ffi_c
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -I /Library/Ruby/Site/2.3.0 -r ./siteconf20200408-79669-1ixivq3.rb extconf.rb
> checking for ffi.h... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
>         --with-opt-dir
>         --without-opt-dir
>         --with-opt-include
>         --without-opt-include=${opt-dir}/include
>         --with-opt-lib
>         --without-opt-lib=${opt-dir}/lib
>         --with-make-prog
>         --without-make-prog
>         --srcdir=.
>         --curdir
>         --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
>         --with-ffi_c-dir
>         --without-ffi_c-dir
>         --with-ffi_c-include
>         --without-ffi_c-include=${ffi_c-dir}/include
>         --with-ffi_c-lib
>         --without-ffi_c-lib=${ffi_c-dir}/lib
>         --enable-system-libffi
>         --disable-system-libffi
>         --with-libffi-config
>         --without-libffi-config
>         --with-pkg-config
>         --without-pkg-config
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `block in try_compile'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:524:in `with_werror'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
>         from extconf.rb:10:in `system_libffi_usable?'
>         from extconf.rb:34:in `<main>'
> 
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
>   /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-16/2.3.0/ffi-1.12.2/mkmf.log
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2 for inspection.
> Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-16/2.3.0/ffi-1.12.2/gem_make.out
> ➜  dotink-index git:(master) ✗ sudo gem install compass > 0.1

`

/Library/Ruby/Gems/2.3.0/extensions/universal-darwin-16/2.3.0/ffi-1.12.2/gem_make.out
`

> package configuration for libffi is not found
> "xcrun clang -o conftest -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin16 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS -iwithsysroot /usr/local/libressl/include conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib -L.             -L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/local/libressl/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/local/lib   -arch x86_64 -arch i386   -lruby.2.3.0  -lpthread -ldl -lobjc "
> In file included from conftest.c:1:
> In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
> #include "ruby/config.h"
>          ^~~~~~~~~~~~~~~
> 1 error generated.
> checked program was:
> /* begin */
> 1: #include "ruby.h"
> 2: 
> 3: int main(int argc, char **argv)
> 4: {
> 5:   return 0;
> 6: }
> /* end */

`

$ sudo xcode-select -p
/Applications/Xcode.app/Contents/Developer

$ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin16]

$ gem --version
2.7.6

$ gcc --version
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/specifications/nokogiri-1.5.6.gemspec:22.
3.1.2

$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
I do have libffi but i installed through brew, but still doesn't work anymore.

**Comment by Schnodderbalken** [comment]
Hey, I am having the same problem. Yet, I reported it here https://github.com/rubygems/rubygems/issues/3628
I have a faint idea it might be connected to MacOS having removed some paths in recent OS versions. However I thought that it was solved by this :https://github.com/ffi/ffi/pull/765. It seems, however, that it's not.

Do you have any progress on this?

**Comment by whoooami** [comment]
Sorry, not yet. I tried a lot, but still no solution. I am currently working on another project, so I have not tracked this issue for the time being.

**Comment by larskanis** [comment]
`fatal error: 'ruby/config.h' file not found` indicates that there's some issue in your ruby environment, beyond the scope of this project. Beside this ruby-2.3 is outdated and no longer supported. I'll close this issue therefore. Sorry!
