### ISSUE TITLE
RuntimeError: ?gFK???V 	from /usr/lib/ruby/gems/1.8/gems/ffi-1.0.6/lib/ffi/library.rb:149:in `attach' 

### ISSUE THREAD

**Issue by gabetax** [ffi/ffi#77]
On Gentoo with the "hardened" profile (gcc with pie+ssp, grsecurity kernel), attempts to run the demo fail with a RunTime error.  The process does not get signal 11'd (which is the typical response to a pie+ssp or pax violation), and grsecurity makes no mentions in the syslog.

$ irb
irb(main):001:0>   require 'ffi'
=> true
irb(main):002:0> 
irb(main):003:0\*   module MyLib
irb(main):004:1>     extend FFI::Library
irb(main):005:1>     ffi_lib 'c'
irb(main):006:1>     attach_function :puts, [ :string ], :int
irb(main):007:1>   end
RuntimeError: ?gFK???V
    from /usr/lib/ruby/gems/1.8/gems/ffi-1.0.6/lib/ffi/library.rb:149:in `attach'
    from /usr/lib/ruby/gems/1.8/gems/ffi-1.0.6/lib/ffi/library.rb:149:in`attach_function'
    from (irb):6
irb(main):008:0> 
irb(main):009:0\*   MyLib.puts 'Hello boys using libc!'
NoMethodError: private method `puts' called for MyLib:Module
    from (irb):9
irb(main):010:0> quit
$ uname -a
Linux proto 2.6.32-hardened-r9 #1 SMP PREEMPT Thu Aug 19 09:32:37 CDT 2010 i686 Intel(R) Xeon(TM) CPU 3.00GHz GenuineIntel GNU/Linux
$ ruby -v

ruby 1.8.7 (2010-08-16 patchlevel 302) [i686-linux]
$ gem list ffi

**\* LOCAL GEMS ***

ffi (1.0.6)
$ emerge --info
# Portage 2.1.8.3 (hardened/linux/x86, gcc-4.4.4, glibc-2.11.2-r3, 2.6.32-hardened-r9 i686)

System uname: Linux-2.6.32-hardened-r9-i686-Intel-R-_Xeon-TM-_CPU_3.00GHz-with-gentoo-1.12.14
Timestamp of tree: Wed, 02 Mar 2011 05:45:01 +0000
app-shells/bash:     4.1_p7
dev-lang/python:     2.4.6, 2.6.5-r3, 3.1.2-r4
dev-util/cmake:      2.8.1-r2
sys-apps/baselayout: 1.12.14-r1
sys-apps/sandbox:    2.3-r1
sys-devel/autoconf:  2.13, 2.65-r1
sys-devel/automake:  1.11.1
sys-devel/binutils:  2.20.1-r1
sys-devel/gcc:       4.4.4-r2
sys-devel/gcc-config: 1.4.1
sys-devel/libtool:   2.2.10
sys-devel/make:      3.81-r2
virtual/os-headers:  2.6.30-r1
ACCEPT_KEYWORDS="x86"
ACCEPT_LICENSE="\* -@EULA"
CBUILD="i686-pc-linux-gnu"
CFLAGS="-march=pentium4 -pipe -O2"
CHOST="i686-pc-linux-gnu"
CONFIG_PROTECT="/etc /var/bind /var/qmail/alias /var/qmail/control"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/php/apache2-php5.2/ext-active/ /etc/php/apache2-php5/ext-active/ /etc/php/cgi-php5.2/ext-active/ /etc/php/cgi-php5/ext-active/ /etc/php/cli-php5.2/ext-active/ /etc/php/cli-php5/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=pentium4 -pipe -O2"
DISTDIR="/usr/portage/distfiles"
FEATURES="assume-digests distlocks fixpackages news parallel-fetch protect-owned sandbox sfperms strict unmerge-logs unmerge-orphans userfetch"
GENTOO_MIRRORS="http://gentoo.osuosl.org/ http://distro.ibiblio.org/pub/linux/distributions/gentoo/ http://ftp.ucsb.edu/pub/mirrors/linux/gentoo/ http://gentoo.chem.wisc.edu/gentoo/"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j5"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --compress --force --whole-file --delete --stats --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
PORTDIR="/usr/portage"
PORTDIR_OVERLAY="/usr/local/portage"
SYNC="rsync://rsync.us.gentoo.org/gentoo-portage"
USE="acl apache2 bash-completion bzip2 chroot cli cracklib crypt ctype curl cxx dri examples expat gd gpm hardened hpn iconv jpeg json modules mssql mudflap multiuser munin-apache mysql mysqli ncurses nls nptl nptlonly openmp pam pcre perl pic png posix pppd python readline reflection ruby sendfile session sftplogging simplexml soap spl ssh ssl subversion symlink sysfs tcpd threads tokenizer truetype unicode urandom utf8 vchroot vhosts x86 xml xorg zlib" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1  emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m   maestro3 trident usb-audio via82xx via82xx-modem ymfpci" ALSA_PCM_PLUGINS="adpcm alaw asym copy dmix dshare dsnoop empty extplug file hooks iec958 ioplug ladspa lfloat linear meter mmap_emul mulaw multi null plug rate route share shm softvol" APACHE2_MODULES="actions alias auth_basic auth_digest authn_dbd authn_default authn_file authz_default authz_groupfile authz_host authz_user autoindex cgi cgid dav dav_fs dav_lock dbd deflate dir env expires filter headers include info log_config logio mime mime_magic negotiation proxy proxy_balancer proxy_connect proxy_http rewrite setenvif so status unique_id userdir" APACHE2_MPMS="prefork" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ubx" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" PHP_TARGETS="php5-3" RUBY_TARGETS="ruby18" USERLAND="GNU" VIDEO_CARDS="apm ark chips cirrus cyrix dummy fbdev glint i128 i740 intel   mach64 mga neomagic nsc nv r128 radeon rendition s3 s3virge savage  siliconmotion sis sisusb tdfx tga trident tseng v4l vesa via vmware     voodoo" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account" 
Unset:  CPPFLAGS, CTARGET, EMERGE_DEFAULT_OPTS, FFLAGS, INSTALL_MASK, LANG, LC_ALL, LINGUAS, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

**Comment by vikas027** [comment]
I had ruby installed through `rbenv`, I had to execute below commands to fix it.

```bash
# paxctl -c $HOME/.rbenv/versions/2.4.1/bin/ruby
file /root/.rbenv/versions/2.4.1/bin/ruby had a PT_GNU_STACK program header, converted
# paxctl -m $HOME/.rbenv/versions/2.4.1/bin/ruby
```
