### ISSUE TITLE
V1.13 `pod update` failed

### ISSUE THREAD

**Issue by granluo** [ffi/ffi#785]
We are having a nightly test using Cocoapods, which need `pod update`. I've found a symbol was not found in a ffi-1.13.0 directory and not sure if it is related to this update.

The test failed on June 1st and the log is like :

```
export LANG=en_US.UTF-8;export GEM_HOME=$HOME/.gem;export PATH=$GEM_HOME/bin:$PATH;env TEMP_ENV=MASTER pod update 
exited w/code 134: Update all pods
Updating local specs repositories
dyld: lazy symbol binding failed: Symbol not found: _ffi_prep_closure_loc
  Referenced from: /Users/kbuilder/.gem/gems/ffi-1.13.0/lib/ffi_c.bundle
  Expected in: /usr/lib/libffi.dylib
```

**Comment by sdinel** [comment]
We have similar results with Fastlane steps :

`bundle exec pod install`

```
Exit status of command 'bundle exec pod install' was  instead of 0.
Analyzing dependencies
dyld: lazy symbol binding failed: Symbol not found: _ffi_prep_closure_loc
  Referenced from: /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.13.0/lib/ffi_c.bundle
  Expected in: /usr/lib/libffi.dylib

dyld: Symbol not found: _ffi_prep_closure_loc
  Referenced from: /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.13.0/lib/ffi_c.bundle
  Expected in: /usr/lib/libffi.dylib
```

Ruby version : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
Pod version : 1.9.3
Mac OS version : 10.14.6

**Comment by Westacular** [comment]
I suspect this is only affecting Mojave?

- Locally, I'm running Catalina (10.15.5) and `pod install` works fine for me with ffi 1.13.0
- My CI machines that are running Mojave (10.14.6) exhibit this error

(All machines are running Ruby 2.6)

**Comment by andrii-rymar** [comment]
Same issue on Mojave runing another gem dependent on ffi, so guess it's not Cocoapods specific.

**Comment by larskanis** [comment]
I opened #787 which should fix this issue. As a temporary workaround ffi-1.13.0 should work if installed on MacOS-10.14 per
```
gem inst ffi -- --disable-system-libffi
```
