### ISSUE TITLE
FFI 0.13.0 no longer ignores invalid parameters

### ISSUE THREAD

**Issue by joshcooper** [ffi/ffi#788]
The ffi 0.13.0 release on Windows switched to using the universal C runtime instead of msvcrt in https://github.com/ffi/ffi/pull/779/files#diff-db0e38803c251431bdf21ae8936ac3f6L132-R132. Previously, msvcrt ignored invalid parameters, but [ucrtbase will abort by default](https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-change-history-2003-2015?view=vs-2019#visual-studio-2005-breaking-changes)

> Many functions now validate their parameters, halting execution if given invalid parameters. This validation may break code that passes invalid parameters and relies on the function ignoring them or just returning an error code.

This can be demonstrated using:

```ruby
require 'ffi'

module MSVCRT
  extend FFI::Library
  ffi_lib 'msvcrt'
  attach_function(:get_osfhandle, :_get_osfhandle, [:int], :intptr_t)
end

module UCRTBASE
  extend FFI::Library
  ffi_lib 'ucrtbase'
  attach_function(:get_osfhandle, :_get_osfhandle, [:int], :intptr_t)
end

puts "msvcrt"
puts MSVCRT.get_osfhandle(42)
puts "ucrtbase"
puts UCRTBASE.get_osfhandle(42)
# we never get here
puts "Done"
```

Note that "Done" is never printed:

```
C:\Users\josh>bundle exec ruby osf.rb
msvcrt
-1
ucrtbase
```

This isn't a problem with FFI, but the ruby process aborts with ` 0xc0000409` without any output, which makes debugging the problem difficult. It'd be great to mention the behavior change in the release notes, and perhaps describe how to install an error handler so that the application can decide how to handle the exception: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/set-invalid-parameter-handler-set-thread-local-invalid-parameter-handler?view=vs-2019.

**Comment by larskanis** [comment]
@joshcooper Thank you for your great analysis!

Obviously the change of `FFI::Library::LIBC` has an impact to several gems and the crashes are more due to the described behavioral change than due to a bug in the depending gem. This behavioral change wasn't intended by a minor version bump (from ffi-1.12 to 1.13). Maybe this is something for ffi-2.0, but for now I think it's best to revert to `msvcrt.dll` for the time being and release it as ffi-1.13.1 soon.

**Comment by joshcooper** [comment]
Thanks @larskanis, much appreciated!
