### ISSUE TITLE
FFI 1.13.1 is failing for me.

### ISSUE THREAD

**Issue by jvlcek** [ffi/ffi#796]
I seem to be encountering the issue described in this Stackoverflow post:
https://stackoverflow.com/questions/62291066/creating-a-controller-with-rails-generate-causing-strange-error

By downgrading to FFI version 1.12.2 I'm able to successfully run my Rails app but with FFI version 1.13.1 I'm encountering:

`Symbol not found: _ffi_prep_closure_loc`

Here is a snippet of my rails app's log file with the error:

[----] I, [2020-06-30T17:55:53.595661 #90506:3ff67c034e10]  INFO -- : MIQ(MiqAeEngine.deliver) Delivering {:event_type=>"evm_server_start", "MiqEvent::miq_event"=>169, :miq_event_id=>169, "EventStream::event_stream"=>169, :event_stream_id=>169} for object [MiqServer.1] with state [] to Automate
dyld: lazy symbol binding failed: Symbol not found: _ffi_prep_closure_loc
  Referenced from: /Users/jvlcek/.rvm/gems/ruby-2.5.7@manageiq/gems/ffi-1.13.1/lib/ffi_c.bundle
  Expected in: /usr/lib/libffi.dylib

dyld: Symbol not found: _ffi_prep_closure_loc
  Referenced from: /Users/jvlcek/.rvm/gems/ruby-2.5.7@manageiq/gems/ffi-1.13.1/lib/ffi_c.bundle
  Expected in: /usr/lib/libffi.dylib

**Comment by jvlcek** [comment]
Please investigate and advise.

Thank you! JoeV

**Comment by larskanis** [comment]
Looks like a dupe of #791 ?

**Comment by jvlcek** [comment]
> Looks like a dupe of #791 ?

Yes. Thank you @larskanis for pointing it out.

I'm closing this as a dup of [#791](https://github.com/ffi/ffi/issues/791)
