### ISSUE TITLE
What is the correct way to pass an array of strings (char**) to a C function?

### ISSUE THREAD

**Issue by ioquatix** [ffi/ffi#797]
I've got an `**options` hash table in Ruby and am trying to invoke `PQconnectStartParams`.

Here is what I'm trying right now:

``` ruby
keys = FFI::MemoryPointer.new(:pointer, options.size + 1)
keys.write_array_of_type(:string, :put_pointer, options.keys.map(&:to_s))
values = FFI::MemoryPointer.new(:pointer, options.size + 1)
values.write_array_of_type(:string, :put_pointer, options.values.map(&:to_s))

pointer = Native.connect_start_params(keys, values, 0)
```

But that's not working.

**Comment by ioquatix** [comment]
This seems like it might be working?

``` ruby
keys = FFI::MemoryPointer.new(:pointer, options.size + 1)
keys.write_array_of_type(:string, :put_pointer, options.keys.map{|key| FFI::MemoryPointer.from_string(key.to_s)})
values = FFI::MemoryPointer.new(:pointer, options.size + 1)
values.write_array_of_type(:string, :put_pointer, options.values.map{|value| FFI::MemoryPointer.from_string(value.to_s)})
```

**Comment by larskanis** [comment]
I would use something like this:

```ruby
require "ffi"

module Native
  extend FFI::Library
  ffi_lib 'libpq'

  typedef :pointer, :PGconn
  enum :ConnStatusType, %i[
    CONNECTION_OK CONNECTION_BAD CONNECTION_STARTED CONNECTION_MADE
    CONNECTION_AWAITING_RESPONSE CONNECTION_AUTH_OK CONNECTION_SETENV CONNECTION_SSL_STARTUP
    CONNECTION_NEEDED CONNECTION_CHECK_WRITABLE CONNECTION_CONSUME CONNECTION_GSS_STARTUP
    CONNECTION_CHECK_TARGET
  ]

  # PGconn *PQconnectdbParams(const char **keywords, const char **values, int expand_dbname);
  attach_function :PQconnectdbParams, [ :pointer, :pointer, :int ], :PGconn
  # ConnStatusType PQstatus(const PGconn *conn);
  attach_function :PQstatus, [ :PGconn ], :ConnStatusType
end

options = {
  host: "",
  port: 5432,
}

keys = options.keys.map do |k|
  FFI::MemoryPointer.from_string(k.to_s)
end
p_keys = FFI::MemoryPointer.new(:pointer, keys.size + 1)
p_keys.write_array_of_pointer(keys)

values = options.values.map do |v|
  FFI::MemoryPointer.from_string(v.to_s)
end
p_values = FFI::MemoryPointer.new(:pointer, values.size + 1)
p_values.write_array_of_pointer(values)

pgconn = Native.PQconnectdbParams(p_keys, p_values, 0)
p pgconn
p Native.PQstatus(pgconn)
```

It's important, that all ruby objects which hold memory used in FFI calls, are pinned in some way to not being GC'ed. So the FFI::MemoryPointer should be kept in some variables, so that the underlying memory isn't freed until the C call resumes. Correct implementation can be tested per `GC.stress = true` to some extend. But that's not suitable for production as it slows down massively.

On the other hand: If there's anything we can do in ruby-pg for better async support or so, give use a note!

**Comment by ioquatix** [comment]
Thanks for your detailed reply.

In order to support the upcoming Ruby 3.0 fiber scheduler, you need to do only one thing:

When you would call a blocking function that does I/O, instead call `IO#wait_readable` or `IO#wait_writable` respectively.

If you want to support Ruby 2.x, then allow the user to inject a custom IO class, which responds to `.new` and implements `#wait_readable` and `#wait_writable`.

You can check how to do it here:

https://github.com/socketry/db-postgres/blob/6fbdd03dd6b04c57c5b7995b60e3f626c674e609/lib/db/postgres/native/connection.rb#L106-L139

We will be augmenting the C interface with some improvements for invoking `IO#wait_readable/wait_writable` but it hasn't landed yet.

**Comment by ioquatix** [comment]
Just to confirm, because pointers goes out of scope here, it could crash right?

https://github.com/socketry/db-postgres/blob/6fbdd03dd6b04c57c5b7995b60e3f626c674e609/lib/db/postgres/native/connection.rb#L28-L38

**Comment by larskanis** [comment]
> Just to confirm, because pointers goes out of scope here, it could crash right?

Yes, the [FFI::MemoryPointer objects](https://github.com/socketry/db-postgres/blob/6fbdd03dd6b04c57c5b7995b60e3f626c674e609/lib/db/postgres/native/connection.rb#L32) are referenced only by pointers and that's not enough to protect it being GC'ed.

**Comment by larskanis** [comment]
@ioquatix Can this issue be closed?

**Comment by ioquatix** [comment]
Yes, thanks!

**Comment by ioquatix** [comment]
Just revisiting this question because I'm implementing it... just wanted to say, thanks for all your hard work maintaining FFI, it's a really special gem.
