### ISSUE TITLE
Check for invalid argument fails on TruffleRuby

### ISSUE THREAD

**Issue by larskanis** [ffi/ffi#803]
Commit d9fe6c703bfa6866b628549d12a43d489e53665c fails on TruffleRuby because MRI and TruffleRuby respond with different errors on invalid arguments: https://github.com/ffi/ffi/runs/858802437#step:8:112

@eregon What do you think? Should we adjust the spec to accept both types of errors or would you like to adjust TruffleRuby to respond equally to MRI?

**Comment by eregon** [comment]
I'll fix in TruffleRuby, `TypeError` seems much better than `NoMethodError` :)

**Comment by eregon** [comment]
I wrote a fix, should be merged soon.

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/f5de7bbfdabd76fb5d4295361c1dd615779f956a.
We need to wait the next [dev build of TruffleRuby](https://github.com/ruby/truffleruby-dev-builder) and then restarting the CI should make it green.

**Comment by eregon** [comment]
I restarted the build of the latest master commit, it's green now :smiley: 
https://github.com/ffi/ffi/runs/860773767

**Comment by larskanis** [comment]
Great! Thank you Benoit!
