### ISSUE TITLE
The to_native class method in a class extended with FFI::DataConverter is called twice with different values

### ISSUE THREAD

**Issue by Adithya-copart** [ffi/ffi#807]
I'm trying to extend a class with `FFI::DataConverter` and perform a nil check in the `to_native` class method to avoid segmentation faults when a nil value is passed.

The `to_native` class method is being called with an instance of the class in most cases. There is a case where the `to_native` method is invoked twice. First with an instance of the class followed by a pointer even though ruby invocation is passing an instance of the class.

This is only happening in one particular [test-case](https://github.com/appsignal/rdkafka-ruby/blob/26beb479dcd87a570a248cd307cdd8633694f6b5/spec/rdkafka/consumer_spec.rb#L718) where this function is called for the first time. The same function call in other places does not reproduce this behavior. I can provide steps to reproduce if necessary.

**Example:**
```
[2] pry(#<Rdkafka::Consumer>)> Rdkafka::Bindings.rd_kafka_consumer_poll(@native_kafka, timeout_ms)
"Handle.to_native invoked with #<Rdkafka::Bindings::Handle:0x00007fcb2c10a7a8>, "
"Handle.to_native invoked with #<FFI::Pointer address=0x00007fcb2d13d000>, "
=> #<FFI::Pointer address=0x00007fcb2fb8f2f0>

[3] pry(#<Rdkafka::Consumer>)> Rdkafka::Bindings.rd_kafka_consumer_poll(@native_kafka, timeout_ms)
"Handle.to_native invoked with #<Rdkafka::Bindings::Handle:0x00007fcb2c10a7a8>, "
=> #<FFI::Pointer address=0x00007fcb2fba0270>
```

The code is as follows:
```
    attach_function :rd_kafka_consumer_poll, [Handle, :int], :pointer, blocking: true

    class Handle
      extend FFI::DataConverter
      native_type FFI::Type::POINTER

      attr_reader :handle_pointer

      def initialize(ptr)
        @handle_pointer = ptr
      end

      class << self
        def from_native(ptr, context)
          new(ptr)
        end

        def to_native(value, context)
          raise if value.nil?

          p "Handle.to_native invoked with #{value}, #{context}"
          value.is_a?(Handle) ? value.handle_pointer : value
        end
      end
    end
```

**Comment by Adithya-copart** [comment]
This is my error. The `attach_function` accepts a instance of the `Handle` class.
It was invoked using a `FFI::Pointer` instance instead which would trigger a call to `to_native` using the pointer instance.

**Comment by larskanis** [comment]
@Adithya-copart Thank you for you follow up! Good to know you solved the issue.

I wasn't able to recognize the mistake from memory in a first attempt. Would you mind to post the change you've done to get your example working?

**Comment by Adithya-copart** [comment]
@larskanis I updated the example with a callback function which illustrates the mistake I actually made.
```
    attach_function :rd_kafka_consumer_poll, [Handle, :int], :pointer, blocking: true
    attach_function :rd_kafka_assign, [Handle, :pointer], :int

    RebalanceCallback = FFI::Function.new(
        :void, [:pointer, :int, :pointer, :pointer]
      ) do |client_ptr, code, partitions_ptr, opaque_ptr|
         Rdkafka::Bindings.rd_kafka_assign(client_ptr, partitions_ptr)
    end
    
    class Handle
      extend FFI::DataConverter
      native_type FFI::Type::POINTER

      attr_reader :handle_pointer

      def initialize(ptr)
        @handle_pointer = ptr
      end

      class << self
        def from_native(ptr, context)
          new(ptr)
        end

        def to_native(value, context)
          raise if value.nil?

          p "Handle.to_native invoked with #{value}, #{context}"
          value.is_a?(Handle) ? value.handle_pointer : value
        end
      end
    end
```

I missed updating one of the callback functions where a pointer is returned from the C-library. I [updated the code](https://github.com/appsignal/rdkafka-ruby/pull/127/files#diff-e2c7aea3be322c3c525fdf482a471043R180-R189) to manually initialize a ruby class with the pointer which solved the issue.
