### ISSUE TITLE
Extra files in gem download

### ISSUE THREAD

**Issue by bjfish** [ffi/ffi#812]
The gemspec currently does not exclude some hidden files which are being distributed:

```
% ls -a data
.		.DS_Store	.github		.gitmodules	.yardopts	COPYING		LICENSE		README.md	ext		lib
..		.appveyor.yml	.gitignore	.travis.yml	CHANGELOG.md	Gemfile		LICENSE.SPECS	Rakefile	ffi.gemspec	samples
```

**Comment by eregon** [comment]
@larskanis How about excluding dot files at the root in https://github.com/ffi/ffi/blob/faae322f74969dfd9a64f767636fea9ed035bf85/ffi.gemspec#L19-L21 ?

**Comment by larskanis** [comment]
Sure, some files could be removed. Which files do you want to remove and why?
