### ISSUE TITLE
How to use typedef aliases in other methods?

### ISSUE THREAD

**Issue by dv** [ffi/ffi#816]
I'm trying to use `typedef` aliases in utility methods in the same module as where the `typedef` was defined.

Here's a condensed version that does not work:

```ruby
require "ffi"

module Sample
  extend FFI::Library

  typedef :size_t, :alias_size

  def self.get_pointer
    FFI::MemoryPointer.new(:alias_size, 1)
  end
end

Sample.get_pointer # <- error here
```

This will throw a `TypeError (unable to resolve type 'alias_size')`. I've tried multiple approaches to get this to work, but could not find anything. Is there something I'm missing, or does FFI just not support a usage like that?

**Comment by eregon** [comment]
One problem here is that `FFI::MemoryPointer.new(:alias_size, 1)` has no (reasonable) way to know under which method/module it is.

This works:
```ruby
require "ffi"

module Sample
  extend FFI::Library

  typedef :size_t, :alias_size

  ALIAS_SIZE = find_type(:alias_size)

  def self.get_pointer
    FFI::MemoryPointer.new(ALIAS_SIZE, 1)
  end
end

p Sample.get_pointer
```

**Comment by dv** [comment]
Thanks @eregon, this helps.

I've adjusted it to be:

```ruby
...
ALIAS_SIZE = typedef :size_t, :alias_size
...
```

This makes it nicely contained in a single line.
