### ISSUE TITLE
Pointers -- how do I declare a void pointer?

### ISSUE THREAD

**Issue by phykos** [ffi/ffi#818]
I am looking for a little project, a LibLLVM(10) FFI library for Ruby, but some function return a void pointer (`void*` in C)
How do I define a function for let it return a void pointer?
I tried Fiddle, and for that there is `Fiddle::TYPE_VOIDP`, with FFI, do I have to pass `:voidp` as ret value?

**Comment by larskanis** [comment]
You can use :pointer type. See here in the wiki: https://github.com/ffi/ffi/wiki/Types

In addition it's possible to define typedefs or map a pointer to a FFI::Struct . Much more possibilities compared to fiddle.

**Comment by phykos** [comment]
> You can use :pointer type. See here in the wiki: https://github.com/ffi/ffi/wiki/Types
> 
> In addition it's possible to define typedefs or map a pointer to a FFI::Struct . Much more possibilities compared to fiddle.

Ik, but what's the correct syntax for declaring a function returning a void pointer?

**Comment by larskanis** [comment]
> Ik, but what's the correct syntax for declaring a function returning a void pointer?

Nothing special, just something like:
```ruby
attach_function 'libusb_dev_mem_alloc', [:libusb_device_handle, :size_t], :pointer
```
