### ISSUE TITLE
Autogenerated FFI::Function can be improperly free, leading to segfaults

### ISSUE THREAD

**Issue by byteit101** [ffi/ffi#820]
I've been going mad over this SEGV, trying to figure out if I'm doing something wrong with either the libpulse API or FFI, but it looks like it's a bug in ffi (or ruby, but that seems unlikely so far). It appears in certain circumstances, ffi will forget to tell the GC about a `FFI::Function`, and on the next GC, it will be freed, leading to potentially overwriting data down the line that can cause a segfault.

### Environment

 - Debian Linux 10 (x64)
 - pulseaudio w/ dev headers installed (libpulse-dev)
 - at least one pulseaudio sink (output, ie: can you play audio and hear it)
 - CRuby (tested as failing on 2.5.1, 2.6.2, 2.7.1)
 - any ffi version from master back to 0.10.0 at least
 - Test case & optional debugging C changes: https://gist.github.com/byteit101/cffecfe00cc109f5f851aab9f52813b9

### Expected
If you run it with JRuby (9.2.7.0 is the version I tried) it works fine (once you comment out the two ObjectSpace debug info lines) by not crashing until it has taken up all your memory and oom's

### Actual
The main script will segfault shortly after, and is configurable as per the comments in the test script as to avoid, delay, or make happen sooner.
I tried to simplify the test case further, such as by removing libpulse and replacing it with a simpler library, but I was not able to get it to crash in that case.

### Notable things
If only one callback is happening for stream reads, everything is ok. If both callbacks are enabled, then both underlying `FFI::Functions` are `free()`'d. 
The crash location varies based on the (configurable) sections in the test case, but is _generally_ stable.

The general structure for a SEGV is:

 1. Allocate the `FFI::Function` (rubyid=1, memory=2) implicitly as we pass a `proc` (rubyid=3, name=`NativeCallbackManager::Callback`) to the callback-accepting function
 2. Pass (mem=2) to  the underlying ffi c function (`pa_stream_set_read_callback` in this case)
 3. Annocate another `FFI::Function` (rubyid=4, memory=5) implicitly as we pass the same `proc` (rubyid=3, name=`NativeCallbackManager::Callback`) to the same callback-accepting function.
 4. Pass (mem=5) to  the underlying ffi c function (`pa_stream_set_read_callback` in this case)
 5. Receive a callback on either 2 or 5 from the underlying ffi c function (`pa_stream_set_read_callback` in this case)
 6. Receive the other callback (5 or 2)
 7. Trigger a GC. Both 1 and 4 are freed, and 2 & 5 are now dangling in the ffi lib. Bad things will now happen.
 8. Have a lot of memory usage in the transient heap to be migrated to the normal heap. 1 and 4 are now overwritten here.
 9. The underlying ffi c function does a callback on 2 or 5, who attempt to get 1 or 4. Boom, SIGSEGV!

I am unsure what steps are missing for my non-libpulse tests, but I couldn't get them to fail, only the large libpulse based one.

### Memory trace

Addresses are raw pointers, except for rubyid (handy for the object space dump)
```txt
++++++++++++++++++++  alloc FOR  are 555555c40c00  (rubyid=555555c367e8) 
..snip...
pulse connected to stream
++++++++++++++++++++  alloc FOR  are 555555c429e0  (rubyid=555555c362c0) 
++++++++++++++++++++  alloc FOR  are 555555c42a50  (rubyid=555555c36270) 
Pointers(new) are 555555c429e0 and 555555cced20, from cb 7fffffffbc80 555555c3fed8,  rbproc: 555555c37d28 wl 555555c42a10  #the old callbacks
pulse connected to stream
Pointers(new) are 555555c3bab0 and 555555cdfc10, from cb 7fffffffca40 555555c3bb80,  rbproc: 555555c37d28 wl 555555c3bae0 
Pointers(new) are 555555c3fde0 and 555555cced20, from cb 7fffffffcb90 555555c3feb0,  rbproc: 555555c37d28 wl 555555c3fe10 
Pointers(new) are 555555c429e0 and 555555cced20, from cb 7fffffffcb90 555555c3fed8,  rbproc: 555555c37d28 wl 555555c42a10 
Pointers(new) are 555555c40c00 and 555555ccec10, from cb 7fffffffcd20 555555c40cd0,  rbproc: 555555c37d28 wl 555555c40c30 # the pa_stream_set_read_callback proc # 1 (see the alloc above has the same first number)
inside stream_read
Pointers(new) are 555555c42a50 and 555555ccec10, from cb 7fffffffcd20 555555c40cf8,  rbproc: 555555c37d28 wl 555555c42a80 # the pa_stream_set_read_callback proc # 2 (see the alloc above has the same first number)
inside stream_read
..snip...
size is 24398
size is 24398
>>>>>>>>>>>>>>>>  FREE FOR  are 555555c39910,  rbproc: 555555c37d28 wl 555555c39940  # ok, old proc. Now look at the wl (watch line) numbers
>>>>>>>>>>>>>>>>  FREE FOR  are 555555c3bab0,  rbproc: 555555c37d28 wl 555555c3bae0   # ok, old proc.
>>>>>>>>>>>>>>>>  FREE FOR  are 555555c3fde0,  rbproc: 555555c37d28 wl 555555c3fe10   # ok, old proc.
>>>>>>>>>>>>>>>>  FREE FOR  are 555555c40c00,  rbproc: 555555c37d28 wl 555555c40c30  # Yikes!  this is proc #1 being freed
!!!!!!!!! Apointer! # break on this statement if you care to use gdb
>>>>>>>>>>>>>>>>  FREE FOR  are 555555c429e0,  rbproc: 555555c37d28 wl 555555c42a10   # ok, old proc.
"checksecond 0" # proc 2 was just called successfully, as it hasn't been freed yet

Thread 1 "ruby" received signal SIGSEGV, Segmentation fault. # and now proc 1 was attempted to be called
invoke_callback (data=data@entry=140737488342304) at Function.c:672
672	    Type* returnType = cbInfo->returnType;
(gdb) 

````
### ObjectSpace dumps
You'll have to tweak the config to not crash after the free (aka avoid step 8, see the test file for what do to), then you can compare the dumps. This is what I got for the above run (filenames vary):
```txt
/tmp $ grep 555555c367e8 ruby-heap.dump201first # notice we are using the ruby id here
/tmp $ grep 555555c367e8 ruby-heap.dump101second
{"address":"0x555555dd9140", "type":"HASH", "class":"0x5555557a0d78", "size":1, "references":["0x555555bcc2d0", "0x555555c367e8"], "file":"./test", "line":276, "method":"stream_set_read_callback", "generation":23, "memsize":232, "flags":{"wb_protected":true, "old":true, "uncollectible":true, "marked":true}}
{"address":"0x555555c367e8", "type":"DATA", "class":"0x555555ba4ca8", "references":["0x555555d57410", "0x555555bcc2d0"], "file":"./test", "line":276, "method":"stream_set_read_callback", "generation":23, "memsize":40, "flags":{"uncollectible":true, "marked":true}}
```

**Comment by larskanis** [comment]
@byteit101 Thank you for your detailed bug report!

I was able to reproduce your segfault. First I wondered why you use the NativeCallbackManager to create a single Proc and dispatch from there by help of the callback argument. This is uncommon, since ruby-ffi can easily create a dedicated callback address for each and every call to a C function. So usually you don't need this typical callback `void*` in ruby.

So I changed the NativeCallbackManager to something like this and the segfault was gone:
```ruby
module NativeCallbackManager
  def self._init
    @procs = []
  end

  def self.make_callback(&blk)
    pr = proc do |*args, ptr|
      yield(*args)
    end
    @procs << pr
    [pr, nil]
  end
end
```

Nevertheless your usage is correct and so I digged deeper and found out, that starting with the third callback signature that a Proc is used for, the GC is eating old callback addresses. This is fixed in commit https://github.com/ffi/ffi/commit/42a9bbd69b7dffbae1c57a4c083382af723fa1f3 .
