### ISSUE TITLE
Installation fails with Ruby 2.7.1:  `/usr/bin/mkdir` not found

### ISSUE THREAD

**Issue by dhs-rec** [ffi/ffi#822]
After updating from Ruby 2.7.0 to 2.7.1 `make install` fails with the following message:
```
current directory: /usr/local/rvm/gems/ruby-2.7.1@MyGemset/gems/ffi-1.13.1/ext/ffi_c
make "DESTDIR=" install
make: /usr/bin/mkdir: Command not found
make: *** [Makefile:202: .sitearchdir.time] Error 127

make install failed, exit code 2
```
There is no `/usr/bin/mkdir`, just `/bin/mkdir` (system is Ubuntu 20.04, but checked on 18.04 and Debian 10, too)

**Comment by larskanis** [comment]
`/usr/bin/mkdir` should be a symlink to `/bin/mkdir` on Ubuntu-20.04:
```
$ ls -l /usr/bin/mkdir 
lrwxrwxrwx 1 root root 10 Jun 12 10:21 /usr/bin/mkdir -> /bin/mkdir*
```

**Comment by dhs-rec** [comment]
But it isn't. Not on 18.04, not on 20.04 and also not on Debian 10. I've also checked the `coreutils` package sources, and there's no sign that it should create a symlink. In fact, it explicitely moves mkdir (and other) binaries from /usr/bin to /bin, but that's all it does.

**Comment by larskanis** [comment]
I guess that Ubuntu installs the symlink by some development package. Anyway ruby-ffi doesn't use any absolute references to mkdir. So the issue is probably somewhere else.

**Comment by dhs-rec** [comment]
Yeah, maybe. May also be a Ruby issue, but I wasn't sure where to file it. It's working fine with Ruby 2.7.0, after all.

**Comment by dhs-rec** [comment]
OK, found the reason. As you can see from the error message above, I am using RVM to setup Ruby Gemsets. When I reinstalled Ruby 2.7.0 yesterday after running into the error with 2.7.1, I recognized that RVM actually compiled 2.7.0, which it didn't do when installing 2.7.1. So I reinstalled Ruby 2.7.1, forcing it to be compiled by passing `--disable-binary` and the error went away. I'll file an issue with RVM...

**Comment by kenyon** [comment]
https://github.com/rvm/rvm/issues/4975

**Comment by wanchic** [comment]
> OK, found the reason. As you can see from the error message above, I am using RVM to setup Ruby gemsets. When I reinstalled Ruby 2.7.0 yesterday after running into the error with 2.7.1, I recognized that RVM actually compiled 2.7.0, which it didn't do when installing 2.7.1. So I reinstalled Ruby 2.7.1, forcing it to be compiled by passing `--disable-binary` and the error went away. I'll file an issue with RVM...

I was having multiple issues with Ruby 2.5, 2.6, & 2.7, with gem install rails 6.0 & 6.1. I'm using Ubuntu 20.04 and yes, I utilize RVM! using `--disable-binary` was the key to making rails gem install again. Thanks dhs-rec!

`rvm remove 2.7.2`  - make sure you don't have any gemsets you want to delete before doing this. It will erase the ruby version and all gemsets associated with it.

`rvm install 2.7.2 --disable-binary`
`rvm use 2.7.2@new_gemset`
`gem install rails -v 6.1.2.1 --no-doc`

No compile errors on `racc` after this.

**Comment by dhnaranjo** [comment]
I believe @wanchic meant https://github.com/ffi/ffi/pull/882

**Comment by alexisdiaz008** [comment]
Can confirm, just ran into the same issue of rvm being unable to bundle with ruby 2.7.1 and rails 6.0.3 on ubuntu 18.04, disabling binary on rvm install worked, thank you!

**Comment by KitMurdock** [comment]
I ran into this issue on Ubuntu 20.04 with ruby 3.0.0 - disabling binary worked for me too. Thank you!

**Comment by aayestashn** [comment]
> --disable-binary

Thank you

**Comment by DanSmaR** [comment]
Great, it worked here too
