### ISSUE TITLE
GNU_LIBC doesn't work on JRuby

### ISSUE THREAD

**Issue by ahorek** [ffi/ffi#824]
JRuby
```
require 'ffi'
FFI::Platform::LIBC => libc.so
```

CRuby
```
require 'ffi'
FFI::Platform::LIBC => libc.so.6
```

unfortunately, libc.so can't be loaded on my environment (linux)
```
LoadError:
  Could not open library 'libc.so' : /usr/lib/x86_64-linux-gnu/libc.so: neplatný hlavička ELF
```

libc.so.6 works fine

on CRuby we do invoke a C compiler to determine the right version name
https://github.com/ffi/ffi/blob/master/lib/ffi/platform.rb#L144
https://github.com/ffi/ffi/blob/6dfc35ff79488ed6c38bd6e0e5f7868917e87eb0/ext/ffi_c/Platform.c#L47
https://sites.uclouvain.be/SystInfo/usr/include/gnu/lib-names.h.html

but we can't do the same trick on JRuby. There's also ```libc.so.6``` hardcoded on a few places, for instance here
https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/ffi/Platform.java#L177
or
https://github.com/ffi/ffi/blob/74c6f265f24f5aafc13f9237906c7a6c341edd59/spec/ffi/library_spec.rb#L152

Does anyone have an idea of how to guess the correct library name more reliably?

**Comment by eregon** [comment]
FWIW on TruffleRuby we just hardcode it too:
https://github.com/oracle/truffleruby/blob/8010c368d89f7eeae54e9ee201b279b696e63f0e/lib/truffle/truffle/ffi_backend.rb#L31-L36

Seems it's unlikely to ever change: https://stackoverflow.com/questions/6495817/why-glibc-binary-is-called-libc-so-6-not-a-libc-so-1-or-libc-so-4
