### ISSUE TITLE
Unable to install FFI....

### ISSUE THREAD

**Issue by AndreasKr** [ffi/ffi#844]
Dear all,

actually I want to install cocoapods. But I receive an error regarding ffi:

    $ gem install ffi --user-install
    Building native extensions. This could take a while...
    ERROR:  Error installing ffi:
 	ERROR: Failed to build gem native extension.

       current directory: /Users/andreas/.gem/ruby/2.6.0/gems/ffi-1.13.1/ext/ffi_c
     /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I 
     /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20201123-5296-1rxaqx.rb 
     extconf.rb
     checking for ffi.h... *** extconf.rb failed ***
     Could not create Makefile due to some reason, probably lack of necessary
     libraries and/or headers.  Check the mkmf.log file for more details.  You may
     need configuration options.

Also in the github repository I cannot find a ffi.h - only a ffi.c...  It seems that the headerfile is missing

Regards
Andreas

**Comment by larskanis** [comment]
ffi.h is not the problem. Either the compiler is missing or the Ruby development headers (ruby.h). The file mkmf.log should give you more details.

**Comment by designervoid** [comment]
Same problem on macOS Big Sur 11.0.1

**Comment by designervoid** [comment]
> Same problem on macOS Big Sur 11.0.1
Also I facing with that problem second time,  first time this helped me [https://github.com/CocoaPods/CocoaPods/issues/10103#issuecomment-701625230](url)

**Comment by designervoid** [comment]
@larskanis here is my log file
```
designervoid@MacBook-Pro-Maxim ios % cat /Users/designervoid/gems/extensions/universal-darwin-20/2.6.0/ffi-1.9.25/mkmf.log
"pkg-config --exists libffi"
| pkg-config --libs libffi
=> "-L/usr/local/Cellar/libffi/3.3/lib -lffi\n"
"xcrun clang -o conftest -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20 -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/backward -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS -DUSE_FFI_CLOSURE_ALLOC conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.Internal.sdk/usr/local/lib     -lruby.2.6   "
In file included from conftest.c:1:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby.h:33:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: note: did not find header 'config.h' in framework 'ruby' (loaded from '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks')
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by designervoid** [comment]
@larskanis also i was try to update my environments variables
https://github.com/ffi/ffi/issues/653#issuecomment-458895497

**Comment by ShreeSoftech-Bhuj** [comment]
same problem with Xcode 13 - macOS 12.0 Beta
