### ISSUE TITLE
error: implicit declaration of function 'ffi_prep_closure' on M1 macOS Big Sur

### ISSUE THREAD

**Issue by defp** [ffi/ffi#869]
```
❯ rbenv install 2.4.0
Installing ruby-2.4.0...

WARNING: ruby-2.4.0 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

ruby-build: using readline from homebrew

BUILD FAILED (macOS 11.1 using ruby-build 20201210-10-g5de6d5f)

Inspect or clean up the working tree at /var/folders/mz/q1f7_y852v7__rt9f3lm0yd40000gn/T/ruby-build.20201229181439.24184.CZQlN7
Results logged to /var/folders/mz/q1f7_y852v7__rt9f3lm0yd40000gn/T/ruby-build.20201229181439.24184.log

Last 10 log lines:
compiling fiber.c
linking shared-object fiber.bundle
compiling closure.c
closure.c:263:14: error: implicit declaration of function 'ffi_prep_closure' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    result = ffi_prep_closure(pcl, cif, callback, (void *)self);
             ^
1 error generated.
make[2]: *** [closure.o] Error 1
make[1]: *** [ext/fiddle/all] Error 2
make: *** [build-ext] Error 2

```

logs

[ruby-build.20201229181439.24184.log](https://github.com/ffi/ffi/files/5750318/ruby-build.20201229181439.24184.log)

install ruby 3.0.0 is ok

**Comment by rience** [comment]
The same error happens to me. I can install

• 3.0.0
• 2.7.2

But when I try to install `2.7.1` or `2.6.6` I have the exact same issue. I'm using ffi `1.14.2`.

**Comment by rience** [comment]
I was able to install other versions by passing `USE_FFI_CLOSURE_ALLOC`, like this

```
RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC rbenv install 2.6.6
```

**Comment by silviosav-SEGA-HARDlight** [comment]
Same issue but when installing cocoapods in sudoless mode with some pods. 

I'm on Catalina 10.15.7 and with the system ruby version which is 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19].

Here's the whole log.

`Building native extensions. This could take a while...
ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    current directory: /Users/silvio.savino/.gem/ruby/2.6.0/gems/ffi-1.14.2/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210105-78259-1sfyqmc.rb extconf.rb
checking for ffi_prep_closure_loc() in -lffi... yes
checking for ffi_prep_cif_var()... yes
checking for ffi_raw_call()... yes
checking for ffi_prep_raw_closure()... yes
creating extconf.h
creating Makefile

current directory: /Users/.../.gem/ruby/2.6.0/gems/ffi-1.14.2/ext/ffi_c
make "DESTDIR=" clean

current directory: /Users/.../.gem/ruby/2.6.0/gems/ffi-1.14.2/ext/ffi_c
make "DESTDIR="
compiling AbstractMemory.c
compiling ArrayType.c
compiling Buffer.c
compiling Call.c
compiling ClosurePool.c
compiling DynamicLibrary.c
compiling Function.c
Function.c:847:17: error: implicit declaration of function 'ffi_prep_closure_loc' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    ffiStatus = ffi_prep_closure_loc(closure->pcl, &fnInfo->ffi_cif, callback_invoke, closure, code);
                ^
Function.c:847:17: note: did you mean 'ffi_prep_closure'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/ffi/ffi.h:269:1: note: 'ffi_prep_closure' declared here
ffi_prep_closure(
^
1 error generated.
make: *** [Function.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/.../.gem/ruby/2.6.0/gems/ffi-1.14.2 for inspection.
Results logged to /Users/.../.gem/ruby/2.6.0/extensions/universal-darwin-19/2.6.0/ffi-1.14.2/gem_make.out`

**Comment by fedeagripa** [comment]
Hi! I'm having this same problem using RVM, I tried all the top solutions but is not working, any ideas 🙏  ?

**Comment by cambrianentropy** [comment]
> I was able to install other versions by passing `USE_FFI_CLOSURE_ALLOC`, like this
> 
> ```
> RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC rbenv install 2.6.6
> ```

New M1 macbook, this also worked for me!

**Comment by minhtrung2606** [comment]
> I was able to install other versions by passing `USE_FFI_CLOSURE_ALLOC`, like this
> 
> ```
> RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC rbenv install 2.6.6
> ```

New M1 MacBook, this also worked for me!
Some details to share:

- MacOSBigSur#11.2.3
- asdf#v0.8.0-c6145d0 (I used [ASDF](https://asdf-vm.com/#/) to install Ruby - `asdf global ruby 2.5.8`)

**Comment by shakilearl** [comment]
> Hi! I'm having this same problem using RVM, I tried all the top solutions but is not working, any ideas 🙏 ?

I am also using RVM and in my situation, the following worked for me:

**Step 1**
Run in terminal: **brew info libffi** which will output the following:

# For compilers to find libffi you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"

# For pkg-config to find libffi you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"

**Step 2**
Run all 3 export commands in terminal to set the env variables.

**Step 3**
Finally, run the ruby installation command. In my case, it was: rvm install ruby-2.5.3

Hope it helps.

**Comment by asungur** [comment]
I had the same problem on macOS 11.2.3 trying to install ruby 2.6.6 with RVM. @shakilearl's solution helped with the installation problem. 2.6.6 works fine but when `rvm list`, I get:
```
=> ruby-2.6.6 [ broken ]
   *  ruby-3.0.0 [ arm64 ]
``` 
What does your `rvm list` log?

**Comment by mayuresh-srivastava** [comment]
I am also seeing the same thing:

> MacBook-Pro:~ mayuresh.srivastava$ rvm list
> => ruby-2.6.2 [ broken ]
>  * ruby-2.7.2 [ arm64 ] 

Will it work or will be having issues?

**Comment by KranthiKishore** [comment]
> I am also seeing the same thing:
> 
> > MacBook-Pro:~ mayuresh.srivastava$ rvm list
> > => ruby-2.6.2 [ broken ]
> > 
> > * ruby-2.7.2 [ arm64 ]
> 
> Will it work or will be having issues?

For me also same issue, it shows as broken.
 * ruby-2.5.8 [ broken ]
=> ruby-2.6.6 [ broken ]

Will Ruby work when it's broken?

**Comment by tbhockey** [comment]
> For me also same issue, it shows as broken.
> 
> * ruby-2.5.8 [ broken ]
>   => ruby-2.6.6 [ broken ]
> 
> Will Ruby work when it's broken?

I have this as well, but so far everything seems to work as expected 🤷‍♂️

**Comment by asungur** [comment]
In the end, we decided to migrate everything to ruby 2.7.2 which seems like the earliest compatible version with M1s.

**Comment by mayuresh-srivastava** [comment]
2.7.2 is in rvm known list and I guess that's why not broken.

> MacBook-Pro:menustreams-v2 mayuresh.srivastava$ rvm list known
> # MRI Rubies
> [ruby-]1.8.6[-p420]
> [ruby-]1.8.7[-head] # security released on head
> [ruby-]1.9.1[-p431]
> [ruby-]1.9.2[-p330]
> [ruby-]1.9.3[-p551]
> [ruby-]2.0.0[-p648]
> [ruby-]2.1[.10]
> [ruby-]2.2[.10]
> [ruby-]2.3[.8]
> [ruby-]2.4[.10]
> [ruby-]2.5[.8]
> [ruby-]2.6[.6]
> [ruby-]2.7[.2]
> [ruby-]3[.0.0]
> ruby-head

**Comment by trandaison** [comment]
@shakilearl Thank you sir, this saved my day!

> I am also using RVM and in my situation, the following worked for me:
> 
> Step 1
> Run in terminal: brew info libffi which will output the following:
> 
> For compilers to find libffi you may need to set:
> export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
> export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"
> 
> For pkg-config to find libffi you may need to set:
> export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"
> 
> Step 2
> Run all 3 export commands in terminal to set the env variables.
> 
> Step 3
> Finally, run the ruby installation command. In my case, it was: rvm install ruby-2.5.3
> 
> Hope it helps.

**Comment by SHGoldfarb** [comment]
solution by @shakilearl worked for me

**Comment by jippylong12** [comment]
For anyone else that is not using the homebrew-bootstrap script that is reference above, I believe the line to execute should simply be 

`export RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC`

So for me, I have the M1 Mac and using rbenv and seeing this issue when trying to use rbenv install. When I export that flag, the issue was resolved and I can freely install ruby versions.

**Comment by revolter** [comment]
Knowing that this was closed, what is the correct and official solution?

**Comment by JigarJoshi04** [comment]
> I was able to install other versions by passing `USE_FFI_CLOSURE_ALLOC`, like this
> 
> ```
> RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC rbenv install 2.6.6
> ```

This is working for ruby 2.4.1 as well.
Thank you.

**Comment by bfad** [comment]
In case it helps people using `ruby-install`, the following worked for that:
```shell
 ruby-install ruby-2.4.3 -- CFLAGS=-DUSE_FFI_CLOSURE_ALLOC
```

**Comment by meshane** [comment]
> ```shell
>  ruby-install ruby-2.4.3 -- CFLAGS=-DUSE_FFI_CLOSURE_ALLOC
> ```

Thanks @bfad, that worked great

**Comment by mrpunkin** [comment]
> ```shell
>  -- CFLAGS=-DUSE_FFI_CLOSURE_ALLOC
> ```

This solution is also the only one that worked for me with Ruby 2.4.1 via RVM on 12.1 Monterey M1. Thanks @bfad!

**Comment by mogosam** [comment]
> I was able to install other versions by passing `USE_FFI_CLOSURE_ALLOC`, like this
> 
> ```
> RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC rbenv install 2.6.6
> ```

With M1 MacBook this worked for me.

**Comment by victorpolko** [comment]
The only approach that was able to fix the issue for me is [this one](https://github.com/rvm/rvm/issues/5043#issuecomment-967000943).
It's about letting Rosetta deal with the installation of everything. Looks like not every library is silicon-ready yet.

MacBook Pro M1 16-Core '21.

**Comment by 9bow** [comment]
This works for me, with M1 macbook.
> RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC rbenv install 2.5.9

**Comment by santry** [comment]
I use https://github.com/postmodern/ruby-install and I needed the following to get Ruby 2.6.5 to build on my M1 MacBook Air (2020):

```
export RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC
export optflags="-Wno-error=implicit-function-declaration"
ruby-install 2.6.5
```

**Comment by Meekohi** [comment]
All 3 of these work-arounds worked for me:

Install new version and let compiler know:
```
brew install libffi
export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"
LDFLAGS="-L/opt/homebrew/opt/libffi/lib" CPPFLAGS="-I/opt/homebrew/opt/libffi/include" rvm install 2.5.1
```

Ignore deprecated syntax:
```
CPPFLAGS=-DUSE_FFI_CLOSURE_ALLOC rvm install 2.5.1 
```

Don't install fiddle:
```
rvm install 2.5.1 --with-out-ext=fiddle
```

(see [rvm issue #5153](https://github.com/rvm/rvm/issues/5153#issuecomment-1228509749))

**Comment by steakknife** [comment]
Ruby-install method: `brew install bison@2.7 ruby-install openssl@1.1 libffi && env MAKEFLAGS=-j CPPFLAGS=-DUSE_FFI_CLOSURE_ALLOC PKG_CONFIG_PATH="$(brew --prefix libffi)/lib/pkgconfig" PATH="$(brew --prefix bison@2.7)/bin:$PATH" ruby-install 2.4.10 -- --enable-shared --disable-install-doc --with-openssl-dir=$(brew --prefix openssl@1.1)`

**Comment by santry** [comment]
FWIW, [this Ruby On Mac article](https://www.rubyonmac.dev/how-to-install-ruby-on-macos-12-6-apple-silicon) has the following to say:

>Similarly, if your project is using a version of 2.6.x lower than 2.6.8, that doesn’t mean you have to use that version. I keep seeing a lot of people try to install Ruby 2.6.6 on Apple Silicon, and recommendations to add the -Wno-error=implicit-function-declaration flag.

>While that may allow Ruby to be installed, it can lead to other issues down the line. It’s also dangerous because it overrides macOS defaults.

>Benoit Daloze, one of the rbenv and ruby-build maintainers, [explains](https://github.com/rbenv/ruby-build/issues/2001#issuecomment-1181613673) in more detail why this flag should not be used:

>>First, it does not seem advisable to disable something the OS does by default. Actually it can be a pretty dangerous workaround, because then the compiler does not know precise argument types and could end up passing arguments incorrectly, which could cause all kinds of problems.

>>Also, recent CRuby enables that flag by default, and it would be very bad to disable something CRuby enables on purpose.

>Since you can install 2.6.8 and greater natively on Apple Silicon without any dangerous hacks, and since there shouldn’t be any breaking changes between older 2.6.x versions and newer ones, you should be able to get your project up and running by simply updating the version in your Gemfile and/or .ruby-version.

**Comment by subashcs** [comment]
Working after recent upgrade to Mac OS Ventura

**Comment by laurent-martin** [comment]
Same problem on ventura 13.1, fixed like this:
```bash
eval $(brew info libffi|grep ' export ')

rvm install ruby-2.4.10
```

**Comment by vinayhegde-drip** [comment]
would recommend trying the upvoted solutions from <ins>rvm/rvm#5047</ins> or alternatively run

```ruby
rvm install x.x.x -C --with-openssl-dir=$HOME/.rvm/usr --with-out-ext=fiddle
```

_tested on Mac OSX Monterey v12.6.6_

**Comment by leewaa** [comment]
> Same problem on ventura 13.1, fixed like this:
> 
> ```shell
> eval $(brew info libffi|grep ' export ')
> 
> rvm install ruby-2.4.10
> ```

Worked also for Macbook M2 running Sonoma 14.4 to instal `ruby 2.2.3`

**Comment by jpdeburgo** [comment]
This worked for me too!
I'm using an M3
```
RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC rbenv install 2.6.5
```
