### ISSUE TITLE
Version 1.15 seems to have problem with Arm Linux (Raspberry Pi)

### ISSUE THREAD

**Issue by printfinn** [ffi/ffi#893]
I was upgrading Rails to 6.0.3.6 from 6.0.3.4 on my Raspberry Pi, after bundle update, ffi gem updated to version 1.15.
But it encounters:

`symbol lookup error: ***/gems/ffi-1.15.0/lib/ffi_c.so: undefined symbol: pthread_atfork`

After I downgrade ffi gem to 1.14.2 (specify it in Gemfile), the problem disappeared.

I'll leave this issue closed, just in case anyone finds the same problem.

**Comment by mariuz** [comment]
The same issue we have on graviton instances on AWS

**Comment by larskanis** [comment]
I think the issue is very similar to https://github.com/scipy/scipy/issues/11323 .  The use of `pthread_atfork` was introduced in ffi-1.15.0, so we probably have to add `-lpthread` or `-pthread` to our compiler options.

**Comment by adeserg** [comment]
Good afternoon.
I'm new to rails but using scaffold I got this error, you could help me solve it. Try to download a better version and delete the last one, but still reinstall it.Beforehand thank you very much.

**rails_generate: symbol lookup error: /home/phablet/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/ffi-1.15.0/lib/ffi_c.so: undefined symbol: pthread_atfork**

**Comment by printfinn** [comment]
> Good afternoon.
> I'm new to rails but using scaffold I got this error, you could help me solve it. Try to download a better version and delete the last one, but still reinstall it.Beforehand thank you very much.
> 
> **rails_generate: symbol lookup error: /home/phablet/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/ffi-1.15.0/lib/ffi_c.so: undefined symbol: pthread_atfork**

I don't quite get you, but maybe you didn't modify your `Gemfile` in your rails project, so the ffi gem remained the latest version. 
You need to append this line:
```gem "ffi", "~> 1.14.2"```
to your `Gemfile`, then run bundle again.

**Comment by larskanis** [comment]
I'll fix this issue in the next release. Until then you should be able to use ffi-1.15.0 by either:
```sh
gem inst ffi -- --with-ldflags=-pthread
```
or with bundler:
```sh
bundle config build.ffi --with-ldflags=-pthread
```

**Comment by yoshiyoshiharu** [comment]
I'm new to rails. I created rails project with Docker.(ruby: 2.6.0, rails: 6.0.0)
I made user model using scaffold. When I access `http://localhost/users, the following error occured.
`symbol lookup error: /usr/local/bundle/gems/ffi-1.15.0/lib/ffi_c.so: undefined symbol: pthread_atfork`

I tried both method, but it doesn't work well.

> I'll fix this issue in the next release. Until then you should be able to use ffi-1.15.0 by either:
> 
> gem inst ffi -- --with-ldflags=-pthread
> or with bundler:
> 
> bundle config build.ffi --with-ldflags=-pthread
