### ISSUE TITLE
FFI call of C++ function fails at script execution time when referencing method from the .Net DLL

### ISSUE THREAD

**Issue by vprokopenko** [ffi/ffi#898]
Hi guys!

I have the following dramatic story to share with you:
1. I need to access the .Net dll from ruby process.
2. COM is NOT an option at this case, please take this as granted :)
3. I've written a C++ wrapper dll over the .Net dll and exported the needed function.
4. Here are the shortified sources:

**demo.cs - CSharpDemo.dll**
```
...
    public class CSharpClass
    {
        public static string CSharpTest(string input)
        {
            return "Hello from C#";
        }
    }
```

**demo.h - CppDemo.dll**
```
...
extern "C" __declspec(dllexport) const char * CppTest(const char * inputValue);
```

**demo_csharp.h - CppDemo.dll**
```
...
using namespace CSharp::Demo;

inline
std::string CSharpTest(const char * inputValue) {
	String^ managedInput = ToManagedString(inputValue); // unmanaged input str to managed str

	String^ managedOutput = CSharpClass::CSharpTest(managedInput); // call C# method

	return ToStdString(managedOutput); // managed str to unmanaged str
}
```

**demo.cpp - CppDemo.dll**
```
...
const char * CppTest(const char * inputValue) {
	std::string output = CSharpTest(inputValue);
	char * str = _strdup(output.c_str());
	return str;
}
```

**demo.rb**
```
require "ffi"

module CppDemo
	extend FFI::Library
	
	ffi_lib "C:/full_path/CppDemo.dll", "C:/full_path/CSharpDemo.dll"
	
	attach_function :CppTest, [ :string ], :string
end

message = CppDemo.CppTest("input")
puts "message = #{message}"
```

5. It works fine as far as:
 - I access C++ dll from the C++ console application: call into .Net dll succeeds and returns the expected value;
 - I remove the C# dll method call from the C++ dll, ruby scripts gets the value from the C++ function.

6. But as soon as C++ dll loaded from the ruby script by ffi calls the .Net dll method - I get following error:
_Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CSharp.Demo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at CSharpTest(basic_string<char\,std::char_traits<char>\,std::allocator<char> >* , SByte* inputValue)
   at CppTest(SByte* inputValue) in c:\full_path\demo.cpp:line 5_

7. Questions:
 - Any ideas why does it happen?
 - Does the ffi even suppose to work with the C++ dll which have a .Net dll dependency? 
 - If so, do we have samples by any chance?

I know this post might be a bit long and confusing, so let me know if some clarifications are needed.
Would appreciate any feedback.
Thanks in advance!

**Comment by larskanis** [comment]
You're using RubyInstaller on Windows? I know about two specifics the RubyInstaller makes use of in regards of DLL loading:
1. ruby.exe doesn't use classic DLL load paths by iterating through the PATH environment variable as described here: https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#user-content-dll-loading
2. ruby.exe uses a side-by-side-assembly manifest which could interfere with the .Net DLL loading. See https://github.com/oneclick/rubyinstaller2/blob/8225034c22152d8195bc0aabc42a956c79d6c712/recipes/sandbox/60-side-by-side-assembly.rake#L1

Both issues can be debugged by [that way](https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#-debug-dll-loading).

Alternatively you can avoid the above two specifics by running a MINGW64-terminal of MSYS2 (either from RubyInstaller-Devkit or dedicated MSYS2). It is in `C:/msys64/mingw64.exe`. Then install ruby from MINGW packages by `pacman -S mingw-w64-x86_64-ruby`. `ruby -v` in the terminal should then show version 2.7.3 or so. This ruby.exe doesn't use side-by-side-assemblies or dedicated DLL load paths, so it's worth to test you ffi issue there.

**Comment by vprokopenko** [comment]
Hi @larskanis 
Thanks for the feedback, but the issue is no longer relevant since we've went with different approach.
I guess I'll close the ticket now.
