### ISSUE TITLE
1.15.3 throws bullseye codecoverage error

### ISSUE THREAD

**Issue by dpmdpm57** [ffi/ffi#907]
Running rspec against my unit test spec file this error is thrown.

BullseyeCoverage 8.15.5 error 15: Cannot find /work/ws-git/release_engineering/nasuni-role_puppet_dev/test.cov. COVFILE is not set, errno=2. Executable is c spec/classes/role_puppet_dev_spec.rb

It does not happen with 1.15.2 or lower 
What I found in my installation of 1.15.3 is a test.cov file . 
$HOME/.pdk/cache/ruby/2.5.0/gems/ffi-1.15.3/ext/ffi_c/test.cov

From what I know of bullseye codecoverage that test.cov is generated when the bullseye is enabled as the compiler.

My dev environment. Note.  I removed bullseye/bin from the environment
pdk (INFO): Using Ruby 2.5.8
pdk (INFO): Using Puppet 6.17.0
Run options: exclude {:bolt=>true}

**Comment by larskanis** [comment]
The file `ffi-1.15.3/ext/ffi_c/test.cov` is not part of the gem. It's obviously generated by your local compiler.
Sorry I can not help more.

**Comment by dpmdpm57** [comment]
Actually your reply was very help. Thank you.
I'm new to how gems work and are installed. I guess when I first started I can only the gem install process found bullseye compiler and create the test.cov

I removed pdk/cache/ruby/2.5.0/gems/ffi-1.15.3 and rspec did not throw error.
I found and assume this is correct location. .pdk/cache/ruby/2.5.0/extensions/x86_64-linux/2.5.0/ffi-1.15.3

Thanks again
