### ISSUE TITLE
`bundler exec` does not pass AWS session into the share lib

### ISSUE THREAD

**Issue by samof76** [ffi/ffi#909]
This happens with bundler versions above `2.1.0`, but works perfectly fine with earlier versions. I have library(.so) that works some AWS objects the session gets passed through the environment it operates on. But when I try to call any functionality that needs to perform some AWS operation it fails with 

```
NoCredentialProviders: no valid providers in chain (StandardError)
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: no route to host
```

But the same program works with older versions of bundler say **2.0.0**. 

Why I say that this might be a ffi issue is because if try to dump the session just before the `ffi_lib` call I get the expect session details? So I am suspecting that somehow the right environment is not getting passed into the library when using the latest bundler.

Any help will be truly appreciated.

**Comment by larskanis** [comment]
You probably need to debug your application more deeply. Possibly byebug or gdb can help you. But I'm very sure this isn't an ffi issue. Sorry for being unable to help you more.

Please reopen this issue of you have a prove that ffi is causing it. At best add a reproducible example.
