### ISSUE TITLE
unable to resolve type 'intptr_t' (TypeError)

### ISSUE THREAD

**Issue by 98-f355-f1** [ffi/ffi#921]
I am trying to use a gem that depends upon ffi...

gems/3.0.0/gems/ffi-1.11.3/lib/ffi/types.rb:66:in `find_type': unable to resolve type 'intptr_t' (TypeError)

I have looked through the files, personally I can't tell if the corrrect platform is being used, which should be x86_64-windows.  I see in the types.conf file the names of the datatypes... I can't fix.

env:
OS: Windows 10 version 21H2
Ruby: mingw64/mingw-w64-x86_64-ruby 3.0.2-4 

using gem: seeing_is_believing

Please let me know how to fix this

**Comment by larskanis** [comment]
Could you please try a more recent version of ffi? There have been updates of types on x86_64-windows.
