### ISSUE TITLE
Support for memory_view

### ISSUE THREAD

**Issue by kojix2** [ffi/ffi#926]
* https://docs.ruby-lang.org/en/master/doc/memory_view_md.html
* https://github.com/ruby-numo/numo-narray/issues/27
* Fiddle code
  * https://github.com/ruby/fiddle/blob/master/ext/fiddle/pointer.c
  * https://github.com/ruby/fiddle/blob/master/ext/fiddle/memory_view.c
* https://tech.speee.jp/entry/2020/12/24/093131 [Japanese]

**Comment by dsisnero** [comment]
Also https://github.com/ffi/ffi/issues/862

**Comment by kojix2** [comment]
sorry!
