### ISSUE TITLE
Could not open library 'ucrt.dll'

### ISSUE THREAD

**Issue by MTG2000** [ffi/ffi#934]
I just cloned a jekyll project that has ffi as a dependency, ran bundle install, then when running 
bundle exec jekyll serve its failing and giving me this error:

C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/ffi-1.13.1/lib/ffi/library.rb:145:in 'block in ffi_lib': Could not open library 'c': The specified module could not be found.\r (LoadError)

Could not open library 'ucrt.dll': The specified module could not be found.\r
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/ffi-1.13.1/lib/ffi/library.rb:99:in 'map'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/ffi-1.13.1/lib/ffi/library.rb:99:in 'ffi_lib'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/ethon-0.12.0/lib/ethon/libc.rb:8:in '<module:Libc>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/ethon-0.12.0/lib/ethon/libc.rb:6:in '<module:Ethon>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/ethon-0.12.0/lib/ethon/libc.rb:1:in '<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/ethon-0.12.0/lib/ethon.rb:14:in 'require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/ethon-0.12.0/lib/ethon.rb:14:in '<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in 'require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in '<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/html-proofer-3.18.8/lib/html-proofer/url_validator.rb:3:in 'require'        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/html-proofer-3.18.8/lib/html-proofer/url_validator.rb:3:in '<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/html-proofer-3.18.8/lib/html-proofer.rb:7:in 'require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/html-proofer-3.18.8/lib/html-proofer.rb:7:in 'block in require_all'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/html-proofer-3.18.8/lib/html-proofer.rb:6:in 'each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/html-proofer-3.18.8/lib/html-proofer.rb:6:in 'require_all'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/html-proofer-3.18.8/lib/html-proofer.rb:12:in '<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.2.14/lib/bundler/runtime.rb:66:in 'require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.2.14/lib/bundler/runtime.rb:66:in 'block (2 levels) in require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.2.14/lib/bundler/runtime.rb:61:in 'each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.2.14/lib/bundler/runtime.rb:61:in 'block in require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.2.14/lib/bundler/runtime.rb:50:in 'each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.2.14/lib/bundler/runtime.rb:50:in 'require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.2.14/lib/bundler.rb:173:in 'require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.1.1/lib/jekyll/plugin_manager.rb:53:in 'require_from_bundler'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.1.1/exe/jekyll:11:in '<top (required)>'
        from C:/Ruby31-x64/bin/jekyll:25:in 'load'
        from C:/Ruby31-x64/bin/jekyll:25:in '<main>'

what is the reason for this error ??
do I need to install something extra ??
I'm on a windows 10 machine.

Thanks for your help.

**Comment by larskanis** [comment]
Please update the ffi gem. That should fix your issue.

**Comment by MTG2000** [comment]
Yup
deleting the Gemfile.lock and installing deps again solved the issue
Thanks for the help !!
