### ISSUE TITLE
Finalizer exception behavior changed in Ruby 3.1.0

### ISSUE THREAD

**Issue by JasonLunn** [ffi/ffi#967]
***Background***
I `attach_function` a native method used as a finalizer like so (inside a class called `MyFFI`):

`attach_function :free_widget,   :Widget_Free,  [Widget], :void`

Where `Widget` is a class that looks something like this:

```ruby
class Widget
  extend ::FFI::DataConverter
  native_type ::FFI::Type::POINTER

  class << self
    prepend TypeSafety

    def to_native(value, _)
      value.instance_variable_get(:@widget) || ::FFI::Pointer::NULL
    end

    def from_native(value, _)
      new(value)
    end
  end

  def initialize(pointer)
    @widget = ::FFI::AutoPointer.new(pointer, MyFFI.method(:free_widget))
  end
end
```

The `TypeSafety` module looks like the following, and is based on the [blog post](https://www.varvet.com/blog/advanced-topics-in-ruby-ffi/#:~:text=the%20same%20type.-,module%20TypeSafety,-def%20to_native) that is linked to from the [FFI Wiki on Types](https://github.com/ffi/ffi/wiki/Types) [as an aside, I'd love to see the FFI team refresh the documentation on this, as the blog post seems dated and includes some [recommendations](https://www.varvet.com/blog/advanced-topics-in-ruby-ffi/#:~:text=class%20Device%20%3C%20FFI%3A%3APointer%0Aend%0Aattach_function%20%3Asome_function%2C%20%5B%20%5D%2C%20Device) that don't work any more].

```ruby
module TypeSafety
  def to_native(value, _)
    if value.kind_of?(self) or value.nil?
      super
    else
      raise TypeError, "expected a kind of #{name}, was #{value.class}"
    end
  end
end
```

I ***thought*** this had been working fine for me with `ffi (1.15.5)` across multiple ruby 2.x versions, JRuby 9.2.x and JRuby 9.3.x. However, when I tested the same code out on Ruby 3.1.0, the finalizer failed loudly, throwing an exception like this:

```
Exception in finalizer #<FFI::AutoPointer::CallableReleaser:0x0000000111856378 @ptr=#<FFI::Pointer address=0x00007ffaa10c4d80>, @proc=#<Method: MyFFI.free_widget(*)>, @autorelease=true>
type_safety.rb:41:in `to_native': expected a kind of Widget, was FFI::Pointer (TypeError)
```

Upon investigation, I found that the call had been failing consistently across the same versions where I thought it was working, but on older Ruby versions the exception within the finalizer was being silently swallowed.

Does FFI consider it expected behavior that the finalizers get invoked with FFI::Pointer, rather than their wrapper objects? If so, I think that the documentation should call out that the `attach_method` definition for finalizer methods must use `:pointer` in their arguments, and cannot use custom types.

**Comment by larskanis** [comment]
Sorry for the late answer! I'll still try to answer for completeness and to document that there's no bug in FFI.

There is a fundamental issue when implementing an object finalizer: You're not allowed to use the object that is getting garbage collected in the finalizer. That's the reason to use a plain pointer and not the wrapping object.

You might use two ruby methods for calling the `Widget_Free` function like so:
```ruby
attach_function :free_widget, :Widget_Free, [Widget], :void
attach_function :free_widget_ptr, :Widget_Free, [:pointer], :void
private_class_method :free_widget_ptr
```

The first method could be called for manual freeing the widget and the latter one can be used for the AutoPointer:
```ruby
@widget = ::FFI::AutoPointer.new(pointer, MyFFI.method(:free_widget_ptr))
```

Older rubies just abort silently if there's an exception in the finalizer, but ruby-3.1 prints a warning, making it much easier to notice issues when freeing objects.
