### ISSUE TITLE
ERROR:  Error installing ffi: ERROR: Failed to build gem native extension. Mac M1 Ventura

### ISSUE THREAD

**Issue by minhka195** [ffi/ffi#977]
I just updated to mac ventura and installed gem and got this error, can anyone give me a solution?
Chip: M1
OS:  macOS Ventura

`Building native extensions. This could take a while...
ERROR:  Error installing ffi:
ERROR: Failed to build gem native extension.
current directory: /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c
/Users/minhka/.rvm/rubies/ruby-2.7.6/bin/ruby -I /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0 -r ./siteconf20221026-72369-19xqld6.rb extconf.rb
checking for ffi_prep_closure_loc() in -lffi... no
checking for ffi_prep_closure_loc() in -llibffi... no
checking for ffi_prep_closure_loc() in -llibffi-8... no
checking for whether -Wl,--exclude-libs,ALL is accepted as LDFLAGS... no
checking for whether -pthread is accepted as LDFLAGS... yes
creating extconf.h
creating Makefile

current directory: /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c
make "DESTDIR=" clean

current directory: /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c
make "DESTDIR="
Configuring libffi
/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/configure: line 18692: readelf: command not found
clang: error: unsupported option '-print-multi-os-directory'
clang: error: no input files
cd "/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi-arm64-darwin22" && /Applications/Xcode.app/Contents/Developer/usr/bin/make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in include
make[3]: Nothing to be done for `all'.
Making all in testsuite
make[3]: Nothing to be done for `all'.
Making all in man
make[3]: Nothing to be done for `all'.
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi  -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src   -Wall -fexceptions -c -o src/prep_cif.lo /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/prep_cif.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src -Wall -fexceptions -c /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/prep_cif.c  -fno-common -DPIC -o src/.libs/prep_cif.o
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi  -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src   -Wall -fexceptions -c -o src/types.lo /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/types.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src -Wall -fexceptions -c /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/types.c  -fno-common -DPIC -o src/.libs/types.o
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi  -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src   -Wall -fexceptions -c -o src/raw_api.lo /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/raw_api.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src -Wall -fexceptions -c /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/raw_api.c  -fno-common -DPIC -o src/.libs/raw_api.o
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi  -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src   -Wall -fexceptions -c -o src/java_raw_api.lo /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/java_raw_api.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src -Wall -fexceptions -c /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/java_raw_api.c  -fno-common -DPIC -o src/.libs/java_raw_api.o
/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/java_raw_api.c:328:46: warning: 'ffi_java_raw_size' is deprecated [-Wdeprecated-declarations]
  ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
                                             ^
include/ffi.h:299:56: note: 'ffi_java_raw_size' has been explicitly marked deprecated here
size_t ffi_java_raw_size (ffi_cif *cif) __attribute__((deprecated));
                                                       ^
/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/java_raw_api.c:331:3: warning: 'ffi_java_ptrarray_to_raw' is deprecated [-Wdeprecated-declarations]
  ffi_java_ptrarray_to_raw (cif, avalue, raw);
  ^
include/ffi.h:295:93: note: 'ffi_java_ptrarray_to_raw' has been explicitly marked deprecated here
void ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw) __attribute__((deprecated));
                                                                                            ^
2 warnings generated.
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi  -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src   -Wall -fexceptions -c -o src/closures.lo /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/closures.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src -Wall -fexceptions -c /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/closures.c  -fno-common -DPIC -o src/.libs/closures.o
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi  -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src   -Wall -fexceptions -c -o src/aarch64/ffi.lo /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/aarch64/ffi.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src -Wall -fexceptions -c /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/aarch64/ffi.c  -fno-common -DPIC -o src/aarch64/.libs/ffi.o
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi  -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src  -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src  -c -o src/aarch64/sysv.lo /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/aarch64/sysv.S
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src -I. -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include -Iinclude -I/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src -c /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/aarch64/sysv.S  -fno-common -DPIC -o src/aarch64/.libs/sysv.o
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -Wall -fexceptions   -o libffi_convenience.la  src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo   src/aarch64/ffi.lo src/aarch64/sysv.lo 
libtool: link: ar cru .libs/libffi_convenience.a src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/aarch64/.libs/ffi.o src/aarch64/.libs/sysv.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libffi_convenience.a(ffi.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libffi_convenience.a(sysv.o) has no symbols
libtool: link: ranlib .libs/libffi_convenience.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libffi_convenience.a(ffi.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libffi_convenience.a(sysv.o) has no symbols
libtool: link: ( cd ".libs" && rm -f "libffi_convenience.la" && ln -s "../libffi_convenience.la" "libffi_convenience.la" )
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -Wall -fexceptions -no-undefined -version-info `grep -v '^#' /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi/libtool-version`     -o libffi.la -rpath /usr/local/lib src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo  src/aarch64/ffi.lo src/aarch64/sysv.lo 
libtool: link: gcc -dynamiclib  -o .libs/libffi.8.dylib  src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/aarch64/.libs/ffi.o src/aarch64/.libs/sysv.o      -install_name  /usr/local/lib/libffi.8.dylib -compatibility_version 10 -current_version 10.0 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_ffi_call", referenced from:
      _ffi_raw_call in raw_api.o
      _ffi_java_raw_call in java_raw_api.o
  "_ffi_closure_trampoline_table_page", referenced from:
      _ffi_trampoline_table_alloc in closures.o
  "_ffi_prep_cif_machdep", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_cif_machdep_var", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_closure_loc", referenced from:
      _ffi_prep_closure in prep_cif.o
      _ffi_prep_raw_closure_loc in raw_api.o
      _ffi_prep_java_raw_closure_loc in java_raw_api.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libffi.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** ["/Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/ext/ffi_c/libffi-arm64-darwin22"/.libs/libffi_convenience.a] Error 2

make failed, exit code 2

Gem files will remain installed in /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/ffi-1.15.5 for inspection.
Results logged to /Users/minhka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/extensions/arm64-darwin-22/2.7.0/ffi-1.15.5/gem_make.out

**Comment by iKronyck** [comment]
+1
