### ISSUE TITLE
Install fails on windows 10 x64

### ISSUE THREAD

**Issue by lucaspast** [ffi/ffi#980]
I'm not able to install the ffi gem no matter what I trie and find online. here is the console line output.

[gem_make.log](https://github.com/ffi/ffi/files/10147423/gem_make.log)

**Comment by larskanis** [comment]
Hm, RailsInstaller is no longer maintained. Just use a recent RubyInstaller version to work with rails. It has some recommendations for rails in addition: https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-rails
