### ISSUE TITLE
JRuby on Windows fails on `winapi_error`

### ISSUE THREAD

**Issue by larskanis** [ffi/ffi#984]
Recent CI runs [fail on Windows](https://github.com/ffi/ffi/actions/runs/3673763975/jobs/6211192575#step:8:49) in [that spec](https://github.com/ffi/ffi/blob/2ea1a4348dbdd336d01b5c84be5837930aaea36f/spec/ffi/errno_spec.rb#L28).

I verified, that the result of `FFI::LastError.error` is correct, but as the spec failure tells, the value of `FFI::LastError.winapi_error` is set to `0`. The JRuby method `winapi_error` is defined [here](https://github.com/jruby/jruby/blob/a309a88614916621de4cc5dc3693f279dae58d0c/core/src/main/java/org/jruby/ext/ffi/jffi/Factory.java#L134). It executes `GetLastError()` immediately, instead of delivering the last error value that was current after the C function call. So obviously the Win32 error state is changed by some Java code that is executed between the call to the C function and the call to `winapi_error`.

`FFI::LastError.error` and `FFI::LastError.winapi_error` can only differ on Cygwin. If Cygwin is not supported, then it would be enough to alias `winapi_error` to `error`. Otherwise it makes sense to store the Win32 `GetLastError` value beneath the `errno` value immediately after the C function has been called. This is how the [ffi C extension works](https://github.com/ffi/ffi/blob/2ea1a4348dbdd336d01b5c84be5837930aaea36f/ext/ffi_c/LastError.c#L195).

The last successful run was on [2022-05-04](https://github.com/ffi/ffi/actions/runs/2267464233/jobs/3368512659) and the first failing run on [2022-05-25](https://github.com/ffi/ffi/actions/runs/2386381742). There were no changes on ffi in that time frame. I tried to find a related commit in JRuby that caused that change, but there was no obviously one.

@headius Can you please have a look at this?

**Comment by ahorek** [comment]
I guess a different test assigns an errno which shouldn't affect the current context. It doesn't fail on my windows environment, but let's try to alias it, it should be more error prone. Fix https://github.com/jruby/jruby/pull/7527

**Comment by larskanis** [comment]
This is solved in JRuby.
